celesticabmc: openbmc-utils: add support for NL2 BIOS firmware update
Summary:
# Description

Netlake 2.0 (the new COMe) uses the AMD EPYC Fire Range CPU, and BIOS has used 64M flash chip.

# Motivation

This PR is used to change the host flash size to 64M and added a check for BIOS flash file size to prevent firmware files from being misused between NL1.0 and NL2.0.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1909

Test Plan:
```
**Test on NL2.0 COMe based platform:**
root@bmc-oob:/mnt/data# bios_update.sh write NL2108.rom
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
....
Writing NL2108.rom to COME_BIOS...
dd: number 0 is not in 1..2147483647 range
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.5.1 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org
Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 3ffffff
Verifying flash... VERIFIED.
/////////////////Program a wrong file--netlake 1.0 ///////////////////
root@bmc-oob:/tmp# bios_update.sh write NL405.bin
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 2.0 detected (Value: 0x99)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Error: File size is less than 64MB for Netlake 2.0.
Cleanup: Execution failed or interrupted (Status 1)
```
**Test on NL1.0 COMe based platform:**
```
root@bmc-oob:/mnt/data# bios_update.sh write NL405.bin
Identifying board type...
....
Netlake 1.0 detected (Value: 0x0d)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
failed to export (aspeed-gpio, GPIOG0): File exists
Flash file size:33554432
Writing NL405.bin to COME_BIOS...
1+0 records in
1+0 records out
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.5.1 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org
Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 3ffffff
Verifying flash... VERIFIED.
root@bmc-oob:/tmp# bios_update.sh write NL2108.rom
Identifying board type...
Netlake 1.0 detected (Value: 0x0d)
failed to export (aspeed-gpio, GPIOG0): File exists
Error: File size exceeds 32MB for Netlake 1.0.
Cleanup: Execution failed or interrupted (Status 1)
/////////////////Program a wrong file--netlake 2.0 ///////////////////
root@bmc-oob:/tmp# bios_update.sh write NL2108.rom
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
failed to export (aspeed-gpio, GPIOG0): File exists
Netlake 1.0 detected (Value: 0x0d)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Error: File size exceeds 32MB for Netlake 1.0.
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:/tmp#
```
[nl1_bios_update_pr.txt](https://github.com/user-attachments/files/26271129/nl1_bios_update_pr.txt)
[nl1_iob_update_pr.txt](https://github.com/user-attachments/files/26271157/nl1_iob_update_pr.txt)
[nl2_bios_update_pr.txt](https://github.com/user-attachments/files/26271172/nl2_bios_update_pr.txt)
[nl2_iob_update_pr.txt](https://github.com/user-attachments/files/26271196/nl2_iob_update_pr.txt)

Reviewed By: binhuang00

Differential Revision: D98291093

Pulled By: ezeob002

fbshipit-source-id: c4c2bd22fe6c6502123ffd9440c0b83501968d77