GT: Enable ncsid and name-util (#3167)
Summary:
TestPlan:
Kernel:5.10
SOC:ast2600

root@bmc-oob:~# name-util
ERROR: RequiredError: fru_type is required
Name Utility
Shows all possible FRU names on the system
(Not all FRUs may be present)

Usage: name-util [OPTIONS] fru_type

Positionals:
  fru_type TEXT:{server_fru,nic_fru,bmc_fru,all} REQUIRED
                              Type of FRU

Options:
  -h,--help                   Print this help message and exit

root@bmc-oob:~# name-util all
{
    "bmc_fru": [
        "bmc"
    ],
    "nic_fru": [
        "nic0",
        "nic1"
    ],
    "server_fru": [
        "mb"
    ],
    "version": "1.0.0"
}

root@bmc-oob:~# log-util all --print |grep ncsid
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 NIC AEN Supported: 0x7, AEN Enable Mask=0x7
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 PLDM type supported = 0x35
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 PLDM type 0 version = 1.0.0.0
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 PLDM type 2 version = 1.1.0.0
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 PLDM type 4 version = 1.0.0.0
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 PLDM type 5 version = 1.0.0.0
4    nic0     2018-03-10 00:30:17    ncsid            FRU: 4 PLDM sensor monitoring enabled

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3167

Reviewed By: garnermic

fbshipit-source-id: 831e9edf02e2db87a3377bfab0bebd3f05cb6938