Fix failed yamp test
Summary:
There is a sensor test that is failing on yamp due to the fact
that the threshold comparison is too tight. This diff fixes the issue

Test Plan:
Failure sample.
```
Cmd: python3 /usr/local/bin/tests2/cit_runner.py --run-test
tests.yamp.test_sensor.SupSensorTest.test_sup_temp_range
Return Code: 1
Stdout: test_sup_temp_range (tests.yamp.test_sensor.SupSensorTest) ...
======================================================================
FAIL: test_sup_temp_range (tests.yamp.test_sensor.SupSensorTest)
(key='Sup Temp2')
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/bin/tests2/tests/yamp/test_sensor.py", line 357, in
test_sup_temp_range
msg="{} value is {} not within range".format(key, value),
AssertionError: 19.800000000000001 != 40 within 20 delta : Sup
Temp2 value is 19.8 not within range

----------------------------------------------------------------------
Ran 1 test in 0.729s

FAILED (failures=1)

Stderr:
```

Working example after the code change.
```
root@fboss200932622-oob:/usr/local/bin/tests2# python cit_runner.py
--platform yamp --run-test
tests.yamp.test_sensor.SupSensorTest.test_sup_temp_range
test_sup_temp_range (tests.yamp.test_sensor.SupSensorTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.545s

OK
root@fboss200932622-oob:/usr/local/bin/tests2#
```

Reviewed By: vineelasmile

fbshipit-source-id: 7a5e963b0c