Add ViperB0 option to board-utils.sh
Summary:
# Description

Adding ViperB0 support to the Bmc image. The Meta Eeprom data for ViperB0 will contain `MERU800BIAB` in its product field, so this needs to be accounted for where the product field is tested.

X-link: https://github.com/facebookexternal/openbmc.arista/pull/377

Test Plan:
Tested `wedge_power.sh reset`:
Before, it fails because `MERU800BIAB` is not accepted:
```
root@bmc:~# wedge_power.sh reset
Power reset x86 (userver) ...Error: Unexpected product name detected.
Error: Unexpected product name detected.
 Done
```
After, it passes:
```
root@bmc:~# wedge_power.sh reset
Power reset x86 (userver) ... Done
```
Ran the cit tests with `--platform meru`:
```
----------------------------------------------------------------------
Ran 12 tests in 145.681s
```
OK

Reviewed By: alandau

Differential Revision: D63722881

Pulled By: joancaneus

fbshipit-source-id: 6eed451770027e0f756c0ec140ae67aa45174ee2