morgan800cc: cit: Fix attribute checks in eeprom and rest endpoint
Summary:
# Description

Currently EEPROM and REST endpoint are effected for CIT in morgan800cc due to some base code changes. This PR will address that issue.

Failure logs for reference:
```
======================================================================
FAIL: test_version (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_version)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_eeprom_test.py", line 83, in test_version
    self.assertTrue(re.search(r"^Version\s*:", self.eeprom_info, re.MULTILINE))
AssertionError: None is not true

======================================================================
FAIL: test_version (tests.morgan800cc.test_eeprom.SCMEepromTest.test_version)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_eeprom_test.py", line 83, in test_version
    self.assertTrue(re.search(r"^Version\s*:", self.eeprom_info, re.MULTILINE))
AssertionError: None is not true

======================================================================
FAIL: test_endpoint_api_sys_mb_fruid (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid) (attrib='Assembled At')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_rest_endpoint_test.py", line 153, in verify_endpoint_attributes
    self.assertIn(
AssertionError: 'Assembled At' not found in '{"Information": {"Product Name": "MORGAN800CC", "Product Part Number": "27-100062", "System Assembly Part Number": "SYSA1234", "Meta PCBA Part Number": "PCBA12345678", "Meta PCB Part Number": "PCB123456789", "ODM/JDM PCBA Part Number": "73-21366-03", "ODM/JDM PCBA Serial Number": "FLM281708HR", "Product Production State": "1", "Product Version": "1", "Product Sub-Version": "1", "Product Serial Number": "FLM282006R3", "System Manufacturer": "FLEXTRONICS", "System Manufacturing Date": "20240101", "PCB Manufacturer": "WUS", "Assembled at": "MEXICO", "EEPROM location on Fabric": "FCB", "BMC MAC Base": "f8:39:18:b6:2d:ae", "BMC MAC Address Size": "1", "Switch ASIC MAC Base": "f8:39:18:b6:2d:af", "Switch ASIC MAC Address Size": "144", "CRC16": "0x1f80"}, "Actions": [], "Resources": []}' : endpoint /api/sys/mb/fruid missing attrib Assembled At

----------------------------------------------------------------------
```

# Motivation

Main motivation is to get the CIT green for morgan800cc platform by fixing the affected test cases.

X-link: https://github.com/facebookexternal/openbmc.cisco/pull/109

Test Plan:
UT is to run the CIT again.
```
root@bmc-oob:/run/tests2# python cit_runner.py --platform morgan800cc
test_bmc_mac (tests.morgan800cc.test_bmc_mac.BMCMacTest.test_bmc_mac) ... ok
test_bmc_mac_oui (tests.morgan800cc.test_bmc_mac.BMCMacTest.test_bmc_mac_oui) ... skipped 'No OUI check for BMC MAC'
test_bmc_mac_address (tests.morgan800cc.test_bmc_mac_address.bmc_mac_address.test_bmc_mac_address) ... ok
test_busybox_usage_strings (tests.morgan800cc.test_busybox_syntax.BusyBoxSyntaxTest.test_busybox_usage_strings) ... ok
test_cpu_utilization (tests.morgan800cc.test_cpu_utilization.CpuUtilizationTest.test_cpu_utilization)
Test that CPU utilization is below a threshold. ... ok
test_asset_tag (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_asset_tag) ... ok
test_bmc_mac (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_bmc_mac) ... ok
test_extended_mac_base (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_extended_mac_base) ... ok
test_local_mac (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_local_mac) ... ok
test_location_on_fabric (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_location_on_fabric) ... ok
test_odm_pcb (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_odm_pcb) ... ok
test_product_name (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_product_name)
Tests if the platform defined product name is present ... ok
test_product_part_number (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_product_part_number) ... ok
test_product_serial_number (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_product_serial_number) ... ok
test_switch_asic_mac (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_switch_asic_mac) ... ok
test_system_manufacturer (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_system_manufacturer) ... ok
test_version (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_version) ... skipped 'Version attribute is not present in Chassis Eeprom'
test_x86_mac (tests.morgan800cc.test_eeprom.CHASSISEepromTest.test_x86_mac) ... skipped 'x86 mac is not present in Chassis Eeprom'
test_asset_tag (tests.morgan800cc.test_eeprom.SCMEepromTest.test_asset_tag) ... ok
test_bmc_mac (tests.morgan800cc.test_eeprom.SCMEepromTest.test_bmc_mac) ... skipped 'BMC mac is not present in SCM Eeprom'
test_extended_mac_base (tests.morgan800cc.test_eeprom.SCMEepromTest.test_extended_mac_base) ... ok
test_local_mac (tests.morgan800cc.test_eeprom.SCMEepromTest.test_local_mac) ... ok
test_location_on_fabric (tests.morgan800cc.test_eeprom.SCMEepromTest.test_location_on_fabric) ... ok
test_odm_pcb (tests.morgan800cc.test_eeprom.SCMEepromTest.test_odm_pcb) ... ok
test_product_name (tests.morgan800cc.test_eeprom.SCMEepromTest.test_product_name)
Tests if the platform defined product name is present ... ok
test_product_part_number (tests.morgan800cc.test_eeprom.SCMEepromTest.test_product_part_number) ... ok
test_product_serial_number (tests.morgan800cc.test_eeprom.SCMEepromTest.test_product_serial_number) ... ok
test_switch_asic_mac (tests.morgan800cc.test_eeprom.SCMEepromTest.test_switch_asic_mac) ... skipped 'ASIC switch mac is not present in SCM Eeprom'
test_system_manufacturer (tests.morgan800cc.test_eeprom.SCMEepromTest.test_system_manufacturer) ... ok
test_version (tests.morgan800cc.test_eeprom.SCMEepromTest.test_version) ... skipped 'Version attribute is not present in SCM Eeprom'
test_x86_mac (tests.morgan800cc.test_eeprom.SCMEepromTest.test_x86_mac) ... ok
test_fw_printenv_noheader_status (tests.morgan800cc.test_fw_env.TestFwEnv.test_fw_printenv_noheader_status) ... ok
test_fw_printenv_status (tests.morgan800cc.test_fw_env.TestFwEnv.test_fw_printenv_status) ... ok
test_fw_setenv (tests.morgan800cc.test_fw_env.TestFwEnv.test_fw_setenv) ... ok
test_gpios (tests.morgan800cc.test_gpio.GpioTest.test_gpios)
Python's subTest will run the test 'gpio_shadow_path' for every gpio ... ok
test_host_mac (tests.morgan800cc.test_host_mac.HostMacTest.test_host_mac) ... ok
test_host_mac_zero_test (tests.morgan800cc.test_host_mac.HostMacTest.test_host_mac_zero_test) ... ok
test_i2c_tree (tests.morgan800cc.test_i2c.I2cTest.test_i2c_tree)
check if i2c devices are created and drivers are binded properly. ... ok
test_i2c_driver_presence (tests.morgan800cc.test_i2c_driver_presence.Morgan800ccI2cDriverPresenceTest.test_i2c_driver_presence) ... ok
test_eth0_4088_v6_interface (tests.morgan800cc.test_interface.InterfaceTest.test_eth0_4088_v6_interface)
Tests eth0 v6 interface ... ok
test_eth0_4088_v6_interface_link_local (tests.morgan800cc.test_interface.InterfaceTest.test_eth0_4088_v6_interface_link_local)
Tests eth0 v6 interface ... ok
test_eth0_v4_interface (tests.morgan800cc.test_interface.InterfaceTest.test_eth0_v4_interface)
Tests eth0 v4 interface ... skipped 'Test not supported in environment'
test_eth0_v6_interface (tests.morgan800cc.test_interface.InterfaceTest.test_eth0_v6_interface)
Tests eth0 v6 interface ... ok
test_usb0_v6_interface (tests.morgan800cc.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests usb0 v6 interface ... ok
test_kernel_path_exists (tests.morgan800cc.test_kernel_abi.KernelABITest.test_kernel_path_exists) ... ok
test_installed_kmods (tests.morgan800cc.test_kernel_module_presence.KernelModulePresenceTest.test_installed_kmods) ... ok
test_mTerm (tests.morgan800cc.test_mTerm.mTerm.test_mTerm) ... ok
test_pid (tests.morgan800cc.test_pid_serialnum.sys_networkd_config.test_pid) ... ok
test_serial_num (tests.morgan800cc.test_pid_serialnum.sys_networkd_config.test_serial_num) ... ok
test_process_restarts (tests.morgan800cc.test_process_restart.ProcessRestartTest.test_process_restarts) ... ok
test_installed_processes (tests.morgan800cc.test_process_running.ProcessRunningTest.test_installed_processes) ... ok
test_endpoint_api (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api) ... ok
test_endpoint_api_sys (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys) ... ok
test_endpoint_api_sys_bmc (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc) ... ok
test_endpoint_api_sys_bmc_mtd (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc_mtd) ... ok
test_endpoint_api_sys_bmc_secondary_boot (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc_secondary_boot) ... ok
test_endpoint_api_sys_fc_present (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_fc_present) ... ok
test_endpoint_api_sys_firmware_info_all (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_firmware_info_all) ... skipped 'not available'
test_endpoint_api_sys_mb (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb) ... ok
test_endpoint_api_sys_mb_fruid (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid) ... ok
test_endpoint_api_sys_sensors (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) ... skipped 'not available'
test_endpoint_api_sys_server (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_server) ... skipped 'not available'
test_server_httperror_code_404 (tests.morgan800cc.test_rest_endpoint.RestEndpointTest.test_server_httperror_code_404)
Test if REST server return 404 code when url is not accessible ... ok
test_spi_driver_presence (tests.morgan800cc.test_spi_driver_presence.SpiDriverPresenceTest.test_spi_driver_presence) ... ok
test_syslog_logs (tests.morgan800cc.test_syslog.TestSyslog.test_syslog_logs) ... ok
test_syslog_restart_no_duplicates (tests.morgan800cc.test_syslog_restart.SyslogRestartTest.test_syslog_restart_no_duplicates) ... ok
test_syslog_restart_pid_changed (tests.morgan800cc.test_syslog_restart.SyslogRestartTest.test_syslog_restart_pid_changed) ... ok
test_uboot_version_check (tests.morgan800cc.test_uboot_version_check.UbootVersionCheck.test_uboot_version_check) ... ok
test_wedge_power_off (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_off)
Tests wedge power off ... ok
test_wedge_power_off_concurrent (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_off_concurrent)
Test multiple instances running 'off' command concurrently. ... ok
test_wedge_power_on (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_on)
Tests wedge power on ... ok
test_wedge_power_on_force (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_on_force)
Tests wedge power on with force ... ok
test_wedge_power_reset (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_reset)
Tests wedge power reset ... ok
test_wedge_power_reset_concurrent (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_reset_concurrent)
Test multiple instances running 'reset' command concurrently. ... ok
test_wedge_power_status (tests.morgan800cc.test_wedge_power.WedgePowerTest.test_wedge_power_status)
Tests wedge power status ... ok
test_weutil_crc (tests.morgan800cc.test_weutil.Weutil.test_weutil_crc) ... ok
test_weutil_local_asset_tag (tests.morgan800cc.test_weutil.Weutil.test_weutil_local_asset_tag) ... ok
test_weutil_local_mac (tests.morgan800cc.test_weutil.Weutil.test_weutil_local_mac) ... ok
test_weutil_part_number (tests.morgan800cc.test_weutil.Weutil.test_weutil_part_number) ... ok
test_weutil_product_name (tests.morgan800cc.test_weutil.Weutil.test_weutil_product_name) ... ok
test_weutil_product_serial (tests.morgan800cc.test_weutil.Weutil.test_weutil_product_serial) ... ok
test_weutil_product_sub_version (tests.morgan800cc.test_weutil.Weutil.test_weutil_product_sub_version) ... ok
test_weutil_product_version (tests.morgan800cc.test_weutil.Weutil.test_weutil_product_version) ... ok

----------------------------------------------------------------------
Ran 83 tests in 229.104s

OK (skipped=10)
root@bmc-oob:
```

Reviewed By: doranand

Differential Revision: D75989442

Pulled By: tao-ren

fbshipit-source-id: b26ec7db8b235424a5bf8516776ccb4bc5af3032