unittest: add "i2cUtils.py" common library
Summary:
Add "i2cUtils.py" which contains library functions for i2c unit test.
More functions/classes will be added/moved to the file later.

Test Plan:
root@bmc-oob:/tmp# ./i2cUtils.py
Error: invalid command line arguments!
Usage: ./i2cUtils.py <i2c-bus-num> <dev-addr-hex>

root@bmc-oob:/tmp# ./i2cUtils.py 8 0x77
no devices probed on i2c bus 8
4 devices skipped on i2c bus 8:
  - 0x22
  - 0x33
  - 0x70
  - 0x77
i2c bus 8, address 0x77: device detected
root@bmc-oob:/tmp# ./i2cUtils.py 8 0x73
no devices probed on i2c bus 8
4 devices skipped on i2c bus 8:
  - 0x22
  - 0x33
  - 0x70
  - 0x77
i2c bus 8, address 0x73: no device present

Reviewed By: vineelasmile

fbshipit-source-id: 93d79328e