yosemite: yosemite-sensors: add missing -lrt
Summary:
Observed the following compile error due to changes in other library's
linking structure.  shm_open is used directly by the package, so add it
to the link flags in the makefile.

```
../build-yosemite/tmp/work/armv5e-fb-linux-gnueabi/yosemite-sensors/0.1-r1/recipe-sysroot/usr/lib/libyosemite_sensor.so: undefined reference to `shm_open'
```

Test Plan: Build passes CIT.

Reviewed By: benwei13

fbshipit-source-id: 8e88b1e504