evb-npcm845: disable due to unbuildable
Summary:
The job which imports the LF tree to our internal source mirror is
failing with the following:

```
There were 21 WARNING messages.
There was 1 ERROR message, returning a non-zero exit code.
ERROR: Nothing PROVIDES 'evb-npcm845-image'
[31mE> Shell error: Return Code 1 while running download-mirror command
```

This machine is currently unbuildable with the way our tooling expects.
Disable it for now until it build successfully so that the automation
works.

Test Plan: Simple comment out machine.

Reviewed By: peterdelevoryas

fbshipit-source-id: c3aa5ef2131436bd1a88d0e5563aa3a4212b4bfa