FBAL: Support 4S block power, when FW update on going. (#2106)
Summary:
TestPlan:
  platform:FBAL
  Kernel:5.0.3

    MB0:
      root@bmc-oob:~# fw-util cpld --update glb_cpld /tmp/AngelsLanding_Global_TOP_cfm0_auto.rpd_signed
      Singed Key Match
      rpd file size = 270336 bytes.
      OnChip Flash Status = 0xFFFFFC00.
      image type = 0x1.
      Max10 Unprotect Sector 5.
      Max10 Erase Sector 5
      Erase sector SUCCESS.
      Max10 Erase Sector 0
      Erase sector SUCCESS.
      Progress: Addr: 0x8BFFC  [100 %]

    MB1:
      1.Global CPLD FW update:
        root@bmc-oob:~# fw-util cpld --update glb_cpld /tmp/AngelsLanding_Global_TOP_cfm0_auto.rpd_signed
        Global CPLD FW update is on going.
        Upgrade of cpld : glb_cpld failed

      2.DC on/off
        root@bmc-oob:~# power-util mb off
        FW update for mb is ongoing, block the power controlling.
        ERROR: power-util fru[1] [PWR_OFF] failed

        root@bmc-oob:~# power-util mb on
        FW update for mb is ongoing, block the power controlling.
        ERROR: power-util fru[1] [PWR_ON] failed

      3.sled-cycle
        root@bmc-oob:~# power-util sled-cycle
        FW update for mb is ongoing, block the power controlling.
        ERROR: power-util fru[255] [SLED_CYCLE] failed

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/2106

Reviewed By: benwei13

fbshipit-source-id: 78592251c0