fuji: cit: change sensor name SMB_XP1R8V_CSU (#1332)
Summary:
change sensor name from **SMB_XP1R84V_CSU** to **SMB_XP1R8V_CSU** in CIT sensor list

to fix CIT ERROR
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p fuji --run-test tests.fuji.test_sensor.SmbSensorTest
test_smb_sensor_keys (tests.fuji.test_sensor.SmbSensorTest) ...
======================================================================
FAIL: test_smb_sensor_keys (tests.fuji.test_sensor.SmbSensorTest) (key='SMB_XP1R84V_CSU')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/fuji/test_sensor.py", line 408, in test_smb_sensor_keys
    self.assertIn(
AssertionError: 'SMB_XP1R84V_CSU' not found in dict_keys(['present', 'SMB_XP3R3V_BMC', 'SMB_XP2R5V_BMC', 'SMB_XP1R8V_BMC', 'SMB_XP1R2V_BMC', 'SMB_XP1R0V_FPGA', 'SMB_XP3R3V_USB', 'SMB_XP5R0V', 'SMB_XP3R3V_EARLY', 'SMB_LM57_VTEMP', 'SMB_XP1R8', 'SMB_XP1R2', 'SMB_VDDC_SW', 'SMB_XP3R3V', 'SMB_XP1R8V_AVDD', 'SMB_XP1R2V_TVDD', 'SMB_XP0R75V_1_PVDD', 'SMB_XP0R75V_2_PVDD', 'SMB_XP0R75V_3_PVDD', 'SMB_VDD_PCIE', 'SMB_XP0R84V_DCSU', 'SMB_XP0R84V_CSU', 'SMB_XP1R8V_CSU', 'SMB_XP3R3V_TCXO', 'SMB_OUTPUT_VOLTAGE_XP0R75V_1', 'SMB_OUTPUT_CURRENT_XP0R75V_1', 'SMB_INPUT_VOLTAGE_1', 'SMB_OUTPUT_VOLTAGE_XP1R2V', 'SMB_OUTPUT_CURRENT_XP1R2V', 'SMB_OUTPUT_VOLTAGE_XP0R75V_2', 'SMB_OUTPUT_CURRENT_XP0R75V_2', 'SMB_INPUT_VOLTAGE_2', 'SMB_TMP422_U20_1_TEMP', 'SMB_TMP422_U20_2_TEMP', 'SMB_TMP422_U20_3_TEMP', 'SIM_LM75_U1_TEMP', 'SMB_LM75B_U51_1_TEMP', 'SMB_LM75B_U57_TEMP', 'SMB_LM75B_U39_TEMP', 'SMB_VDDC_SW_TEMP', 'SMB_XP12R0V_VDDC_SW_IN', 'SMB_VDDC_SW_IN_SENS', 'SMB_VDDC_SW_POWER_IN', 'SMB_VDDC_SW_POWER_OUT', 'SMB_VDDC_SW_CURR_IN', 'SMB_VDDC_SW_CURR_OUT', 'PDB_L_TMP75_U2_TEMP', 'PDB_L_TMP75_U3_TEMP', 'PDB_R_TMP75_U2_TEMP', 'PDB_R_TMP75_U3_TEMP', 'FCB_FCM1_TMP75_U1_TEMP', 'FCB_FCM1_TMP75_U2_TEMP', 'FCB_FCM2_TMP75_U1_TEMP', 'FCB_FCM2_TMP75_U2_TEMP', 'FCM-T_CHIP_INPUT_VOLTAGE', 'FCM-T_POWER_CURRENT', 'FCM-T_POWER_VOLTAGE', 'FCM-B_CHIP_INPUT_VOLTAGE', 'FCM-B_POWER_CURRENT', 'FCM-B_POWER_VOLTAGE', 'FAN1_FRONT_SPEED', 'FAN1_REAR_SPEED', 'FAN2_FRONT_SPEED', 'FAN2_REAR_SPEED', 'FAN3_FRONT_SPEED', 'FAN3_REAR_SPEED', 'FAN4_FRONT_SPEED', 'FAN4_REAR_SPEED', 'FAN5_FRONT_SPEED', 'FAN5_REAR_SPEED', 'FAN6_FRONT_SPEED', 'FAN6_REAR_SPEED', 'FAN7_FRONT_SPEED', 'FAN7_REAR_SPEED', 'FAN8_FRONT_SPEED', 'FAN8_REAR_SPEED', 'SMB_SENSOR_TH4_HIGH']) : Missing key SMB_XP1R84V_CSU in SMB sensor data

----------------------------------------------------------------------
Ran 1 test in 0.085s

FAILED (failures=1)
```

TestPlan:
CIT test passed.
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p fuji --run-test tests.fuji.test_sensor.SmbSensorTest
test_smb_sensor_keys (tests.fuji.test_sensor.SmbSensorTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.082s

OK
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1332

Reviewed By: mikechoifb

fbshipit-source-id: 5a00a11d33956dc0894071691c0de500e1784253