cit: montblanc: Remove BMC EEPROM I2C Device Entry
Summary:
# Description

This pull request removes the BMC EEPROM i2c entry from the list of i2c trees to be tested in the CIT

# Motivation

The BMC EEPROM access has been removed from the BMC image. Consequently, it's essential to remove the corresponding I2C device entry from the CIT to ensure accurate testing.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1763

Test Plan:
Without the fix:
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p montblanc --run-test  tests.montblanc.test_i2c
test_i2c_tree (tests.montblanc.test_i2c.I2cTest.test_i2c_tree)
check if i2c devices are created and drivers are binded properly. ...
  test_i2c_tree (tests.montblanc.test_i2c.I2cTest.test_i2c_tree) (i2c_path='8-0051')
check if i2c devices are created and drivers are binded properly. ... FAIL

======================================================================
FAIL: test_i2c_tree (tests.montblanc.test_i2c.I2cTest.test_i2c_tree) (i2c_path='8-0051')
check if i2c devices are created and drivers are binded properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_i2c_test.py", line 79, in test_i2c_tree
    self.check_i2c_device(i2c_path, i2c_info)
  File "/usr/local/bin/tests2/common/base_i2c_test.py", line 46, in check_i2c_device
    self.assertTrue(
AssertionError: False is not true : 8-0051 (name=24c64, driver=at24) is missing

----------------------------------------------------------------------
Ran 1 test in 0.019s

FAILED (failures=1)
```

After Fix:
```
root@bmc-oob:/usr/local/bin/tests2# vim tests/montblanc/test_data/i2c/i2c.py root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p montblanc --run-test  tests.montblanc.test_i2c
test_i2c_tree (tests.montblanc.test_i2c.I2cTest.test_i2c_tree)
check if i2c devices are created and drivers are binded properly. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.015s

OK
```

Reviewed By: mikechoifb

Differential Revision: D57485080

Pulled By: alandau

fbshipit-source-id: 1ffa263cb1480963d2d7033fffa17e4cc2108c6b