fby35: Add qemuboot configuration
Summary:
Implementing `qemuboot.bbclass` and providing these options lets us use `runqemu` from a bitbake environment after building an `fby35-image`.

Note: We _have_ to run it as `runqemu nographic`, not just `runqemu`, because the $#@!'ing `runqemu` script appends some arguments without spaces and produces an invalid command line otherwise, and there's no way to resolve it through the various options except to pass the `nographic` argument.

I fully intend to add something to replace `runqemu` so that it's actually usable, but we can start with this for now.

Test Plan:
```
$ source openbmc-init-build-env fby35 build
$ bitbake fby35-image
$ runqemu nographic
runqemu - INFO - Running bitbake -e ...
runqemu - INFO - Continuing with the following parameters:
KERNEL: []
MACHINE: [fby35]
FSTYPE: [none]
ROOTFS: []
CONFFILE: [/home/pdel/openbmc/build/tmp/deploy/images/fby35/fby35-image-fby35-20220805011632.qemuboot.conf]

runqemu - INFO - Running /home/pdel/openbmc/build/tmp/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-arm    -drive file=/home/pdel
/openbmc/build/tmp/deploy/images/fby35/flash-fby35,format=raw,if=mtd,snapshot=on      -drive file=/home/pdel/openbmc/build/tmp/deploy/images/fby35/flash-fby35,format=raw
,if=mtd,snapshot=on  -machine fby35-bmc   -m 1G -serial mon:stdio -serial null -nographic

U-Boot SPL 2019.04 fby35-dc71cb7ff7-dirty (Aug 03 2022 - 04:50:17 +0000)
SYS_INIT_RAM_END=10016000
CONFIG_SYS_INIT_SP_ADDR=10015000
CONFIG_MALLOC_F_ADDR=10012000
gd = sp = 10011f10
fdt=000184dc
Setup flash: write enable, addr4B, CE1 AHB 64MB window
Setup FMC_CE_CTRL = 0x00000033
Watchdog: 300s
BSM unlocked after BMC reboot
GIU_HW_OPEN configured, booting with GIU_OPEN mode
hwstrap write protect SCU508=0x00000000, SCU518=0x00000000
should_lock=0, giu_mode=0xEA
Before: CE0_CTRL=0x00000600, CE1_CTRL=0x00000004
cs0_status = 1, cs1_status = 2
After: CE0_CTRL=0x00000400, CE1_CTRL=0x00000400
vboot_reset 583
SPL Could not find TPM (ret=-5)
Booting recovery U-Boot.
Blindly jumping to 0x20040000

U-Boot 2019.04 fby35-dc71cb7ff7-dirty (Aug 03 2022 - 04:50:17 +0000)

SOC: AST2600-A3
...
ok: run: restapi: (pid 1225) 0s

OpenBMC Release fby35-dc71cb7ff7-dirty

bmc-oob. login: Error: Read failed
Error: Read failed
Setup fscd for fby35...
ok: down: fscd: 0s, normally up
slot is pulled out, stop fscd.
Setting Zone 0 speed to 100%
Setting Zone 1 speed to 100%
Setting Zone 2 speed to 100%
Setting Zone 3 speed to 100%
QEMU 7.0.90 monitor - type 'help' for more information
(qemu) q
```

`ctrl-a, c` to enter the monitor, and then `q` to quit after that.

Reviewed By: williamspatrick

fbshipit-source-id: f59e0e4b95fe7bf107e2c29019d29644bf2f2a29