tahan: host-recovery: fix bug, busybox-1.38.0 affact spi upgrade failure
Summary:
# Description
In spi-utils.sh, use flashrom with --flash-size option insteads grep and cut command

# Motivation
To fix the issue while upgrade iob_flash and come_bios error as below
```
Error: Image size (33554432 B) doesn't match the expected size (67108864 B)!
```

## Root cause
From Busybox upgrade from v1.37.0 to v1.38.0
'cut' command with '-f 0' cannot use anymore.
```
root@bmc-oob:~# busybox | head -n 1
BusyBox v1.37.0 () multi-call binary.
root@bmc-oob:~# echo "1 2 3 4 5" | cut -d' ' -f 0
1
root@bmc-oob:~# echo "1 2 3 4 5" | cut -d' ' -f 1
1
root@bmc-oob:~#
```
```
root@bmc:~# busybox | head -n 1
BusyBox v1.38.0 () multi-call binary.
root@bmc:~# echo "1 2 3 4 5" | cut -d' ' -f 0
cut: invalid range 0-0
root@bmc:~# echo "1 2 3 4 5" | cut -d' ' -f 1
1
root@bmc:~
```
## Solutions
To stability if the flashrom may change output format in future, change the script to use flashrom --flash-size insteads grep and cut text.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1931

Test Plan:
Validate on tahan platform
```
root@bmc:~# bios_update.sh write NL405.bin
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
exporting gpio (aspeed-gpio, GPIOG4), shadow=BMC_IOB_FLASH_SEL
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
[  121.134985] spi-aspeed-smc 1e630000.spi: CE0 window resized to 32MB
[  121.217555] spi-aspeed-smc 1e630000.spi: CE0 window (32MB) too small for mapping
[  121.326558] spi-aspeed-smc 1e630000.spi: No good frequency, using dumb slow
[  121.418299] spi-aspeed-smc 1e630000.spi: CE0 read buswidth:1 [0x000c0041]
[  121.507859] 1 fixed-partitions partitions found on MTD device spi1.0
[  121.591714] Creating 1 MTD partitions on "spi1.0":
[  121.654828] 0x000000000000-0x000002000000 : "host-flash"
Writing NL405.bin to COME_BIOS...
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.6.0 on Linux 6.12.55-tahan (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (32768 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 1ffffff
Verifying flash... VERIFIED.
[  206.014244] Deleting MTD partitions on "spi1.0":
[  206.075138] Deleting host-flash MTD partition
root@bmc:~#
```

Reviewed By: Scott8440

Differential Revision: D106634729

Pulled By: ezeob002

fbshipit-source-id: b4f5dde47fe2ba171fb97865cf1241754c81da58