GT: Sign component support force update (#3542)
Summary:
1. Sign component support force update
2. Change GT platform some namings for sign component
3. Fix a bug that may cause component update failed but return success.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3542

Test Plan:
1. Update VR
2. Force update VR

Testing:
root@bmc-oob:# fw-util mb --version cpu0_vccin
VR_CPU0_VCCIN/VCCFA_FIVRA Version: Renesas 4f541b00, Remaining Write: 25
root@bmc-oob:#
root@bmc-oob:#
root@bmc-oob:# fw-util mb --update cpu0_vccin /tmp/test.hex
Configuration GEN3 CRC (Production): 4F541B00
Update VR: VR_CPU0_VCCIN/VCCFA_FIVRA
WARNING: the CRC is the same as used now 4F541B00! Please use "--force" option to try again.
ERROR: VR Firmware update failed!
/tmp/mb_signed_update.bin
Update component with temp file failed. error(-1)
Upgrade of mb : cpu0_vccin failed
root@bmc-oob:#
root@bmc-oob:#
root@bmc-oob:# fw-util mb --force --update cpu0_vccin /tmp/test.hex
Configuration GEN3 CRC (Production): 4F541B00
Update VR: VR_CPU0_VCCIN/VCCFA_FIVRA
Remaining writes: 25
updated: 100 %
Force upgrade of mb : cpu0_vccin succeeded

Reviewed By: garnermic

Differential Revision: D42928555

fbshipit-source-id: ea43b5df2343d4c2d6dfdbefc2bdc6c27c83f5ee