tools: qemu: Refactor arg that requires Python3.7
Summary:
The 'required' argument for subparsers was added in Python3.7, but a lot of people use Python3.6 on devservers because you can install python packages for it using `dnf`. To remove this dependency, I've just replaced the argument with setting the attribute directly. This works in 3.6 and 3.8.

The reason we even have this is that it specifies an appropriate error message if you don't specify a subcommand, instead of just crashing.

Test Plan:
Before:

```
pdel@devvm9194:/data/users/pdel/openbmc2$ python3 --version
Python 3.8.6
pdel@devvm9194:/data/users/pdel/openbmc2$ python3 ./tools/experimental/qemu/qrun
usage: qrun [-h] {list-machines,tap,start} ...
qrun: error: the following arguments are required: subcommand
pdel@devvm9194:/data/users/pdel/openbmc2$ python3.6 ./tools/experimental/qemu/qrun
Traceback (most recent call last):
  File "./tools/experimental/qemu/qrun", line 189, in <module>
    main()
  File "./tools/experimental/qemu/qrun", line 135, in main
    subparsers = parser.add_subparsers(dest='subcommand', required=True)
  File "/usr/lib64/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

After:

```
pdel@devvm9194:/data/users/pdel/openbmc2$ python3 ./tools/experimental/qemu/qrun
usage: qrun [-h] {list-machines,tap,start} ...
qrun: error: the following arguments are required: subcommand
pdel@devvm9194:/data/users/pdel/openbmc2$ python3.6 ./tools/experimental/qemu/qrun
usage: qrun [-h] {list-machines,tap,start} ...
qrun: error: the following arguments are required: subcommand
```

Reviewed By: zhdaniel12

fbshipit-source-id: 2fbddd3f5fdc206444a598301d880e5f273f8ba6