fbal: revise TI VR pout workaround (#2198)
Summary:
To fix that 0xce register is not restored when VR version is not 2.7.10.0,
and which will cause the VR cannot be updated. ex:

root@bmc-oob:~# fw-util vr --force --update cpu0_vccio /tmp/98D.csv
Update VR: VR_CPU0_VCCIO
File CRC : 0552
ERROR: VR Firmware update failed!
Force upgrade of vr : cpu0_vccio failed

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/2198

Test Plan:
Build and test pass on fbal
Check all VRs' register 0xce, bit6 of byte[10] are cleared:

root@bmc-oob:~# cat /var/log/messages |grep vr
 2020 Dec 21 00:23:22 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr workaround addr=0xC0 version=2.7.10.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr addr=0xC4 version=2.7.9.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr workaround addr=0xCC version=2.7.10.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr workaround addr=0xD0 version=2.7.10.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr workaround addr=0xD8 version=2.7.10.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr workaround addr=0xE0 version=2.7.10.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr addr=0xE4 version=2.7.9.0
 2020 Dec 21 00:23:23 bmc-oob. user.warning angelslanding-v2020.52.0.Test: sensord: vr workaround addr=0xEC version=2.7.10.0

root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xc0 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8f aa fa af ff ff 87 c4 87 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xc4 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8f ff ff ff ff ff 07 c4 07 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xcc 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8a af ff ff ff ff 07 c4 87 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xd0 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8a af ff ff ff ff 07 c4 87 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xd8 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8a af ff ff ff ff 07 c4 87 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xe0 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8f aa fa af ff ff 87 c4 87 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xe4 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8f ff ff ff ff ff 07 c4 07 c4 03 00 00 00
root@bmc-oob:~# ipmitool raw 0x6 0x52 0x3 0xec 0x20 0xce
 1f 0b 04 00 00 08 00 ee 22 0c 80 00 00 1b 00 00
 1b 00 8a af ff ff ff ff 07 c4 87 c4 03 00 00 00

Reviewed By: benwei13

fbshipit-source-id: 85bfc7e265