Add aggregate REST endpoint
Summary:
Currrently, aggregate REST endpoint is missing from route's list, caused
1. CIT test to fail (skipped ATM)
2. Can not get agregate data

This diff fixes above issues and also removes endpoint "scdinfo" which is
not applicable to fuji, and fixes lint issues

Test Plan:
1- CIT:
Before the fix:
```
======================================================================
ERROR: test_endpoint_api_sys_sensors (tests.fuji.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (item='aggregate')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data1/tests2/common/base_rest_endpoint_test.py", line 126, in verify_endpoint_resource
    raise BaseRestEndpointException(
common.base_rest_endpoint_test.BaseRestEndpointException: HTTPError on GET /api/sys/sensors/aggregate : <HTTPError 404: 'Not Found'>

----------------------------------------------------------------------
Ran 1 test in 6.183s
```
After applying the fix:
```
test_endpoint_api_sys_sensors (tests.fuji.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) ... ok

----------------------------------------------------------------------
Ran 1 test in 6.199s

OK
```
2- REST endpoint:
Before the fix:
```
curl -s http://fboss317293514-oob.ash6:8080/api/sys/sensors/aggregate | jq
parse error: Expected string key before ':' at line 1, column 4
```

After applying the fix:
```
curl -s http://fboss317293514-oob.ash6:8080/api/sys/sensors/aggregate | jq
{
  "Information": {
    "name": "aggregate",
    "Adapter": "aggregate",
    "present": true,
    "SYSTEM_AIRFLOW": "NA"
  },
  "Actions": [],
  "Resources": []
}
```

Reviewed By: Scott8440

Differential Revision: D46228432

fbshipit-source-id: df6156c571b3b74171f7f0679033e7a10075334f