fw-util: Add syslog for VR update (#1925)
Summary:
As title

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1925

Test Plan:
Build pass and test on fbep

// If failed to update
root@bmc-oob:~# fw-util vr --update p0v8_vdd0 usb/30h_20-0608.csv
WARNING: the version is the same as used now 0x31!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of vr : p0v8_vdd0 failed

// No completion log
root@bmc-oob:~# log-util all --print
2020 Sep 03 23:12:25 log-util: User cleared all logs
0    all      2020-09-03 23:12:45    fw-util          Component p0v8_vdd0 upgrade initiated

// Try force date
root@bmc-oob:~# fw-util vr --force --update p0v8_vdd0 usb/30h_20-0608.csv
Update VR VR_P0V8_VDD0 to version 0x31
Force upgrade of vr : p0v8_vdd0 succeeded

// Check log
root@bmc-oob:~# log-util all --print
2020 Sep 03 23:12:25 log-util: User cleared all logs
0    all      2020-09-03 23:12:45    fw-util          Component p0v8_vdd0 upgrade initiated
0    all      2020-09-03 23:13:07    fw-util          Component p0v8_vdd0 upgrade initiated
0    all      2020-09-03 23:13:08    fw-util          Component p0v8_vdd0 force upgrade completed

Reviewed By: benwei13

fbshipit-source-id: 8e78cc8462