Add a test to validate 'kv get' works
Summary: Recently we observed a regression in trunk with broken `kv` , a simple test that validated if kv could get data for a key would have caught the regression. Here is such a test.

Test Plan:
> Reproduce the bug seen with a test
```
root@dhcp-100-97-167-25:/usr/local/bin/tests2# python cit_runner.py --platform minipack --run-test tests.minipack.test_kv
test_kv_get_key (tests.minipack.test_kv.KvTest) ... test_kv_path_exists (tests.minipack.test_kv.KvTest) ... ok

======================================================================
ERROR: test_kv_get_key (tests.minipack.test_kv.KvTest) (key='pim1_sensor_health')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/utils/shell_util.py", line 46, in run_shell_cmd
    raise Exception(err + " [FAILED]")
Exception: /bin/sh: /usr/bin/kv: No such file or directory
 [FAILED]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_kv_test.py", line 54, in test_kv_get_key
    run_shell_cmd(cmd)
  File "/usr/local/bin/tests2/utils/shell_util.py", line 51, in run_shell_cmd
    raise Exception("Failed to run command = {} and exception {}".format(cmd, e))
Exception: Failed to run command = /usr/bin/kv get pim1_sensor_health persistent and exception /bin/sh: /usr/bin/kv: No such file or directory
 [FAILED]

======================================================================
ERROR: test_kv_get_key (tests.minipack.test_kv.KvTest) (key='pim2_sensor_health')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/utils/shell_util.py", line 46, in run_shell_cmd
    raise Exception(err + " [FAILED]")
Exception: /bin/sh: /usr/bin/kv: No such file or directory
 [FAILED]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_kv_test.py", line 54, in test_kv_get_key
    run_shell_cmd(cmd)
  File "/usr/local/bin/tests2/utils/shell_util.py", line 51, in run_shell_cmd
    raise Exception("Failed to run command = {} and exception {}".format(cmd, e))
Exception: Failed to run command = /usr/bin/kv get pim2_sensor_health persistent and exception /bin/sh: /usr/bin/kv: No such file or directory
 [FAILED]
```
> When unexpected key was tested for:
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --platform minipack --run-test tests.minipack.test_kv
test_kv_get_key (tests.minipack.test_kv.KvTest) ... test_kv_path_exists (tests.minipack.test_kv.KvTest) ... ok

======================================================================
ERROR: test_kv_get_key (tests.minipack.test_kv.KvTest) (key='blah')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/utils/shell_util.py", line 47, in run_shell_cmd
    raise Exception("{} exited with non-zero exit code".format(cmd))
Exception: /usr/bin/kv get blah persistent exited with non-zero exit code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_kv_test.py", line 56, in test_kv_get_key
    run_shell_cmd(cmd)
  File "/usr/local/bin/tests2/utils/shell_util.py", line 50, in run_shell_cmd
    raise Exception("Failed to run command = {} and exception {}".format(cmd, e))
Exception: Failed to run command = /usr/bin/kv get blah persistent and exception /usr/bin/kv get blah persistent exited with non-zero exit code

----------------------------------------------------------------------
Ran 2 tests in 5.215s

FAILED (errors=1)
```
> when all the keys work
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --platform minipack --run-test tests.minipack.test_kv
test_kv_get_key (tests.minipack.test_kv.KvTest) ... ok
test_kv_path_exists (tests.minipack.test_kv.KvTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 5.388s

OK
```
on this diff KV test

{F341419542}

Reviewed By: williamspatrick, tao-ren

fbshipit-source-id: 30448faf48