fix restapi unit test fail
Summary:
D35186957 break the restapi fwinfo unittest.
root cause was rest_fwinfo.py will read fruid info from a dict using for-loop which doesn't guarantee the output order.
however, in unit test we mock the output of common_utils.async_exec from a list which will guarantee the order thus causing incorrect mapping in test result, [ex](https://www.internalfb.com/intern/sandcastle/job/9007199903971709/insights):
```
AssertionError: {'Information': {'fruid_info': {'nicexp': {[457 chars]: []} != {'Actions': [], 'Information': {'fruid_info[476 chars]: []}
  {'Actions': [],
-  'Information': {'fruid_info': {'bmc': {'model': 'A very good nic',
?                                  ^^

+  'Information': {'fruid_info': {'nic': {'model': 'A very good nic',
?                                  ^^

                                          'part_number': 'PART_NUMBER_42',
                                          'serial_number': 'SERIAL-number-42',
                                          'vendor': 'NIC Manufacturer'},
-                                 'nic': {'model': '',
+                                 'nicexp': {'model': '',
?                                     +++

-                                         'part_number': '',
+                                            'part_number': '',
? +++

-                                         'serial_number': '',
+                                            'serial_number': '',
? +++

-                                         'vendor': ''},
+                                            'vendor': ''},
? +++

-                                 'nicexp': {'model': 'Twin Lakes Passive MP',
?                                  ^^^^^^

+                                 'slot1': {'model': 'Twin Lakes Passive MP',
?                                  ^^^^^

-                                            'part_number': 'I.AM.A.PART',
? -

+                                           'part_number': 'I.AM.A.PART',
-                                            'serial_number': 'MYSERIAL',
? -

+                                           'serial_number': 'MYSERIAL',
-                                            'vendor': 'Mighty manufacturer'}},
? -

+                                           'vendor': 'Mighty manufacturer'}},
+                  'fw_info': {'bic_version': 'BICBICBIC',
-                  'fw_info': {'bmc': {'bmc_cpld_ver': ' CPLD_VERSION_42',
?                  ^^^^^^^^^^^^^^^^^^^^                 -

+                              'bmc_cpld_ver': 'CPLD_VERSION_42',
?                  ^^^^^^^^^^^^

-                                      'bmc_ver': ' fby2-v2021.12.8'}}},
? --------                                         -                  -

+                              'bmc_ver': 'fby2-v2021.12.8'}},
   'Resources': []}

----------------------------------------------------------------------
```
In short, we need to adjust the unittest for D35186957 with:
1. adding `board_setup_var.py` for qemux86, in that we will use list instead of dict to guarantee the output order.
2. Patching missing expected fields like `bmc` to the unit test.

Test Plan: Ptest restapi passed on sandcastle: https://www.internalfb.com/intern/sandcastle/job/4503600279596889/insights

Reviewed By: GoldenBug

fbshipit-source-id: 05d21ea3214f14c5a4e5adb28521df690a615d2d