minipack: Skip usb0 ping test in qemu (unbreaks conveyor)
Summary:
In qemu, usb0 is `UP` but not `RUNNING` and thus can't be pinged,
causing the test to fail.

Test Plan:
Before:
```
root@bmc:~/tests2# python cit_runner.py --denylist qemu_denylist.txt --run-test tests.minipack.test_interface.InterfaceTest.test_usb0_v6_interface
test_usb0_v6_interface (tests.minipack.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests eth0 v6 interface ... ERROR

======================================================================
ERROR: test_usb0_v6_interface (tests.minipack.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests eth0 v6 interface
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/root/tests2/tests/minipack/test_interface.py", line 33, in test_usb0_v6_interface
    self.assertEqual(self.ping_v6(), 0, "Ping test for usb0 v6 failed")
                     ^^^^^^^^^^^^^^
  File "/home/root/tests2/common/base_interface_test.py", line 122, in ping_v6
    ip = self.get_ipv6_address()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/root/tests2/common/base_interface_test.py", line 98, in get_ipv6_address
    ipv6 = self.get_ip_addr_output_inet6()[1].split("/")[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/root/tests2/common/base_interface_test.py", line 86, in get_ip_addr_output_inet6
    raise Exception(
Exception: Device usb0 does not have an IPv6 address [FAILED]
command output:4: usb0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 64
    link/ether 02:00:00:00:00:01 brd ff:ff:ff:ff:ff:ff

----------------------------------------------------------------------
Ran 1 test in 0.086s

FAILED (errors=1)

```

After:
```
root@bmc-oob:/run# python3 tests2/cit_runner.py --denylist /run/tests2/qemu_denylist.txt --run-test tests.minipack.test_interface.InterfaceTest
test_eth0_4088_v6_interface (tests.minipack.test_interface.InterfaceTest.test_eth0_4088_v6_interface)
Tests eth0 v6 interface ... ok
test_eth0_4088_v6_interface_link_local (tests.minipack.test_interface.InterfaceTest.test_eth0_4088_v6_interface_link_local)
Tests eth0 v6 interface ... ok
test_eth0_v4_interface (tests.minipack.test_interface.InterfaceTest.test_eth0_v4_interface)
Tests eth0 v4 interface ... skipped 'Test not supported in environment'
test_eth0_v6_interface (tests.minipack.test_interface.InterfaceTest.test_eth0_v6_interface)
Tests eth0 v6 interface ... ok
test_usb0_v6_interface (tests.minipack.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests usb0 v6 interface ... skipped 'test env is QEMU, skipped'

----------------------------------------------------------------------
Ran 5 tests in 0.340s

OK (skipped=2)
```

Reviewed By: kimdo8736

Differential Revision:
D59495068

Privacy Context Container: L1188897

fbshipit-source-id: 4c72421d418b10fa5e16af30a2cd6ffe41b46fd6