montblanc: add log util (#1521)
Summary:
- implement libpal for montblanc
- add log-util-v2

### TestPlan:
validate log-util able to use
```
root@bmc:~# log-util
ERROR: RequiredError: fru is required
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,scm,sys} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
  -s TEXT                     Starting time for timestamp delete
  -e TEXT Needs: -s           Ending time for timestamp delete
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU
root@bmc:~# log-util all --print
2023 Jan 26 00:27:11 log-util: User cleared all logs
2023 Jan 26 00:27:11 log-util: User cleared FRU: 1 logs
2023 Jan 26 00:27:12 log-util: User cleared sys logs
root@bmc:~#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1521

Reviewed By: binhuang00

Differential Revision: D45305670

fbshipit-source-id: dcb32c6bea2cbcd9ab396e1936339a9ac6178141