fby3: GPv3: remove the duplicate set_fw_update_ongoing() code (#1930)
Summary:
-set_fw_update_ongoing() is found in pal.c and bic_xfer.c.
Move it from bic_xfer.c to bic_ipmi.c for easier management because is_fw_update_ongoing() is put there.
And remove the duplicate code in pal.c

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1930

Test Plan:
-build code(pass)
-check fru_fwupd file is generated(pass)
root@bmc-oob:~# cat /tmp/cache_store/fru1_fwupd
993root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
Please make sure no firmware update is ongoing
ERROR: power-util fru[1] [12V_CYCLE] failed

Reviewed By: garnermic

fbshipit-source-id: 3f5ddbf783