Fix py3 compatibility issue in system.py
Summary:
`subprocess.check_output` in Py3 returns a byte string, we need to
decode it before returning.

```
ERROR:2020-06-27 23:21:27,055 Unhandled exception raised.
Traceback (most recent call last):
  File "/tmp/improve_system.py", line 236, in <module>
    improve_system(logger)
  File "/tmp/improve_system.py", line 169, in improve_system
    system.append_to_kernel_parameters(args.dry_run, mtdparts, logger)
  File "/var/volatile/tmp/system.py", line 456, in append_to_kernel_parameters
    if "mtdparts" in before:
TypeError: a bytes-like object is required, not 'str'
```

Test Plan:
was able to run bmc_pusher with this change w/o crash:

/tmp/pypartition/openbmc.utils.pypartition/47/tmp/bmc_pusher /tmp/openbmc_image/openbmc.image.minipack100/6/flash-minipack1
P134431971

Reviewed By: kawmarco

fbshipit-source-id: 3c031afa09