FBAL:remove jg7 and iox set-usb command (#2184)
Summary:
IOX and JG7 i2c is fixed in MB0 and MB1 don't need switch, We still keep law command to switch it.

root@bmc-oob:~# cm-util
ERROR: RequiredError: At least 1 option from [--set-mode,--sled-cycle,--get-mode,--get-position,--reset-bmc,--get-lan] is required
Chassis Management Utility
[At least 1 of the following options are required]
Usage: cm-util [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --set-mode TEXT:{2S,4S-2OU-0,4S-2OU-1,4S-4OU}
                              Set chassis operating mode
                              2S: 2 Socket Mode
                              4S-2OU-0: 4 Socket mode with Tray 0 as primary
                              4S-2OU-1: 4 Socket mode with Tray 1 as primary
                              4S-4OU: 4 Socket mode, in 4OU mode

  --sled-cycle                Perform a SLED cycle after operations (If any)
  --get-mode                  Get Chassis Operating mode
  --get-position              Get current tray position
  --reset-bmc TEXT:{clearcreek,emeraldpools,tray1}
                              Reset BMC in the specified Tray
  --get-lan TEXT:{clearcreek,emeraldpools,tray1}
                              Get LAN/Network information of the given BMC

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/2184

Reviewed By: benwei13

fbshipit-source-id: 098fa1bbf6