vboot-check: Fix VbootParserException raising
Summary:
I was running vboot-check on an unsigned image, and noticed this:

```
SPL does not contain KEK keys
Exception: __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "./common/recipes-utils/vboot-utils/files/vboot-check.py", line 568, in <module>
    sys.exit(main())
  File "./common/recipes-utils/vboot-utils/files/vboot-check.py", line 361, in main
    ret.update(decode_flash(fh, data))
  File "./common/recipes-utils/vboot-utils/files/vboot-check.py", line 165, in decode_flash
    retval["spl_keys"] = validate_and_parse_keys(
  File "./common/recipes-utils/vboot-utils/files/vboot-check.py", line 78, in validate_and_parse_keys
    raise VbootParserException(code=EC_SPLROM_BAD)
TypeError: __init__() missing 1 required positional argument: 'message'
```

The VbootParserException constructor was:

```
class VbootParserException(Exception):
    def __init__(self, message, code):
        super().__init__(message)
        self.code = code
```

And all the `raise` statements in vboot-check were like this:

```
if "signature" not in fdt_json:
    print(error, file=sys.stderr)
    raise VbootParserException(code=EC_SPLROM_BAD)
```

And after fixing that, the main function was still hiding the exception because it was catching it and then returning the error code. Now the error looks like this:

```
SPL does not contain KEK keys
Traceback (most recent call last):
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 560, in <module>
    main()
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 359, in main
    ret.update(decode_flash(fh, data))
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 163, in decode_flash
    retval["spl_keys"] = validate_and_parse_keys(
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 76, in validate_and_parse_keys
    raise VbootParserException(code=EC_SPLROM_BAD)
VbootParserException
```

Test Plan:
Tested this on locked, unsigned, and signed fby2 images, and verified they produced the same output as the old version (ran `diff <old output> <new output>`)

```
Try loading image meta from image build-fby2/tmp/deploy/images/fby2/flash-fby2.locked
No image meta found: UnicodeDecodeError('utf-8', b'\xfb\xed\xc8_IN\xd9\xa0\xe4\x94\xd5Y9\xc5G\xe7\xff\xc7\xad\xbf\xc0\x90\x0e\xf9\xc5\xc0\'\x943\xbe\xd4\xea\xfc\xf7q)\xbf\xdcF\xf3\xd0\xdbXA\xf4\xe7y\x89MH\xf7\xd7\xd3\x18\xdc+*\x9c3\xd5\xfe\xf1\x98\x7fr\xa0\x8fKR9M\x95#y\xab\xac\x85\xca\xed\xa7r\xa7\xaar\x1a\x95\xdbO\xe5\xfa\xa9\x9cP\xe5\x80Y\xdcL\xe5\x8eR\xb9\x90\xd7\xcd\xb9\xfc\'g\xcf\x88\xf9/\xa5\xf3\xb5tW\x85S\x8au\x14\xfd\x92\xbd\x9f\xe4\xda<\xd1i\xfd\xb1\xe2\x1e\xe4|\xa1qH\xa4 \xeb\x16\xc4\xad\xf4J%{\xbd~\xec\xa3g)p\xc2p\xefU\xfa\x0f\xbe\x01\xbc\x14\xde\x81w\xe1=g\xbc\xace\x0e\xc2_,\xe7\x9a5\xe2\xb7\x87x\xb9\xcf\x8f\xc8\x19\xc7\xb6\x85$\xf1\xbe\x90\x03=\xebY\x7f\x99\x8e\x88\x01\xe0o \x8f\x0e\xfbpAW\x8d\xbc\xd7\xd4\x17_\xa4\xdd\xe1\\\xa2\xc8\x97\tl\xf5`"\xfd\xdd\x0f\x06\xe5\x99L\xfc!\xcd\xd1\xba}\xf3c\xce~\xfa\x1cX\x16s^\xa0\xff/\xd1\xc7\xa2\xef\x07\xe9\x7f?}\x0e\xd3w\xc8', 0, 1, 'invalid start byte')
verifying legacy image
Lockbit: [1]
SPL FIT offset: 68752
  SPL KEK: key-kek1 (sha256,rsa4096) (signs image)
  SPL KEK: key-kek0 (sha256,rsa4096) (signs image)

Subordinate date: Sat Jun 17 20:17:06 UTC 2017 (0x59458e42)
Subordinate timestamp: 1497730626
Subordinate keys signing key: kek0
Subordinate keys hash (sha256): a3e42427fc6c7580a83ddda5ad9b813fbd398537e076d0db32d43f0545bfcca9: OK
  Subordinate: key-fb1 (sha256,rsa4096) (signs conf)
  Subordinate: key-odm1 (sha256,rsa4096) (signs conf)
  Subordinate: key-odm3 (sha256,rsa4096) (signs conf)
  Subordinate: key-odm2 (sha256,rsa4096) (signs conf)
  Subordinate: key-fb0 (sha256,rsa4096) (signs conf)

U-Boot date: Wed Nov 10 18:40:11 UTC 2021 (0x618c120b)
U-Boot timestamp: 1636569611
U-Boot configuration signing key: fb0
U-Boot hash (sha256): 55b34bc82558bd023dfed7dfc2cda02b6b47add04371fad8169995f97d2c46cf: OK

Kernel/ramdisk date: Wed Nov 10 18:40:26 UTC 2021 (0x618c121a)
Kernel/ramdisk timestamp: 1636569626
Kernel/ramdisk configuration signing key: fb0
Kernel hash (sha256): eb54e7d82c3aec04b3fe0cf89f29928c2f0112a14e983de73ff04de0c59a39a4: OK
Ramdisk hash (sha256): 88333d9bf55783fe4b8c0e444d4a8cce68a776936d054d88f2e008ce944b5713: OK
```

```
Try loading image meta from image build-fby2/tmp/deploy/images/fby2/flash-fby2.unsigned
No image meta found: UnicodeDecodeError('utf-8', b'\xfb\xed\xc8_IN\xd9\xa0\xe4\x94\xd5Y9\xc5G\xe7\xff\xc7\xad\xbf\xc0\x90\x0e\xf9\xc5\xc0\'\x943\xbe\xd4\xea\xfc\xf7q)\xbf\xdcF\xf3\xd0\xdbXA\xf4\xe7y\x89MH\xf7\xd7\xd3\x18\xdc+*\x9c3\xd5\xfe\xf1\x98\x7fr\xa0\x8fKR9M\x95#y\xab\xac\x85\xca\xed\xa7r\xa7\xaar\x1a\x95\xdbO\xe5\xfa\xa9\x9cP\xe5\x80Y\xdcL\xe5\x8eR\xb9\x90\xd7\xcd\xb9\xfc\'g\xcf\x88\xf9/\xa5\xf3\xb5tW\x85S\x8au\x14\xfd\x92\xbd\x9f\xe4\xda<\xd1i\xfd\xb1\xe2\x1e\xe4|\xa1qH\xa4 \xeb\x16\xc4\xad\xf4J%{\xbd~\xec\xa3g)p\xc2p\xefU\xfa\x0f\xbe\x01\xbc\x14\xde\x81w\xe1=g\xbc\xace\x0e\xc2_,\xe7\x9a5\xe2\xb7\x87x\xb9\xcf\x8f\xc8\x19\xc7\xb6\x85$\xf1\xbe\x90\x03=\xebY\x7f\x99\x8e\x88\x01\xe0o \x8f\x0e\xfbpAW\x8d\xbc\xd7\xd4\x17_\xa4\xdd\xe1\\\xa2\xc8\x97\tl\xf5`"\xfd\xdd\x0f\x06\xe5\x99L\xfc!\xcd\xd1\xba}\xf3c\xce~\xfa\x1cX\x16s^\xa0\xff/\xd1\xc7\xa2\xef\x07\xe9\x7f?}\x0e\xd3w\xc8', 0, 1, 'invalid start byte')
verifying legacy image
SPL does not contain KEK keys
Traceback (most recent call last):
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 560, in <module>
    main()
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 359, in main
    ret.update(decode_flash(fh, data))
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 163, in decode_flash
    retval["spl_keys"] = validate_and_parse_keys(
  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 76, in validate_and_parse_keys
    raise VbootParserException(code=EC_SPLROM_BAD)
VbootParserException
```

```
Try loading image meta from image build-fby2/tmp/deploy/images/fby2/flash-fby2.signed
No image meta found: UnicodeDecodeError('utf-8', b'\xfb\xed\xc8_IN\xd9\xa0\xe4\x94\xd5Y9\xc5G\xe7\xff\xc7\xad\xbf\xc0\x90\x0e\xf9\xc5\xc0\'\x943\xbe\xd4\xea\xfc\xf7q)\xbf\xdcF\xf3\xd0\xdbXA\xf4\xe7y\x89MH\xf7\xd7\xd3\x18\xdc+*\x9c3\xd5\xfe\xf1\x98\x7fr\xa0\x8fKR9M\x95#y\xab\xac\x85\xca\xed\xa7r\xa7\xaar\x1a\x95\xdbO\xe5\xfa\xa9\x9cP\xe5\x80Y\xdcL\xe5\x8eR\xb9\x90\xd7\xcd\xb9\xfc\'g\xcf\x88\xf9/\xa5\xf3\xb5tW\x85S\x8au\x14\xfd\x92\xbd\x9f\xe4\xda<\xd1i\xfd\xb1\xe2\x1e\xe4|\xa1qH\xa4 \xeb\x16\xc4\xad\xf4J%{\xbd~\xec\xa3g)p\xc2p\xefU\xfa\x0f\xbe\x01\xbc\x14\xde\x81w\xe1=g\xbc\xace\x0e\xc2_,\xe7\x9a5\xe2\xb7\x87x\xb9\xcf\x8f\xc8\x19\xc7\xb6\x85$\xf1\xbe\x90\x03=\xebY\x7f\x99\x8e\x88\x01\xe0o \x8f\x0e\xfbpAW\x8d\xbc\xd7\xd4\x17_\xa4\xdd\xe1\\\xa2\xc8\x97\tl\xf5`"\xfd\xdd\x0f\x06\xe5\x99L\xfc!\xcd\xd1\xba}\xf3c\xce~\xfa\x1cX\x16s^\xa0\xff/\xd1\xc7\xa2\xef\x07\xe9\x7f?}\x0e\xd3w\xc8', 0, 1, 'invalid start byte')
verifying legacy image
Lockbit: not set
SPL FIT offset: 68752
  SPL KEK: key-kek1 (sha256,rsa4096) (signs image)
  SPL KEK: key-kek0 (sha256,rsa4096) (signs image)

Subordinate date: Sat Jun 17 20:17:06 UTC 2017 (0x59458e42)
Subordinate timestamp: 1497730626
Subordinate keys signing key: kek0
Subordinate keys hash (sha256): a3e42427fc6c7580a83ddda5ad9b813fbd398537e076d0db32d43f0545bfcca9: OK
  Subordinate: key-fb1 (sha256,rsa4096) (signs conf)
  Subordinate: key-odm1 (sha256,rsa4096) (signs conf)
  Subordinate: key-odm3 (sha256,rsa4096) (signs conf)
  Subordinate: key-odm2 (sha256,rsa4096) (signs conf)
  Subordinate: key-fb0 (sha256,rsa4096) (signs conf)

U-Boot date: Wed Nov 10 18:39:48 UTC 2021 (0x618c11f4)
U-Boot timestamp: 1636569588
U-Boot configuration signing key: fb0
U-Boot hash (sha256): 55b34bc82558bd023dfed7dfc2cda02b6b47add04371fad8169995f97d2c46cf: OK

Kernel/ramdisk date: Wed Nov 10 18:40:03 UTC 2021 (0x618c1203)
Kernel/ramdisk timestamp: 1636569603
Kernel/ramdisk configuration signing key: fb0
Kernel hash (sha256): eb54e7d82c3aec04b3fe0cf89f29928c2f0112a14e983de73ff04de0c59a39a4: OK
Ramdisk hash (sha256): 88333d9bf55783fe4b8c0e444d4a8cce68a776936d054d88f2e008ce944b5713: OK
```

```
[openbmc:helium] diff fixed.signed.out signed.out
[openbmc:helium] diff fixed.locked.out locked.out
[openbmc:helium] diff fixed.unsigned.out unsigned.out
 --- fixed.unsigned.out  2021-11-10 10:44:40.045362555 -0800
+++ unsigned.out        2021-11-10 10:42:19.255089270 -0800
@@ -2,13 +2,14 @@
 No image meta found: UnicodeDecodeError('utf-8', b'\xfb\xed\xc8_IN\xd9\xa0\xe4\x94\xd5Y9\xc5G\xe7\xff\xc7\xad\xbf\xc0\x90\x0e\xf9\xc5\xc0\'\x943\xbe\xd4\xea\xfc\xf7q)\xbf
\xdcF\xf3\xd0\xdbXA\xf4\xe7y\x89MH\xf7\xd7\xd3\x18\xdc+*\x9c3\xd5\xfe\xf1\x98\x7fr\xa0\x8fKR9M\x95#y\xab\xac\x85\xca\xed\xa7r\xa7\xaar\x1a\x95\xdbO\xe5\xfa\xa9\x9cP\xe5\x8
0Y\xdcL\xe5\x8eR\xb9\x90\xd7\xcd\xb9\xfc\'g\xcf\x88\xf9/\xa5\xf3\xb5tW\x85S\x8au\x14\xfd\x92\xbd\x9f\xe4\xda<\xd1i\xfd\xb1\xe2\x1e\xe4|\xa1qH\xa4 \xeb\x16\xc4\xad\xf4J%{\x
bd~\xec\xa3g)p\xc2p\xefU\xfa\x0f\xbe\x01\xbc\x14\xde\x81w\xe1=g\xbc\xace\x0e\xc2_,\xe7\x9a5\xe2\xb7\x87x\xb9\xcf\x8f\xc8\x19\xc7\xb6\x85$\xf1\xbe\x90\x03=\xebY\x7f\x99\x8e
\x88\x01\xe0o \x8f\x0e\xfbpAW\x8d\xbc\xd7\xd4\x17_\xa4\xdd\xe1\\\xa2\xc8\x97\tl\xf5`"\xfd\xdd\x0f\x06\xe5\x99L\xfc!\xcd\xd1\xba}\xf3c\xce~\xfa\x1cX\x16s^\xa0\xff/\xd1\xc7\
xa2\xef\x07\xe9\x7f?}\x0e\xd3w\xc8', 0, 1, 'invalid start byte')
 verifying legacy image
 SPL does not contain KEK keys
+Exception: __init__() missing 1 required positional argument: 'message'
 Traceback (most recent call last):
-  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 560, in <module>
-    main()
-  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 359, in main
+  File "./common/recipes-utils/vboot-utils/files/vboot-check.bk.py", line 568, in <module>
+    sys.exit(main())
+  File "./common/recipes-utils/vboot-utils/files/vboot-check.bk.py", line 361, in main
     ret.update(decode_flash(fh, data))
-  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 163, in decode_flash
+  File "./common/recipes-utils/vboot-utils/files/vboot-check.bk.py", line 165, in decode_flash
     retval["spl_keys"] = validate_and_parse_keys(
-  File "./common/recipes-utils/vboot-utils/files/vboot-check", line 76, in validate_and_parse_keys
+  File "./common/recipes-utils/vboot-utils/files/vboot-check.bk.py", line 78, in validate_and_parse_keys
     raise VbootParserException(code=EC_SPLROM_BAD)
-VbootParserException
+TypeError: __init__() missing 1 required positional argument: 'message'
```

Reviewed By: zhdaniel12

fbshipit-source-id: 6377715f46