celesticabmc: host-recovery: fix bug, busybox-1.38.0 affact spi upgrade failure
Summary:
# Description
In spi-utils.sh, use flashrom with --flash-size option insteads grep and cut command

# Motivation
To fix the issue while upgrade iob_flash and come_bios error as below
```
Error: Image size (33554432 B) doesn't match the expected size (67108864 B)!
```

## Root cause
From Busybox upgrade from v1.37.0 to v1.38.0
'cut' command with '-f 0' cannot use anymore.

```
root@bmc-oob:~# busybox | head -n 1
BusyBox v1.37.0 () multi-call binary.
root@bmc-oob:~# echo "1 2 3 4 5" | cut -d' ' -f 0
1
root@bmc-oob:~# echo "1 2 3 4 5" | cut -d' ' -f 1
1
root@bmc-oob:~#
```
```
root@bmc:~# busybox | head -n 1
BusyBox v1.38.0 () multi-call binary.
root@bmc:~# echo "1 2 3 4 5" | cut -d' ' -f 0
cut: invalid range 0-0
root@bmc:~# echo "1 2 3 4 5" | cut -d' ' -f 1
1
root@bmc:~
```

## Solutions
To stability if the flashrom may change output format in future, change the script to use flashrom --flash-size insteads grep and cut text.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1933

Test Plan:
Validate on Icecube platform
```
root@bmc:~# bios_update.sh write NL405.bin
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 1.0 detected (Value: 0x0d)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
failed to export (aspeed-gpio, GPIOG0): File exists
Flash file size:33554432
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
exporting gpio (aspeed-gpio, GPIOG4), shadow=BMC_IOB_FLASH_SEL
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
failed to export (aspeed-gpio, GPIOG0): File exists
/usr/local/bin/spi-utils.sh: line 63: echo: write error: No such device
Writing NL405.bin to COME_BIOS...
1+0 records in
1+0 records out
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.6.0 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 3ffffff
Verifying flash... VERIFIED.
root@bmc:~#
```

Reviewed By: joancaneus

Differential Revision: D106748480

Pulled By: ezeob002

fbshipit-source-id: 2c8de9bdd1e57a430fcd78d8e80fbf3bb1d10e94