cit: acctonbmc: Change reset test flow in WedgePowerTest
Summary:
# Description:
Add retry mechanism to run_power_cmd_test

# Motivation:
After wedge_power.sh reset behavior is changed, CIT WedgePowerTest needs to use retry to do the test

X-link: https://github.com/facebookexternal/openbmc.accton/pull/222

Test Plan:
 --- CIT Log ---
-- Before applying this fix --
root@bmc-oob:/run/tests2# python cit_runner.py --platform acctonbmc --run-test tests.acctonbmc.test_wedge_power.WedgePowerTest test_wedge_power_off (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_off) Tests wedge power off ... ok
test_wedge_power_on (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on) Tests wedge power on ... ok
test_wedge_power_on_force (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on_force) Tests wedge power on with force ... ok
test_wedge_power_reset (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_reset) Tests wedge power reset ... ERROR
test_wedge_power_status (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_status) Tests wedge power status ... ok

====================================================================== ERROR: test_wedge_power_reset (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_reset) Tests wedge power reset
---------------------------------------------------------------------- Traceback (most recent call last):
File "/run/tests2/tests/acctonbmc/test_wedge_power.py", line 185, in test_wedge_power_reset
self.run_power_cmd_test("reset"), 0, "Power reset test failed"
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
File "/run/tests2/tests/acctonbmc/test_wedge_power.py", line 124, in run_power_cmd_test
return_code, _ = self.run_power_cmd(cmd)
~~~~~~~~~~~~~~~~~~^^^^^
File "/run/tests2/tests/acctonbmc/test_wedge_power.py", line 83, in run_power_cmd
raise Exception(stderr.decode())
Exception: Reset timed out

---------------------------------------------------------------------- Ran 5 tests in 11.759s

FAILED (errors=1)

-- After applying this fix --
root@bmc-oob:/run/tests2# python cit_runner.py --platform acctonbmc --run-test tests.acctonbmc.test_wedge_power.WedgePowerTest test_wedge_power_off (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_off) Tests wedge power off ... ok
test_wedge_power_on (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on) Tests wedge power on ... ok
test_wedge_power_on_force (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on_force) Tests wedge power on with force ... ok
test_wedge_power_reset (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_reset) Tests wedge power reset ... ok
test_wedge_power_status (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_status) Tests wedge power status ... ok

---------------------------------------------------------------------- Ran 5 tests in 21.102s

OK

Reviewed By: lsiudut

Differential Revision: D87004440

Pulled By: tao-ren

fbshipit-source-id: c3568e5881840f5bcad6992d7c2248a35716964d