FBAL Support 4S EP only mode (#2550)
Summary:
Support 4S+8A Config

root@bmc-oob:~# cm-util
ERROR: RequiredError: At least 1 option from [--set-mode,--recfg-cycle,--get-mode,--get-position,--reset-bmc,--get-lan] is required
Chassis Management Utility
[At least 1 of the following options are required]
Usage: cm-util [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --set-mode TEXT:{2S,4S-0,4S-1,4S-2OU-0,4S-2OU-1}
                              Set chassis operating mode
                              2S: 2 Socket Mode
                              4S-0: 4 Socket EP mode with Tray 0 as primary
                              4S-1: 4 Socket EP mode with Tray 1 as primary
                              4S-2OU-0: 4 Socket EX mode with Tray 0 as primary
                              4S-2OU-1: 4 Socket EX mode with Tray 1 as primary

  --recfg-cycle               Perform a SLED cycle after operations (If any)
  --get-mode                  Get Chassis Operating mode
  --get-position              Get current tray position
  --reset-bmc TEXT:{emeraldpools,tray1}
                              Reset BMC in the specified Tray
  --get-lan TEXT:{emeraldpools,tray1}
                              Get LAN/Network information of the given BMC

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/2550

Reviewed By: GoldenBug

fbshipit-source-id: 2a5999b762