Fix Python 3.12 asyncore issue for lf-dunfell external builds
Summary:
Fix Python 3.12 asyncore issue for lf-dunfell external builds
Python 3.12 removed the asyncore module which is required by bitbake's
pyinotify in lf-dunfell. This adds a fallback to use Python 3.9 for
external builds (no facebook folder) on lf-dunfell platforms.
This fix is only needed for lf-dunfell; lf-master already removed the
asyncore dependency. This happens in all repo.

Test Plan:
Before changes:

```
[uezeobi@devvm23835.ftw0 /data/users/uezeobi/quanta/openbmc.quanta/build_wedge (main)]$ bitbake wedge-image
Traceback (most recent call last):
  File "/data/users/uezeobi/quanta/openbmc.quanta/yocto/lf-dunfell/poky/bitbake/bin/bitbake", line 24, in <module>
    from bb.main import bitbake_main, BitBakeConfigParameters, BBMainException
  File "/data/users/uezeobi/quanta/openbmc.quanta/yocto/lf-dunfell/poky/bitbake/lib/bb/main.py", line 24, in <module>
    from bb import cooker
  File "/data/users/uezeobi/quanta/openbmc.quanta/yocto/lf-dunfell/poky/bitbake/lib/bb/cooker.py", line 25, in <module>
    import pyinotify
  File "/data/users/uezeobi/quanta/openbmc.quanta/yocto/lf-dunfell/poky/bitbake/lib/pyinotify.py", line 45, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'
```
After changes:
```
[uezeobi@devvm23835.ftw0 /data/users/uezeobi/quanta/openbmc.quanta/build_wedge400_4 (main)]$ bitbake wedge400-imag
...
NOTE: Tasks Summary: Attempted 5471 tasks of which 3897 didn't need to be rerun and all succeeded.
```

Reviewed By: williamspatrick

Differential Revision: D93553778

fbshipit-source-id: 61abfa806c4f072f9890db5b27718568ede56195