github: kernel-5.10: update kernel version id
Summary:
The kernel tree is now at 5.10.23.  Update to avoid failures such as:

```
    ERROR: linux-aspeed-5.10.5-r1 do_kernel_version_sanity_check: Package
    Version (5.10.5) does not match of kernel being built (5.10.23). Please
    update the PV variable to match the kernel source or set
    KERNEL_VERSION_SANITY_SKIP="1" in your recipe.
```

Test Plan:
PR with passing CI.
    - https://app.circleci.com/pipelines/github/facebook/openbmc/1902/workflows/ab86ba3f-abcb-42f5-a00c-a1552fef53f5

Reviewed By: jerrt2003, tao-ren

fbshipit-source-id: a9218fb8cf