montblanc: host-recovery: fix bug, busybox-1.38.0 affact spi upgrade failure
Summary:
# Description
In spi-utils.sh, use flashrom with --flash-size option insteads grep and cut command

# Motivation
To fix the issue while upgrade iob_flash and come_bios error as below
```
Error: Image size (33554432 B) doesn't match the expected size (67108864 B)!
```

## Root cause
From Busybox upgrade from v1.37.0 to v1.38.0
'cut' command with '-f 0' cannot use anymore.

```
root@bmc-oob:~# busybox | head -n 1
BusyBox v1.37.0 () multi-call binary.
root@bmc-oob:~# echo "1 2 3 4 5" | cut -d' ' -f 0
1
root@bmc-oob:~# echo "1 2 3 4 5" | cut -d' ' -f 1
1
root@bmc-oob:~#
```

```
root@bmc:~# busybox | head -n 1
BusyBox v1.38.0 () multi-call binary.
root@bmc:~# echo "1 2 3 4 5" | cut -d' ' -f 0
cut: invalid range 0-0
root@bmc:~# echo "1 2 3 4 5" | cut -d' ' -f 1
1
root@bmc:~
```

## Solutions
To stability if the flashrom may change output format in future,
change the script to use flashrom --flash-size insteads grep and cut text.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1928

Test Plan:
Validate on montblanc platform
```
root@bmc:~# spi_util.sh write spi1 COME_BIOS NL405.bin
Select BIOS flash..
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 1.0 detected (Value: 0x05)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Flash file size:33554432
Probe flashes..
[ 4259.687075] spi-aspeed-smc 1e630000.spi: No good frequency, using dumb slow
[ 4259.778750] spi-aspeed-smc 1e630000.spi: CE0 read buswidth:1 [0x000c0041]
[ 4259.868147] 1 fixed-partitions partitions found on MTD device spi1.0
[ 4259.951770] Creating 1 MTD partitions on "spi1.0":
[ 4260.014788] 0x000000000000-0x000004000000 : "host-flash"
Copy NL405.bin to /tmp/.spi_util_image.tmp..
Append 33554432 bytes to /tmp/.spi_util_image.tmp..
Write /tmp/.spi_util_image.tmp to /dev/mtd7..
flashrom v1.6.0 on Linux 6.12.55-montblanc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 3ffffff
Verifying flash... VERIFIED.
Restore environment..
[ 4415.511315] Deleting MTD partitions on "spi1.0":
[ 4415.572106] Deleting host-flash MTD partition
root@bmc:~#
```

```
root@bmc:~# spi_util.sh write spi1 IOB_FPGA mp3_iob_v0.50.bit
Select IOB_FPGA flash..
Probe flashes..
[ 5118.699943] spi-aspeed-smc 1e630000.spi: No good frequency, using dumb slow
[ 5118.791727] spi-aspeed-smc 1e630000.spi: CE0 read buswidth:1 [0x000b0041]
[ 5118.881128] 1 fixed-partitions partitions found on MTD device spi1.0
[ 5118.964809] Creating 1 MTD partitions on "spi1.0":
[ 5119.027800] 0x000000000000-0x000004000000 : "host-flash"
[ 5119.097673] mtd: partition "host-flash" extends beyond the end of device "spi1.0" -- size truncated to 0x1000000
Copy mp3_iob_v0.50.bit to /tmp/.spi_util_image.tmp..
Append 14585095 bytes to /tmp/.spi_util_image.tmp..
Write /tmp/.spi_util_image.tmp to /dev/mtd7..
flashrom v1.6.0 on Linux 6.12.55-montblanc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to ffffff
Verifying flash... VERIFIED.
Restore environment..
[ 5158.331048] Deleting MTD partitions on "spi1.0":
[ 5158.391836] Deleting host-flash MTD partition
root@bmc:~#
```

Reviewed By: Scott8440

Differential Revision: D106481979

Pulled By: ezeob002

fbshipit-source-id: ea1cae8a6e88dd3385b086f8605642ed00c0e7ff