psb-util: Migrate to CLI11
Summary: As title, instead of C style getopt, use CLI11

Test Plan:
Build on half dome and test it out.
```
root@sled3503-oob:~# psb-util
ERROR: RequiredError: fru is required
PSB Utility
Usage: psb-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,slot1,slot3} REQUIRED
                              FRU to show PSB

Options:
  -h,--help                   Print this help message and exit
  --json                      Print output as JSON formatted
  -d,--debug                  Enable Debug
```
```
root@sled3503-oob:~# psb-util all
==================================
slot1
==================================
PlatformVendorID:             0x8D
PlatformModelID:              0x00
BiosKeyRevisionID:            0x00
<snip>

==================================
slot3
==================================
PlatformVendorID:             0x8D
PlatformModelID:              0x00
<snip>
```

```
root@sled3503-oob:~# psb-util slot1
==================================
slot1
==================================
PlatformVendorID:             0x8D
PlatformModelID:              0x00
BiosKeyRevisionID:            0x00
<snip>
```
And the equivalent --json

Reviewed By: williamspatrick

Differential Revision: D43970108

fbshipit-source-id: 300d36dcee934739f5d86b71e443424f4d44f406