netlakemtp: Weutil: refactor CRC location handling
Summary:
# Description:
- Refactor the CRC location discovery to a forward-scan approach.
- Update error handling in CRC checks to prevent false positives.
- For Netlake MB MP testing and the version is netlakemtp-v2026.11.f1

# Motivation:
- The current CRC handling includes a backward byte-pattern scan for the CRC TLV header (0xFA 0x02). This is unsafe in a TLV-encoded EEPROM because it can match the same byte pattern inside a value field or even the CRC value itself—leading to mislocation of the CRC TLV and corruption of the CRC bytes.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3512

Test Plan:
- Build code. - pass
- Write the EEPROM with a pattern that produces the 0xFA 0x02 0xFA 0x02 corner case, then confirm the code handles it correctly. - pass

# Test Log:
- Verify corner case pattern is correctly handled
1. Modify ODM/JDM PCBA Part Number (type 6) CRC value: 0xFAFC root@bmc-oob:~# weutil -m 6 B91.04M10.000E
Read netlake-eeprom ------- [Pass]
Check Header -------------- [Pass]
Check CRC TLV ------------- [Pass]
Modify Value -------------- [Pass]
Calculate CRC-CCITT_AUG --- [Pass]
--------------------------------------------
[EEPROM Data Format : Meta FBOSS V6]
[Write new Data to netlake-eeprom Success!]
root@bmc-oob:# hexdump -C /sys/bus/i2c/devices/4-0056/eeprom 00000000  fb fb 06 ff 01 07 4e 45  54 4c 41 4b 45 02 02 4e  |......NETLAKE..N|
00000010  41 03 08 4e 41 20 20 20  20 20 20 04 0c 31 39 2d  |A..NA      ..19-|
00000020  31 30 30 32 35 37 20 20  20 05 0c 4e 41 20 20 20  |100257   ..NA   |
00000030  20 20 20 20 20 20 20 06  0e 42 39 31 2e 30 34 4d  |       ..B91.04M|
00000040  31 30 2e 30 30 30 45 07  02 4e 41 08 01 04 09 01  |10.000E..NA.....|
00000050  00 0a 01 00 0b 02 4e 41  0c 06 57 49 57 59 4e 4e  |......NA..WIWYNN|
00000060  0d 08 4e 41 20 20 20 20  20 20 0e 02 4e 41 0f 04  |..NA      ..NA..|
00000070  57 59 54 4e 10 03 55 32  30 11 08 00 00 00 00 00  |WYTN..U20.......|
00000080  00 00 00 12 08 00 00 00  00 00 00 00 00 13 08 00  |................|
00000090  00 00 00 00 00 00 00 14  08 00 00 00 00 00 00 00  |................|
000000a0  00 15 01 00 fa 02 fa fc  ff ff ff ff ff ff ff ff  |................|
000000b0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00004000

2. Modify ODM/JDM PCBA Serial Number (type 7) CRC value: 0xFA02 root@bmc-oob:~# weutil -m 7 WK0E60304GFN01
Read netlake-eeprom ------- [Pass]
Check Header -------------- [Pass]
Check CRC TLV ------------- [Pass]
Modify Value -------------- [Pass]
Calculate CRC-CCITT_AUG --- [Pass]
--------------------------------------------
[EEPROM Data Format : Meta FBOSS V6]
[Write new Data to netlake-eeprom Success!]
root@bmc-oob:# hexdump -C /sys/bus/i2c/devices/4-0056/eeprom 00000000  fb fb 06 ff 01 07 4e 45  54 4c 41 4b 45 02 02 4e  |......NETLAKE..N|
00000010  41 03 08 4e 41 20 20 20  20 20 20 04 0c 31 39 2d  |A..NA      ..19-|
00000020  31 30 30 32 35 37 20 20  20 05 0c 4e 41 20 20 20  |100257   ..NA   |
00000030  20 20 20 20 20 20 20 06  0e 42 39 31 2e 30 34 4d  |       ..B91.04M|
00000040  31 30 2e 30 30 30 45 07  0e 57 4b 30 45 36 30 33  |10.000E..WK0E603|
00000050  30 34 47 46 4e 30 31 08  01 04 09 01 00 0a 01 00  |04GFN01.........|
00000060  0b 02 4e 41 0c 06 57 49  57 59 4e 4e 0d 08 4e 41  |..NA..WIWYNN..NA|
00000070  20 20 20 20 20 20 0e 02  4e 41 0f 04 57 59 54 4e  |      ..NA..WYTN|
00000080  10 03 55 32 30 11 08 00  00 00 00 00 00 00 00 12  |..U20...........|
00000090  08 00 00 00 00 00 00 00  00 13 08 00 00 00 00 00  |................|
000000a0  00 00 00 14 08 00 00 00  00 00 00 00 00 15 01 00  |................|
000000b0  fa 02 fa 02 ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
000000c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00004000

3. Modify Product Version (type 9) CRC value: 0x29E3 root@bmc-oob:~# weutil -m 9 2
Read netlake-eeprom ------- [Pass]
Check Header -------------- [Pass]
Check CRC TLV ------------- [Pass]
Modify Value -------------- [Pass]
Calculate CRC-CCITT_AUG --- [Pass]
--------------------------------------------
[EEPROM Data Format : Meta FBOSS V6]
[Write new Data to netlake-eeprom Success!]
root@bmc-oob:# hexdump -C /sys/bus/i2c/devices/4-0056/eeprom 00000000  fb fb 06 ff 01 07 4e 45  54 4c 41 4b 45 02 02 4e  |......NETLAKE..N|
00000010  41 03 08 4e 41 20 20 20  20 20 20 04 0c 31 39 2d  |A..NA      ..19-|
00000020  31 30 30 32 35 37 20 20  20 05 0c 4e 41 20 20 20  |100257   ..NA   |
00000030  20 20 20 20 20 20 20 06  0e 42 39 31 2e 30 34 4d  |       ..B91.04M|
00000040  31 30 2e 30 30 30 45 07  0e 57 4b 30 45 36 30 33  |10.000E..WK0E603|
00000050  30 34 47 46 4e 30 31 08  01 04 09 01 02 0a 01 00  |04GFN01.........|
00000060  0b 02 4e 41 0c 06 57 49  57 59 4e 4e 0d 08 4e 41  |..NA..WIWYNN..NA|
00000070  20 20 20 20 20 20 0e 02  4e 41 0f 04 57 59 54 4e  |      ..NA..WYTN|
00000080  10 03 55 32 30 11 08 00  00 00 00 00 00 00 00 12  |..U20...........|
00000090  08 00 00 00 00 00 00 00  00 13 08 00 00 00 00 00  |................|
000000a0  00 00 00 14 08 00 00 00  00 00 00 00 00 15 01 00  |................|
000000b0  fa 02 29 e3 ff ff ff ff  ff ff ff ff ff ff ff ff  |..).............|
000000c0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00004000

- Verify modify command is aborted when garbage data is detected in the post-CRC region of the EEPROM root@bmc-oob:~# weutil -w Netlake-garbage_value.bin Write Netlake-garbage_value.bin to netlake-eeprom success !

root@bmc-oob:# hexdump -C /sys/bus/i2c/devices/4-0056/eeprom 00000000  fb fb 06 ff 01 07 4e 45  54 4c 41 4b 45 02 02 4e  |......NETLAKE..N|
00000010  41 03 08 4e 41 20 20 20  20 20 20 04 0c 31 39 2d  |A..NA      ..19-|
00000020  31 30 30 32 35 37 20 20  20 05 0c 4e 41 20 20 20  |100257   ..NA   |
00000030  20 20 20 20 20 20 20 06  02 4e 41 07 02 4e 41 08  |       ..NA..NA.|
00000040  01 04 09 01 00 0a 01 00  0b 02 4e 41 0c 06 57 49  |..........NA..WI|
00000050  57 59 4e 4e 0d 08 4e 41  20 20 20 20 20 20 0e 02  |WYNN..NA      ..|
00000060  4e 41 0f 04 57 59 54 4e  10 03 55 32 30 11 08 00  |NA..WYTN..U20...|
00000070  00 00 00 00 00 00 00 12  08 00 00 00 00 00 00 00  |................|
00000080  00 13 08 00 00 00 00 00  00 00 00 14 08 00 00 00  |................|
00000090  00 00 00 00 00 15 01 00  fa 02 2b c3 12 34 56 78  |..........+..4Vx|
000000a0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00004000
root@bmc-oob:~# weutil -m 13 20260311
Read netlake-eeprom ------- [Pass]
Check Header -------------- [Pass]
ERROR: Garbage Data after CRC TLV

Differential Revision: D96094012

fbshipit-source-id: 777e6f6eb332de00ba1f5f668bf8e2b72642ef8c