yosemite: front-paneld: fix compiler warnings with -Wall
Summary:
Fix two types of warnings in front-paneld.

Missing return value from thread function; return NULL to resolve.
```
| front-paneld.c: In function 'debug_card_handler':
| front-paneld.c:182:1: error: no return statement in function returning non-void [-Werror=return-type]
|  }
```

Unused variable; remove.
```
| front-paneld.c: In function 'ts_handler':
| front-paneld.c:314:11: error: unused variable 'por' [-Werror=unused-variable]
|    uint8_t por = 0;
```

Test Plan: Build yosemite image.

Reviewed By: benwei13

fbshipit-source-id: 9e11618c5d