fpc-util: add missing include for strcmp (string.h)
Summary:
Fix compiler warnings where string.h is missing include list.

```
    | fpc-util.c:42:7: error: implicit declaration of function 'strcmp' [-Werror=implicit-function-declaration]
    |    if (strcmp(argv[1], "sled") || strcmp(argv[2], "--identify")) {
    |        ^~~~~~
    | cc1: all warnings being treated as errors
```

Test Plan: Build a few different systems affected by the changes.

Reviewed By: amithash

fbshipit-source-id: 02b74b190f