common: libvr, remove Renesas VR IC_DEVICE_REV check (#3091)
Summary:
The VR update fail in Some fby35 mother board due to VR IC_DEVICE_REV is 5.0.0.0
Renesas programinig guid has note "The device revision number must be 6.0.0.0 or greater"

Confirmed with Renesas FAE,
We can ignore the IC_DEVICE_REV check.
But we need to make sure that legacy IC use legacy HEX and production IC use production HEX.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3091

Test Plan:
before
 ---
root@bmc-oob:~# fw-util slot3 --force --update vr_vccin  /tmp/ISL69260-1\ 0x60.hex
Configuration GEN3 CRC (Legacy): C151AC43
Update VR: VCCIN/VCCFA_EHV_FIVRA
Remaining writes: 22
ERROR: VR Firmware update failed!
Force upgrade of slot3 : vr_vccin failed

root@bmc-oob:~# cat /var/log/messages | grep fw-util
 2022 Jul 31 19:21:04 bmc-oob. authpriv.info fby35-v2022.28.1: -bash[23464]: HISTORY: PID=23464 UID=0 cat /var/log/messages | grep fw-util
 2022 Jul 31 19:21:09 bmc-oob. authpriv.info fby35-v2022.28.1: -bash[23464]: HISTORY: PID=23464 UID=0 fw-util slot3 --force --update vr_vccin  /tmp/ISL69260-1\ 0x60.hex
 2022 Jul 31 19:21:10 bmc-oob. user.err fby35-v2022.28.1: fw-util: bic_ipmb_wrapper: slot3 netfn: 0x06 cmd: 0x52, Completion Code: 0x83
 2022 Jul 31 19:21:10 bmc-oob. user.warning fby35-v2022.28.1: fw-util: bic_get_vr_device_id() Failed to get vr device id, ret=-1
 2022 Jul 31 19:21:10 bmc-oob. user.err fby35-v2022.28.1: fw-util: bic_ipmb_wrapper: slot3 netfn: 0x06 cmd: 0x52, Completion Code: 0x83
 2022 Jul 31 19:21:10 bmc-oob. user.warning fby35-v2022.28.1: fw-util: bic_get_vr_device_id() Failed to get vr device id, ret=-1
 2022 Jul 31 19:21:10 bmc-oob. user.crit fby35-v2022.28.1: fw-util: Updating VCCIN/VCCFA_EHV_FIVRA on slot3. File: /tmp/ISL69260-1 0x60.hex
 2022 Jul 31 19:21:10 bmc-oob. user.warning fby35-v2022.28.1: fw-util: check_dev_rev: GEN3 unexpected IC_DEVICE_REV 00000005
 2022 Jul 31 19:21:10 bmc-oob. user.warning fby35-v2022.28.1: fw-util: vr_fw_update: update VR VCCIN/VCCFA_EHV_FIVRA failed
 2022 Jul 31 19:21:10 bmc-oob. user.crit fby35-v2022.28.1: fw-util: Updated VCCIN/VCCFA_EHV_FIVRA on slot3. File: /tmp/ISL69260-1 0x60.hex. Result: Fail
 2022 Jul 31 19:21:12 bmc-oob. authpriv.info fby35-v2022.28.1: -bash[23464]: HISTORY: PID=23464 UID=0 cat /var/log/messages | grep fw-util

after
 ---
root@bmc-oob:/tmp# fw-util slot3 --force --update vr_vccin  ISL69260-1\ 0x60.hex
Configuration GEN3 CRC (Legacy): C151AC43
Update VR: VCCIN/VCCFA_EHV_FIVRA
Remaining writes: 22
updated: 100 %
Force upgrade of slot3 : vr_vccin succeeded

Signed-off-by: jungle0220 <Ken.Chen@quantatw.com>

Reviewed By: williamspatrick

fbshipit-source-id: 5df8d79869f20e3ebda1674e80e0df93bd6bc308