common: prot-util: enhance and add more commands (#3412)
Summary:
1. enhance `status` command, and add following new commands
 - sendDataPacket: send raw data to PROT module
 - receiveDataPacket: receive data from PROT module
 - log: print logs from PROT module
2. add pal_get_prot_address() into libpal for getting PROT module I2C bus and address
3. add pal_get_prot_address() implementation for fby35 (halfdome)

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3412

Test Plan:
1. build passed on halfdome
2. tested on halfdome

- prot-util help message
```
root@bmc-oob:~# prot-util
ERROR: RequiredError: fru is required
PROT-Util
Usage: prot-util [OPTIONS] fru [SUBCOMMAND]

Positionals:
  fru TEXT:{slot1,slot2,slot3,slot4} REQUIRED

Options:
  -h,--help
  --verbose

Subcommands:
  sendDataPacket              Send Data Packet
  receiveDataPacket           Receive Data Packet
  status                      Status
  log                         Log
```

- sendDataPacket test results
```
root@bmc-oob:~# prot-util slot1 sendDataPacket 0x80
DataPacket.Command = 0x80
DataPacket.Length = 4
DataPacket.Flag = 0x04
DataPacket.PayLoad[0] = 0x78 = CheckSum

session_id = 16

PackageIndex:0, totalPackageCount:1, SendPacketThroughLinkLayer
LinkLayerPackage->Command = 0x10
LinkLayerPackage->AckNeeded = 0x01
LinkLayerPackage->PackageType = 0x00
LinkLayerPackage->Length = 0x06
LinkLayerPackage->LastPackageIndex = 0x01
LinkLayerPackage->SubPackageIndex = 0x00

Send LinkLayer SubPackage : 0
0x50 0x06 0x10 0x80 0x04 0x04 0x78 0x9A
sleep 100 ms
SendPacketThroughLinkLayer ret : 0
sleep 100 ms
Get command LinkLayer Ack
print link layer data:
LinkLayerPkgBuffer->SubPackageIndex = 0
0x20 0x90 0x10 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x40
verify session_id... successful
verify checksum... successful
```

- receiveDataPacket test results
```
root@bmc-oob:~# prot-util slot1 receiveDataPacket

--------------------------DataLayerReceive--------------------------
session_id = 16
sleep 200 ms
print link layer data:
LinkLayerPkgBuffer->SubPackageIndex = 0
0x20 0x10 0x10 0x05 0x80 0x03 0x00 0x78 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xC0
verify session_id... successful
verify checksum... successful
LinkLayerPkgBuffer->AckNeeded = 0...no need to sent ACK to platfire

RECEIVED DATA BUFFER
0x05 0x80 0x03 0x00 0x78
verify datalayer checksum... successful
```

- status test results
```
root@bmc-oob:~# prot-util slot1 status
Auth1 Module Present: true
Auth1 Module Mode: PFR
SPI_A Status: 0x00 (active)
SPI_A BIOS-Version: 0x00010000
SPI_B Status: 0x02 (dirty)
SPI_B BIOS-Version: 0x00010000
Verification-Status active: 0x00 (successful)
Verification-Status recovery: 0x01 (fail)
```

- status test results in json format
```
root@bmc-oob:~# prot-util slot1 status -j
{
    "Auth1": {
        "Module-Mode": "PFR",
        "Module-Present": true
    },
    "SPI_A": {
        "BIOS-Version": "0x00010000",
        "Status": "0x00 (active)"
    },
    "SPI_B": {
        "BIOS-Version": "0x00010000",
        "Status": "0x02 (dirty)"
    },
    "Verification-Status": {
        "active": "0x00 (successful)",
        "recovery": "0x01 (fail)"
    }
}
```

- log test results
```
root@bmc-oob:~# prot-util slot1 log

-------------------------- Result --------------------------
PROT Log Count - 120
LOG 0 : 0x0d 0x0e 0x1b 0x0a 0x01 0x00 0x00 0x00 0x00 0x00
    03:14:54  type:0x01 class:0x08 subclass:0x02 reserved:0x00 code:0x0001 parameter:0x00000000
    Log: BMC Commands, Is UPDATE_COMPLETE (0x81) Received

LOG 1 : 0x0d 0x0d 0xdc 0x35 0x01 0x00 0x00 0x00 0x00 0x00
    03:13:56  type:0x01 class:0x07 subclass:0x05 reserved:0x01 code:0x0001 parameter:0x00000000
    Log: Undefined log

LOG 2 : 0x0d 0x8d 0xd7 0x35 0x01 0x00 0x00 0x00 0x00 0x00
    03:13:47  type:0x01 class:0x07 subclass:0x05 reserved:0x01 code:0x0001 parameter:0x00000000
    Log: Undefined log

LOG 3 : 0x0d 0x8c 0x14 0x06 0x01 0x00 0x00 0x00 0x00 0x00
    03:12:41  type:0x01 class:0x08 subclass:0x01 reserved:0x00 code:0x0001 parameter:0x00000000
    Log: BMC Commands, Is RECOVERY_SPI_UNLOCK_REQUEST (0x80) Received

LOG 4 : 0x39 0x96 0x07 0x0a 0x01 0x00 0x00 0x00 0x00 0x00
    14:22:15  type:0x01 class:0x08 subclass:0x02 reserved:0x00 code:0x0001 parameter:0x00000000
    Log: BMC Commands, Is UPDATE_COMPLETE (0x81) Received

LOG 5 : 0x39 0x96 0xc4 0x35 0x01 0x00 0x00 0x00 0x00 0x00
    14:22:09  type:0x01 class:0x07 subclass:0x05 reserved:0x01 code:0x0001 parameter:0x00000000
    Log: Undefined log

...

LOG 115 : 0x01 0x80 0x80 0x0c 0x01 0x00 0x00 0x00 0x00 0x00
    00:00:01  type:0x01 class:0x02 subclass:0x03 reserved:0x00 code:0x0001 parameter:0x00000000
    Log: System Info, Current State, 0x0001

LOG 116 : 0x01 0x80 0x80 0x08 0x01 0x00 0x00 0x00 0x00 0x00
    00:00:01  type:0x01 class:0x02 subclass:0x02 reserved:0x00 code:0x0001 parameter:0x00000000
    Log: System Info, Current State, 0x0001

LOG 117 : 0x01 0x80 0x80 0x04 0x05 0x01 0x00 0x00 0x00 0x00
    00:00:01  type:0x01 class:0x02 subclass:0x01 reserved:0x00 code:0x0105 parameter:0x00000000
    Log: System Info, Active 0x05, Backup SVN 0x01

LOG 118 : 0x01 0x80 0xd9 0x19 0x01 0x00 0x00 0x00 0x00 0x00
    00:00:51  type:0x01 class:0x07 subclass:0x06 reserved:0x00 code:0x0001 parameter:0x00000000
    Log: Undefined log

LOG 119 : 0x01 0x80 0xd7 0x25 0x01 0x00 0x00 0x00 0x00 0x00
    00:00:47  type:0x01 class:0x07 subclass:0x01 reserved:0x01 code:0x0001 parameter:0x00000000
    Log: Undefined log
```

Reviewed By: zhdaniel12

Differential Revision: D42814626

fbshipit-source-id: f21dd46dbc06fa73b2367edb911a262a5c4147c7