common: snapshot-util: modify snapshot-util to use in different platform (#1475)
Summary:
1. Modify snapshot-util to use in different platform

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1475

Test Plan:
1. Built and test pass on GPv2 and Grand Canyon.

2. Check there are no unexpected error logs in BMC /var/log/messages and SELs.

3. Check snapshot-util is functional on GPv2 system.
(1) Usage
    root@bmc-oob:~# snapshot-util
    Error: invalid number of arguments
    Usage: snapshot-util [fru] --set <type> <reason_file>
           snapshot-util [fru] --set <type> "<inline reason string>"
           snapshot-util [fru] --get <type> <info_num> <dump_file>
           snapshot-util [fru] --get --all <dump_file>
           snapshot-util [fru] --clear <type> <info_num>

           [fru]: slot1, slot2, slot3, slot4
           <type>:
             --rma  RMA information
             --mfg  MFG failure information
           <info_num>: 1 ~ 3 for RMA information; 1 for MFG failure information

(2) Test on slot 1
    [Test clear]
    root@bmc-oob:~# snapshot-util slot1 --clear --mfg 1 571932
    Finished

    root@bmc-oob:~# snapshot-util slot1 --clear --rma 1 571932
    Finished

    root@bmc-oob:~# snapshot-util slot1 --clear --rma 2 571932
    Finished

    root@bmc-oob:~# snapshot-util slot1 --clear --rma 3 571932
    Finished

    [Create reason file for snapshot-util]
    root@bmc-oob:~# cat reason.txt
    slot 1 test

    [Set information to different regions]
    root@bmc-oob:~# snapshot-util slot1 --set --mfg reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 890
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot1 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 886
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot1 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 890
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot1 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 887
    Storing to EEPROM...
    Finished

    [Dump all snapshot files]
    root@bmc-oob:~# snapshot-util slot1 --get --all slot1
    Filename: slot1-rma1
    File Size: 886
    Dumping from EEPROM...
    Filename: slot1-rma2
    File Size: 890
    Dumping from EEPROM...
    Filename: slot1-rma3
    File Size: 887
    Dumping from EEPROM...
    Filename: slot1-mfg1
    File Size: 890
    Dumping from EEPROM...
    Finished

    root@bmc-oob:~# ls
    reason.txt  slot1-mfg1  slot1-rma1  slot1-rma2  slot1-rma3

    [Change the files extension to 'tgz' and unzip the files]
    root@bmc-oob:~# mv slot1-mfg1 slot1-mfg1.tgz
    root@bmc-oob:~# mkdir slot1-mfg1 && tar zxvf slot1-mfg1.tgz -C slot1-mfg1
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv slot1-rma1 slot1-rma1.tgz
    root@bmc-oob:~# mkdir slot1-rma1 && tar zxvf slot1-rma1.tgz -C slot1-rma1
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv slot1-rma2 slot1-rma2.tgz
    root@bmc-oob:~# mkdir slot1-rma2 && tar zxvf slot1-rma2.tgz -C slot1-rma2
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv slot1-rma3 slot1-rma3.tgz
    root@bmc-oob:~# mkdir slot1-rma3 && tar zxvf slot1-rma3.tgz -C slot1-rma3
    ./log.txt
    ./postcode.txt
    ./reason.txt

    [Check the snapshot files]
    (1) MFG failure information
    root@bmc-oob:~# cat slot1-mfg1/log.txt
    ...
    0    all      2021-02-18 18:44:32    gpiointrd        ASSERT: SLED is not seated
    5    spb      2021-02-18 18:44:36    front-paneld     Power Button Press for FRU: 5
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 13164.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 13252.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH
    5    spb      2021-02-18 18:45:06    front-paneld     Power Button Press for FRU: 5
    0    all      2021-02-18 18:45:14    gpiointrd        DEASSERT: SLED is seated
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x46 curr_val: 10885.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x47 curr_val: 10654.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH

    root@bmc-oob:~# cat slot1-mfg1/postcode.txt
    slot1 is not a server

    root@bmc-oob:~# cat slot1-mfg1/reason.txt
    slot 1 test

    (2) RMA information
    root@bmc-oob:~# cat slot1-rma2/log.txt
    ...
    0    all      2021-02-18 18:44:32    gpiointrd        ASSERT: SLED is not seated
    5    spb      2021-02-18 18:44:36    front-paneld     Power Button Press for FRU: 5
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 13164.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 13252.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH
    5    spb      2021-02-18 18:45:06    front-paneld     Power Button Press for FRU: 5
    0    all      2021-02-18 18:45:14    gpiointrd        DEASSERT: SLED is seated
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x46 curr_val: 10885.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x47 curr_val: 10654.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH

    root@bmc-oob:~# cat slot1-rma2/postcode.txt
    slot1 is not a server

    root@bmc-oob:~# cat slot1-rma2/reason.txt
    slot 1 test

    [Test command line reason]
    root@bmc-oob:~# snapshot-util slot1 --clear --rma 1 571932
    Finished
    root@bmc-oob:~# snapshot-util slot1 --clear --rma 2 571932
    Finished
    root@bmc-oob:~# snapshot-util slot1 --clear --rma 3 571932
    Finished

    root@bmc-oob:~# snapshot-util slot1 --set --rma "slot1 rma test"
    Reason file doesn't exist, assume stdin
    Getting logs...
    Getting POST codes...
    File Size: 902
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot1 --get --rma 1 rma
    Filename: rma
    File Size: 902
    Dumping from EEPROM...
    Finished

    root@bmc-oob:~# mv rma rma.tgz
    root@bmc-oob:~# mkdir rma && tar zxvf rma.tgz -C rma
    ./log.txt
    ./postcode.txt
    ./snapshot-reason-dft

    root@bmc-oob:~# cat rma/log.txt
    ...
    0    all      2021-02-18 18:44:32    gpiointrd        ASSERT: SLED is not seated
    5    spb      2021-02-18 18:44:36    front-paneld     Power Button Press for FRU: 5
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 13164.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 13252.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH
    5    spb      2021-02-18 18:45:06    front-paneld     Power Button Press for FRU: 5
    0    all      2021-02-18 18:45:14    gpiointrd        DEASSERT: SLED is seated
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x46 curr_val: 10885.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x47 curr_val: 10654.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH

    root@bmc-oob:~# cat rma/postcode.txt
    slot1 is not a server

    root@bmc-oob:~# cat rma/snapshot-reason-dft
    slot1 rma test

(3) Test on slot 2
    [Test clear]
    root@bmc-oob:~# snapshot-util slot2 --clear --mfg 1 571932
    Finished

    root@bmc-oob:~# snapshot-util slot2 --clear --rma 1 571932
    Finished

    root@bmc-oob:~# snapshot-util slot2 --clear --rma 2 571932
    Finished

    root@bmc-oob:~# snapshot-util slot2 --clear --rma 3 571932
    Finished

    [Create reason file for snapshot-util]

    root@bmc-oob:~# cat reason.txt
    slot 2 test

    [Set information to different regions]
    root@bmc-oob:~# snapshot-util slot2 --set --mfg reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 1083
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot2 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 1085
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot2 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 1084
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot2 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 1085
    Storing to EEPROM...
    Finished

    [Dump all snapshot files]
    root@bmc-oob:~# snapshot-util slot2 --get --all slot2
    Filename: slot2-rma1
    File Size: 1085
    Dumping from EEPROM...
    Filename: slot2-rma2
    File Size: 1084
    Dumping from EEPROM...
    Filename: slot2-rma3
    File Size: 1085
    Dumping from EEPROM...
    Filename: slot2-mfg1
    File Size: 1083
    Dumping from EEPROM...
    Finished

    root@bmc-oob:~# ls
    reason.txt  slot2-mfg1  slot2-rma1  slot2-rma2  slot2-rma3

    [Change the files extension to 'tgz' and unzip the files]
    root@bmc-oob:~# mv slot2-mfg1 slot2-mfg1.tgz
    root@bmc-oob:~# mkdir slot2-mfg1 && tar zxvf slot2-mfg1.tgz -C slot2-mfg1
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv slot2-rma1 slot2-rma1.tgz
    root@bmc-oob:~# mkdir slot2-rma1 && tar zxvf slot2-rma1.tgz -C slot2-rma1
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv slot2-rma2 slot2-rma2.tgz
    root@bmc-oob:~# mkdir slot2-rma2 && tar zxvf slot2-rma2.tgz -C slot2-rma2
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv slot2-rma3 slot2-rma3.tgz
    root@bmc-oob:~# mkdir slot2-rma3 && tar zxvf slot2-rma3.tgz -C slot2-rma3
    ./log.txt
    ./postcode.txt
    ./reason.txt

    [Check the snapshot files]
    (1) MFG failure information
    root@bmc-oob:~# cat slot2-mfg1/log.txt
    ...
    0    all      2021-02-18 18:44:32    gpiointrd        ASSERT: SLED is not seated
    5    spb      2021-02-18 18:44:36    front-paneld     Power Button Press for FRU: 5
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 13164.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 13252.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH
    5    spb      2021-02-18 18:45:06    front-paneld     Power Button Press for FRU: 5
    0    all      2021-02-18 18:45:14    gpiointrd        DEASSERT: SLED is seated
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x46 curr_val: 10885.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x47 curr_val: 10654.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH

    root@bmc-oob:~# cat slot2-mfg1/postcode.txt
    00 00 00 00 E3 E3 E3 AA 84 A0 B1 78 AD D9 78 AD
    D9 78 AD 92 92 92 99 92 9C 9D 98 97 92 92 92 92
    D5 91 99 92 92 92 EF 96 95 94 94 94 94 94 93 94
    93 94 93 94 93 94 93 94 93 94 93 94 93 94 93 94
    93 94 93 94 93 94 93 94 93 94 93 94 93 94 93 94
    93 94 93 92 91 D4 D3 D2 D1 D0 79 70 68 78 9A 61
    4F EE ED EC EB E9 E8 E7 E6 BF BC B7 BB B9 BA B9
    B9 B9 B9 B9 B8 B7 BE B7 B7 B7 B7 B7 B7 B7 B7 B7
    B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7
    B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B6 B7
    B6 B7 B7 B6 B6 B6 B6 B3 B3 B3 B3 B2 B4 B1 B0 B0
    E5 E3 E4 E1 E0 AF AE AA A9 A9 A8 A7 A7 A7 A9 A7
    A3 A3 A1 19 06 05 04 03 02 01

    root@bmc-oob:~# cat slot2-mfg1/reason.txt
    slot 2 test

    (2) RMA information
    ...
    0    all      2021-02-18 18:44:32    gpiointrd        ASSERT: SLED is not seated
    5    spb      2021-02-18 18:44:36    front-paneld     Power Button Press for FRU: 5
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 13164.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 13252.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH
    5    spb      2021-02-18 18:45:06    front-paneld     Power Button Press for FRU: 5
    0    all      2021-02-18 18:45:14    gpiointrd        DEASSERT: SLED is seated
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x46 curr_val: 10885.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x47 curr_val: 10654.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH

    root@bmc-oob:~# cat slot2-rma2/postcode.txt
    00 00 00 00 E3 E3 E3 AA 84 A0 B1 78 AD D9 78 AD
    D9 78 AD 92 92 92 99 92 9C 9D 98 97 92 92 92 92
    D5 91 99 92 92 92 EF 96 95 94 94 94 94 94 93 94
    93 94 93 94 93 94 93 94 93 94 93 94 93 94 93 94
    93 94 93 94 93 94 93 94 93 94 93 94 93 94 93 94
    93 94 93 92 91 D4 D3 D2 D1 D0 79 70 68 78 9A 61
    4F EE ED EC EB E9 E8 E7 E6 BF BC B7 BB B9 BA B9
    B9 B9 B9 B9 B8 B7 BE B7 B7 B7 B7 B7 B7 B7 B7 B7
    B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7
    B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B6 B7
    B6 B7 B7 B6 B6 B6 B6 B3 B3 B3 B3 B2 B4 B1 B0 B0
    E5 E3 E4 E1 E0 AF AE AA A9 A9 A8 A7 A7 A7 A9 A7
    A3 A3 A1 19 06 05 04 03 02 01

    root@bmc-oob:~# cat slot2-rma2/reason.txt
    slot 2 test

    [Test command line reason]
    root@bmc-oob:~# snapshot-util slot2 --clear --rma 1 571932
    Finished
    root@bmc-oob:~# snapshot-util slot2 --clear --rma 2 571932
    Finished
    root@bmc-oob:~# snapshot-util slot2 --clear --rma 3 571932
    Finished

    root@bmc-oob:~# snapshot-util slot2 --set --rma "slot2 rma test"
    Reason file doesn't exist, assume stdin
    Getting logs...
    Getting POST codes...
    File Size: 1095
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util slot2 --get --rma 1 rma
    Filename: rma
    File Size: 1095
    Dumping from EEPROM...
    Finished

    root@bmc-oob:~# mv rma rma.tgz
    root@bmc-oob:~# mkdir rma && tar zxvf rma.tgz -C rma
    ./log.txt
    ./postcode.txt
    ./snapshot-reason-dft

    root@bmc-oob:~# cat rma/log.txt
    ...
    0    all      2021-02-18 18:44:32    gpiointrd        ASSERT: SLED is not seated
    5    spb      2021-02-18 18:44:36    front-paneld     Power Button Press for FRU: 5
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 13164.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:44:46    sensord          ASSERT: Upper Non Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 13252.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH
    5    spb      2021-02-18 18:45:06    front-paneld     Power Button Press for FRU: 5
    0    all      2021-02-18 18:45:14    gpiointrd        DEASSERT: SLED is seated
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x46 curr_val: 10885.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN0_TACH
    5    spb      2021-02-18 18:45:19    sensord          DEASSERT: Upper Non Critical threshold - settled - FRU: 5, num: 0x47 curr_val: 10654.00 RPM, thresh_val: 13000.00 RPM, snr: SP_FAN1_TACH

    root@bmc-oob:~# cat rma/postcode.txt
    00 00 00 00 E3 E3 E3 AA 84 A0 B1 78 AD D9 78 AD
    D9 78 AD 92 92 92 99 92 9C 9D 98 97 92 92 92 92
    D5 91 99 92 92 92 EF 96 95 94 94 94 94 94 93 94
    93 94 93 94 93 94 93 94 93 94 93 94 93 94 93 94
    93 94 93 94 93 94 93 94 93 94 93 94 93 94 93 94
    93 94 93 92 91 D4 D3 D2 D1 D0 79 70 68 78 9A 61
    4F EE ED EC EB E9 E8 E7 E6 BF BC B7 BB B9 BA B9
    B9 B9 B9 B9 B8 B7 BE B7 B7 B7 B7 B7 B7 B7 B7 B7
    B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7
    B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B7 B6 B7
    B6 B7 B7 B6 B6 B6 B6 B3 B3 B3 B3 B2 B4 B1 B0 B0
    E5 E3 E4 E1 E0 AF AE AA A9 A9 A8 A7 A7 A7 A9 A7
    A3 A3 A1 19 06 05 04 03 02 01

    root@bmc-oob:~# cat rma/snapshot-reason-dft
    slot2 rma test

Reviewed By: benwei13

fbshipit-source-id: 85678b4de2