power-util: update error message
Summary:
When power-util fails (not due to command line erorr),
it prints usage string, which can be confusing to user,
e.g.
root@rtptest12467-oob:~# power-util slot3 on
Powering fru 3 to ON state...
Usage: power-util [ slot1, slot2, slot3, slot4 ] [ status, graceful-shutdown, off, on, reset, cycle, 12V-off, 12V-on, 12V-cycle ]
Usage: power-util sled-cycle

This diff updates error-exit path print message
e.g.
root@bmc-oob:/tmp# power-util slot3 on
Powering fru 3 to ON state...
ERROR: power-util fru[3] [PWR_ON] failed

Test Plan: verified on YosemiteV2 DVT system

Reviewed By: amithash

fbshipit-source-id: 71a2381