fuji: image bb file update (#452)
Summary:
update the image bb file for ipmbd, ipmid, ipmitool, bic-util,bic-cache,bic-mond,log-util,flashrom,fw-util,gpiod,,psu-util etc.

Pull Request resolved: https://github.com/facebookexternal/openbmc.celestica/pull/452

Test Plan:
1. bic-cache
root@cshan0166:~# hexdump -C /tmp/sdr_scm.bin
00000000  00 00 51 01 39 40 00 01  07 01 77 48 01 01 00 02  |..Q.9@....wH....|
00000010  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
00000020  00 00 ff 00 00 5d 00 00  00 00 00 00 00 00 00 ce  |.....]..........|
00000030  4d 42 20 4f 75 74 6c 65  74 20 54 65 6d 70 00 00  |MB Outlet Temp..|
00000040  01 00 51 01 39 40 00 07  37 01 77 48 01 01 00 02  |..Q.9@..7.wH....|
00000050  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
00000060  00 00 ff 00 00 5d 00 00  00 00 00 00 00 00 00 cd  |.....]..........|
00000070  4d 42 20 49 6e 6c 65 74  20 54 65 6d 70 00 00 00  |MB Inlet Temp...|
00000080  02 00 51 01 33 40 00 08  07 01 77 48 01 01 00 02  |..Q.3@....wH....|
00000090  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
000000a0  00 00 ff 00 00 5d 00 00  00 00 00 00 00 00 00 c8  |.....]..........|
000000b0  50 43 48 20 54 65 6d 70  20 54 65 6d 70 00 00 00  |PCH Temp Temp...|
000000c0  03 00 51 01 33 40 00 05  41 01 77 48 01 01 00 02  |..Q.3@..A.wH....|
000000d0  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
000000e0  00 00 ff 00 00 62 00 00  00 00 00 00 00 00 00 c8  |.....b..........|
000000f0  53 4f 43 20 54 65 6d 70  20 54 65 6d 70 00 00 00  |SOC Temp Temp...|
00000100  04 00 51 01 3b 40 00 09  03 01 45 43 01 01 00 00  |..Q.;@....EC....|
00000110  00 00 00 00 80 01 00 00  01 00 00 00 00 00 00 f1  |................|
00000120  00 00 ff 00 00 00 00 00  00 00 00 00 00 00 00 d0  |................|
00000130  53 4f 43 20 54 68 65 72  6d 20 4d 61 72 67 69 6e  |SOC Therm Margin|
00000140  05 00 51 01 34 40 00 30  03 01 45 43 01 01 00 00  |..Q.4@.0..EC....|
00000150  00 00 00 00 00 01 00 00  01 00 00 00 00 00 00 f1  |................|
00000160  00 00 ff 00 00 00 00 00  00 00 00 00 00 00 00 c9  |................|
00000170  53 4f 43 20 54 6a 6d 61  78 20 4d 61 72 67 69 6e  |SOC Tjmax Margin|
00000180  06 00 51 01 3a 40 00 b4  20 01 77 48 01 01 00 02  |..Q.:@.. .wH....|
00000190  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
000001a0  00 00 ff 00 00 55 00 00  00 00 00 00 00 00 00 cf  |.....U..........|
000001b0  53 4f 43 20 44 49 4d 4d  41 30 20 54 65 6d 70 6e  |SOC DIMMA0 Tempn|
000001c0  07 00 51 01 3a 40 00 b6  20 03 77 48 01 01 00 02  |..Q.:@.. .wH....|
000001d0  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
000001e0  00 00 ff 00 00 55 00 00  00 00 00 00 00 00 00 cf  |.....U..........|
000001f0  53 4f 43 20 44 49 4d 4d  42 30 20 54 65 6d 70 6e  |SOC DIMMB0 Tempn|
00000200  08 00 51 01 3b 40 00 81  07 01 77 48 01 01 00 02  |..Q.;@....wH....|
00000210  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
00000220  00 00 ff 00 00 73 00 00  00 00 00 00 00 00 00 d0  |.....s..........|
00000230  31 56 30 35 43 4f 4d 42  20 56 52 20 54 65 6d 70  |1V05COMB VR Temp|
00000240  09 00 51 01 37 40 00 82  07 01 77 48 01 01 00 02  |..Q.7@....wH....|
00000250  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
00000260  00 00 ff 00 00 73 00 00  00 00 00 00 00 00 00 cc  |.....s..........|
00000270  56 44 44 52 20 56 52 20  54 65 6d 70 54 65 6d 70  |VDDR VR TempTemp|
00000280  0a 00 51 01 38 40 00 80  07 01 77 48 01 01 00 02  |..Q.8@....wH....|
00000290  00 22 10 10 80 01 00 00  01 00 00 00 00 00 00 23  |.".............#|
000002a0  00 00 ff 00 00 73 00 00  00 00 00 00 00 00 00 cd  |.....s..........|
000002b0  56 43 43 49 4e 20 56 52  20 54 65 6d 70 65 6d 70  |VCCIN VR Tempemp|
000002c0  0b 00 51 01 3b 40 00 84  07 01 77 48 03 01 00 02  |..Q.;@....wH....|
000002d0  00 22 10 10 00 05 00 00  7d 00 00 00 00 d0 00 23  |."......}......#|
000002e0  00 00 ff 00 00 80 00 00  00 00 00 00 00 00 00 d0  |................|
000002f0  31 56 30 35 43 4f 4d 42  20 56 52 20 43 75 72 72  |1V05COMB VR Curr|
00000300  0c 00 51 01 37 40 00 85  07 01 77 48 03 01 00 02  |..Q.7@....wH....|
00000310  00 22 10 10 00 05 00 00  7d 00 00 00 00 d0 00 23  |."......}......#|
00000320  00 00 ff 00 00 48 00 00  00 00 00 00 00 00 00 cc  |.....H..........|
00000330  56 44 44 52 20 56 52 20  43 75 72 72 43 75 72 72  |VDDR VR CurrCurr|
00000340  0d 00 51 01 38 40 00 83  07 01 77 48 03 01 00 02  |..Q.8@....wH....|
00000350  00 22 10 10 00 05 00 00  05 00 00 00 00 f0 00 23  |.".............#|
00000360  00 00 ff 00 00 8c 00 00  00 00 00 00 00 00 00 cd  |................|
00000370  56 43 43 49 4e 20 56 52  20 43 75 72 72 75 72 72  |VCCIN VR Currurr|
00000380  0e 00 51 01 3a 40 00 89  07 01 77 48 02 01 04 22  |..Q.:@....wH..."|
00000390  04 22 12 12 00 04 00 00  01 00 00 00 00 e0 00 23  |.".............#|
000003a0  00 00 ff 00 00 72 00 00  5e 00 00 00 00 00 00 cf  |.....r..^.......|
000003b0  31 56 30 35 43 4f 4d 42  20 56 52 20 56 6f 6c 72  |1V05COMB VR Volr|
000003c0  0f 00 51 01 36 40 00 8a  07 01 77 48 02 01 04 22  |..Q.6@....wH..."|
000003d0  04 22 12 12 00 04 00 00  01 00 00 00 00 e0 00 23  |.".............#|
000003e0  00 00 ff 00 00 9b 00 00  3e 00 00 00 00 00 00 cb  |........>.......|
000003f0  56 44 44 52 20 56 52 20  56 6f 6c 20 56 6f 6c 72  |VDDR VR Vol Volr|
00000400  10 00 51 01 37 40 00 88  07 01 77 48 02 01 04 22  |..Q.7@....wH..."|
00000410  04 22 12 12 00 04 00 00  01 00 00 00 00 e0 00 23  |.".............#|
00000420  00 00 ff 00 00 d2 00 00  82 00 00 00 00 00 00 cc  |................|
00000430  56 43 43 49 4e 20 56 52  20 56 6f 6c 56 6f 6c 72  |VCCIN VR VolVolr|
00000440  11 00 51 01 3b 40 00 8c  07 01 77 48 0b 01 00 02  |..Q.;@....wH....|
00000450  00 22 10 10 00 06 00 00  7d 00 00 00 00 d0 00 23  |."......}......#|
00000460  00 00 ff 00 00 97 00 00  00 00 00 00 00 00 00 d0  |................|
00000470  31 56 30 35 43 4f 4d 42  20 56 52 20 50 6f 75 74  |1V05COMB VR Pout|
00000480  12 00 51 01 37 40 00 8d  07 01 77 48 0b 01 00 02  |..Q.7@....wH....|
00000490  00 22 10 10 00 06 00 00  19 00 00 00 00 e0 00 23  |.".............#|
000004a0  00 00 ff 00 00 30 00 00  00 00 00 00 00 00 00 cc  |.....0..........|
000004b0  56 44 44 52 20 56 52 20  50 6f 75 74 50 6f 75 74  |VDDR VR PoutPout|
000004c0  13 00 51 01 38 40 00 8b  07 01 77 48 0b 01 00 02  |..Q.8@....wH....|
000004d0  00 22 10 10 00 06 00 00  01 00 00 00 00 00 00 23  |.".............#|
000004e0  00 00 ff 00 00 78 00 00  00 00 00 00 00 00 00 cd  |.....x..........|
000004f0  56 43 43 49 4e 20 56 52  20 50 6f 75 74 6f 75 74  |VCCIN VR Poutout|
00000500  14 00 51 01 32 40 00 d0  07 01 77 48 02 01 04 22  |..Q.2@....wH..."|
00000510  04 22 12 12 00 04 00 00  d1 00 00 00 00 c0 00 a7  |."..............|
00000520  b4 a5 ff 00 00 ae 00 00  8e 00 00 00 00 00 00 c7  |................|
00000530  50 33 56 33 5f 4d 42 52  20 50 6f 75 74 6f 75 74  |P3V3_MBR Poutout|
00000540  15 00 51 01 37 40 00 d5  07 01 77 48 02 01 04 22  |..Q.7@....wH..."|
00000550  04 22 12 12 00 04 00 00  d1 00 00 00 00 c0 00 a7  |."..............|
00000560  b4 a5 ff 00 00 ae 00 00  8e 00 00 00 00 00 00 cc  |................|
00000570  50 33 56 33 5f 53 54 42  59 5f 4d 42 74 6f 75 74  |P3V3_STBY_MBtout|
00000580  16 00 51 01 31 40 00 d7  07 01 77 48 02 01 04 22  |..Q.1@....wH..."|
00000590  04 22 12 12 00 04 00 00  27 00 00 00 00 d0 00 6d  |."......'......m|
000005a0  75 5d ff 00 00 5d 00 00  45 00 00 00 00 00 00 c6  |u]...]..E.......|
000005b0  50 56 5f 42 41 54 54 42  59 5f 4d 42 74 6f 75 74  |PV_BATTBY_MBtout|
000005c0  17 00 51 01 35 40 00 8e  07 01 77 48 02 01 04 22  |..Q.5@....wH..."|
000005d0  04 22 12 12 00 04 00 00  82 00 00 00 00 c0 00 88  |."..............|
000005e0  90 85 ff 00 00 58 00 00  48 00 00 00 00 00 00 ca  |.....X..H.......|
000005f0  50 31 56 30 35 5f 43 4f  4d 42 4d 42 74 6f 75 74  |P1V05_COMBMBtout|
00000600  18 00 51 01 34 40 00 d3  07 01 77 48 02 01 04 22  |..Q.4@....wH..."|
00000610  04 22 12 12 00 04 00 00  82 00 00 00 00 c0 00 88  |."..............|
00000620  90 85 ff 00 00 58 00 00  48 00 00 00 00 00 00 c9  |.....X..H.......|
00000630  50 31 56 30 35 5f 50 43  48 42 4d 42 74 6f 75 74  |P1V05_PCHBMBtout|
00000640  19 00 51 01 32 40 00 d2  07 01 77 48 02 01 04 22  |..Q.2@....wH..."|
00000650  04 22 12 12 00 04 00 00  4e 00 00 00 00 d0 00 bb  |."......N.......|
00000660  ca 98 ff 00 00 a9 00 00  8b 00 00 00 00 00 00 c7  |................|
00000670  50 31 32 56 5f 4d 42 43  48 42 4d 42 74 6f 75 74  |P12V_MBCHBMBtout|
00000680  1a 00 51 01 36 40 00 d6  07 01 77 48 02 01 04 22  |..Q.6@....wH..."|
00000690  04 22 12 12 00 04 00 00  20 00 00 00 00 d0 00 bb  |."...... .......|
000006a0  ca 98 ff 00 00 ac 00 00  8e 00 00 00 00 00 00 cb  |................|
000006b0  50 35 56 5f 53 54 42 59  5f 4d 42 42 74 6f 75 74  |P5V_STBY_MBBtout|
000006c0  1b 00 51 01 30 40 00 d8  07 01 77 48 02 01 04 22  |..Q.0@....wH..."|
000006d0  04 22 12 12 00 04 00 00  83 00 00 00 00 c0 00 bb  |."..............|
000006e0  ca 98 ff 00 00 65 00 00  52 00 00 00 00 00 00 c5  |.....e..R.......|
000006f0  50 56 44 44 52 54 42 59  5f 4d 42 42 74 6f 75 74  |PVDDRTBY_MBBtout|
00000700  1c 00 51 01 32 40 00 d9  07 01 77 48 02 01 04 22  |..Q.2@....wH..."|
00000710  04 22 12 12 00 04 00 00  81 00 00 00 00 c0 00 bb  |."..............|
00000720  ca 98 ff 00 00 5b 00 00  4a 00 00 00 00 00 00 c7  |.....[..J.......|
00000730  50 56 43 43 47 42 45 59  5f 4d 42 42 74 6f 75 74  |PVCCGBEY_MBBtout|
00000740  1d 00 51 01 3a 40 00 2c  03 01 45 43 0b 01 00 00  |..Q.:@.,..EC....|
00000750  00 00 00 00 00 06 00 00  01 00 00 00 00 00 00 64  |...............d|
00000760  ca 01 ff 00 00 00 00 00  00 00 00 00 00 00 00 cf  |................|
00000770  53 4f 43 20 50 61 63 6b  61 67 65 20 50 77 72 74  |SOC Package Pwrt|
00000780  1e 00 51 01 37 40 00 29  07 01 77 48 0b 01 00 02  |..Q.7@.)..wH....|
00000790  00 22 10 10 00 06 00 00  01 00 00 00 00 00 00 20  |."............. |
000007a0  5c 01 ff 00 00 3c 00 00  00 00 00 00 00 00 00 cc  |\....<..........|
000007b0  49 4e 41 32 33 30 20 50  6f 77 65 72 50 77 72 74  |INA230 PowerPwrt|
000007c0  1f 00 51 01 39 40 00 2a  07 01 77 48 02 01 04 22  |..Q.9@.*..wH..."|
000007d0  04 22 12 12 00 04 00 00  4f 00 00 00 00 d0 00 bb  |."......O.......|
000007e0  ca 98 ff 00 00 a8 00 00  88 00 00 00 00 00 00 ce  |................|
000007f0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000800  20 00 51 02 28 40 00 10  07 01 62 40 c9 6f 07 00  | .Q.(@....b@.o..|
00000810  07 00 07 00 c0 00 00 01  00 00 00 00 00 00 00 cd  |................|
00000820  53 79 73 74 65 6d 20 53  74 61 74 75 73 00 00 ce  |System Status...|
00000830  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000840  21 00 51 02 29 40 00 65  03 01 62 40 07 6f 10 00  |!.Q.)@.e..b@.o..|
00000850  00 00 10 00 c0 00 00 01  00 00 00 00 00 00 00 ce  |................|
00000860  50 72 6f 63 65 73 73 6f  72 20 46 61 69 6c 00 ce  |Processor Fail..|
00000870  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000880  22 00 51 02 27 40 00 b3  07 01 62 40 c7 6f 03 00  |".Q.'@....b@.o..|
00000890  03 00 03 00 c0 00 00 01  00 00 00 00 00 00 00 cc  |................|
000008a0  43 50 55 5f 44 49 4d 4d  20 48 4f 54 69 6c 00 ce  |CPU_DIMM HOTil..|
000008b0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
000008c0  23 00 51 02 21 40 00 b2  07 01 62 40 c6 6f 03 00  |#.Q.!@....b@.o..|
000008d0  03 00 03 00 c0 00 00 01  00 00 00 00 00 00 00 c6  |................|
000008e0  56 52 20 48 4f 54 4d 4d  20 48 4f 54 69 6c 00 ce  |VR HOTMM HOTil..|
000008f0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000900  24 00 51 02 2a 40 00 7e  07 01 62 40 ca 6f 3f 00  |$.Q.*@.~..b@.o?.|
00000910  3f 00 3f 00 c0 00 00 01  00 00 00 00 00 00 00 cf  |?.?.............|
00000920  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000930  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000940  25 00 51 03 12 40 00 eb  03 01 07 6f 01 00 00 00  |%.Q..@.....o....|
00000950  c6 43 41 54 45 52 52 01  00 00 00 00 00 00 00 cf  |.CATERR.........|
00000960  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000970  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000980  26 00 51 03 1a 2c 00 3b  13 00 09 05 01 00 00 00  |&.Q..,.;........|
00000990  ce 50 77 72 20 54 68 72  65 73 68 20 45 76 74 cf  |.Pwr Thresh Evt.|
000009a0  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
000009b0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
000009c0  27 00 51 03 14 01 00 2b  22 01 0f 6f 01 00 00 00  |'.Q....+"..o....|
000009d0  c8 50 4f 53 54 20 45 72  72 73 68 20 45 76 74 cf  |.POST Errsh Evt.|
000009e0  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
000009f0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000a00  28 00 51 03 17 40 00 56  07 01 c3 6f 01 00 00 00  |(.Q..@.V...o....|
00000a10  cb 50 6f 77 65 72 20 45  72 72 6f 72 45 76 74 cf  |.Power ErrorEvt.|
00000a20  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000a30  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000a40  29 00 51 03 17 40 00 51  03 01 07 6f 01 00 00 00  |).Q..@.Q...o....|
00000a50  cb 50 72 6f 63 48 6f 74  20 45 78 74 45 76 74 cf  |.ProcHot ExtEvt.|
00000a60  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000a70  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000a80  2a 00 51 03 1b 01 00 40  34 01 07 6f 01 00 00 00  |*.Q....@4..o....|
00000a90  cf 4d 61 63 68 69 6e 65  20 43 68 6b 20 45 72 72  |.Machine Chk Err|
00000aa0  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000ab0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000ac0  2b 00 51 03 14 01 00 41  31 01 13 6f 01 00 00 00  |+.Q....A1..o....|
00000ad0  c8 50 43 49 65 20 45 72  72 43 68 6b 20 45 72 72  |.PCIe ErrChk Err|
00000ae0  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000af0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000b00  2c 00 51 03 19 01 00 43  2d 01 13 70 01 00 00 00  |,.Q....C-..p....|
00000b10  cd 4f 74 68 65 72 20 49  49 4f 20 45 72 72 72 72  |.Other IIO Errrr|
00000b20  53 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |Sys booting sts.|
00000b30  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000b40  2d 00 51 03 1c 01 00 63  20 01 0c 6f 01 00 00 00  |-.Q....c ..o....|
00000b50  d0 4d 65 6d 6f 72 79 20  45 43 43 20 45 72 72 6f  |.Memory ECC Erro|
00000b60  72 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |rys booting sts.|
00000b70  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000b80  2e 00 51 03 19 2c 60 17  2e 00 dc 75 01 00 00 00  |..Q..,`....u....|
00000b90  cd 53 50 53 20 46 57 20  48 65 61 6c 74 68 72 6f  |.SPS FW Healthro|
00000ba0  72 79 73 20 62 6f 6f 74  69 6e 67 20 73 74 73 ce  |rys booting sts.|
00000bb0  49 4e 41 32 33 30 20 56  6f 6c 74 61 67 65 72 74  |INA230 Voltagert|
00000bc0
root@cshan0166:~#

2.bic-util
root@cshan0166:~# bic-util
Usage: bic-util <scm> <[0..n]data_bytes_to_send>
Usage: bic-util <scm> <--me> <[0..n]data_bytes_to_send>
Usage: bic-util <scm> <--me_file> <path>
Usage: bic-util <scm> <option>
       option:
       --get_dev_id
       --get_gpio
       --get_gpio_config
       --get_config
       --get_post_code
       --get_sdr
       --read_sensor
       --read_fruid
       --read_mac
root@cshan0166:~# bic-util scm --get_dev_id
Device ID: 0x25
Device Revision: 0x80
Firmware Revision: 0x1:0x11
IPMI Version: 0x2
Device Support: 0xBF
Manufacturer ID: 0x0:0x1C:0x4C
Product ID: 0x46:0x20
Aux. FW Rev: 0x0:0x0:0x0:0x0

3.psu-util
root@cshan0166:~# psu-util
Usage: psu-util <psu1|psu2|psu3|psu4> --update <file_path>
Usage: psu-util <psu1|psu2|psu3|psu4> <command> <options>
       command:
         --get_psu_info
         --get_eeprom_info
         --get_blackbox_info
           options:
             --print
             --clear
root@cshan0166:~# psu-util psu1 --get_psu_info

PSU Information           : PSU1 (Bus:48 Addr:0x58)
---------------           : -----------------------
MFR_ID             (0x99) : Delta
MFR_MODEL          (0x9A) : ECD55020006
MFR_REVISION       (0x9B) : 00
MFR_DATE           (0x9D) : 20190606
MFR_SERIAL         (0x9E) : THAF1192300B2
PRI_FW_VER         (0xDD) : 4.0
SEC_FW_VER         (0xD7) : 3.0
STATUS_WORD        (0x79) : 0x0
STATUS_VOUT        (0x7A) : 0x0
STATUS_IOUT        (0x7B) : 0x0
STATUS_INPUT       (0x7C) : 0x0
STATUS_TEMP        (0x7D) : 0x0
STATUS_CML         (0x7E) : 0x0
STATUS_FAN         (0x81) : 0x0
STATUS_STBY_WORD   (0xD3) : 0x0
STATUS_VSTBY       (0xD4) : 0x0
STATUS_ISTBY       (0xD5) : 0x0
OPTN_TIME_TOTAL    (0xD8) : 91D:12H:21M:10S
OPTN_TIME_PRESENT  (0xD9) : 0D:0H:7M:20S

4.fw-util
root@cshan0166:~# fw-util all --version
BMC Version: fuji-eedce0b-dirty
Fan Speed Controller Version: NA
TPM Version: 7.85
FCMCPLD B: 0.3.0
FCMCPLD T: 0.3.0
PWRCPLD L: 0.5.0
PWRCPLD R: 0.5.0
SCMCPLD: 0.5.0
SMBCPLD: 1.0.0
PIM1 DOMFPGA: NA
PIM2 DOMFPGA: NA
PIM3 DOMFPGA: NA
PIM4 DOMFPGA: NA
PIM5 DOMFPGA: NA
PIM6 DOMFPGA: NA
PIM7 DOMFPGA: NA
PIM8 DOMFPGA: 0.18
Bridge-IC Version: v1.11
Bridge-IC Bootloader Version: v1.10
BIOS Version: XG1_3A09
CPLD Version: 0x00010032
ME Version: 3.0.3.45
PVCCIN VR Version: 0x54c8, 0xe9d6
DDRAB VR Version: 0xb41b, 0xe66c
P1V05 VR Version: 0x54c8, 0xe9d6

6.ipmid
root@cshan0166:~# ps w|grep ipmi
  704 root      2104 S    runsv /etc/sv/ipmid
  709 root     15876 S    /usr/local/bin/ipmid
 9721 root      2236 S    grep ipmi
root@cshan0166:~# ps w|grep ipmb
  707 root      2104 S    runsv /etc/sv/ipmbd_0
  708 root      2104 S    runsv /etc/sv/ipmbd_4
  711 root     41284 S    /usr/local/bin/ipmbd 4 1
  712 root     41392 S    /usr/local/bin/ipmbd 0 1
 9804 root      2236 S    grep ipmb

7.bicmond
root@cshan0166:~# ps w|grep bic
  787 root      2104 S    runsv /etc/sv/bicmond
  829 root      5352 S    /usr/local/bin/bicmond
10956 root      2236 S    grep bic

8.log-util
root@cshan0166:~# log-util
ERROR: RequiredError: fru is required
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,pim1,pim2,pim3,pim4,pim5,pim6,pim7,pim8,psu1,psu2,psu3,psu4,scm,smb,sys} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU

9.flashrom
root@cshan0166:~# flashrom
flashrom v1.0 on Linux 5.6.14-fuji (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Please select a programmer with the --programmer parameter.
Previously this was not necessary because there was a default set.
To choose the mainboard of this computer use 'internal'. Valid choices are:
internal, dummy, gfxnvidia, drkaiser, satasii, atavia, it8212, serprog,
buspirate_spi, dediprog, pony_spi, nicintel, nicintel_spi, nicintel_eeprom,
ogp_spi, linux_spi, pickit2_spi, ch341a_spi.

10. threshold-util
root@cshan0166:~# threshold-util
Usage: threshold-util [fru] <--set> <snr_num> [thresh_type] <threshold_value>
       threshold-util [fru] <--clear>
       [fru]           : all, scm, smb, pim1, pim2, pim3, pim4, pim5, pim6, pim7, pim8, psu1, psu2, psu3, psu4
       <snr_num>    : 0xXX
       [thresh_type]   : UCR, UNC, UNR, LCR, LNC, LNR

11. spatula
root@cshan0166:~# ps w | grep spatula
  851 root     16228 S    python3 /usr/local/bin/spatula_wrapper.py
21966 root      2236 S    grep spatula

Pass.

Reviewed By: benwei13

fbshipit-source-id: d0dbe4973d