cloudripper: cit-test: delete one sensor in test_sensor (#894)
Summary:
delete one sensor in test_sensor

Pull Request resolved: https://github.com/facebookexternal/openbmc.celestica/pull/894

Test Plan:
```
Before:
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py  --run-test tests.cloudripper.test_sensor.ScmSensorTest
test_scm_sensor_keys (tests.cloudripper.test_sensor.ScmSensorTest) ... test_scm_temp_sensor_range (tests.cloudripper.test_sensor.ScmSensorTest) ... ok

======================================================================
FAIL: test_scm_sensor_keys (tests.cloudripper.test_sensor.ScmSensorTest) (key='SCM_HSC_INPUT_12V_VOLT')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/cloudripper/test_sensor.py", line 41, in test_scm_sensor_keys
    key, result.keys(), "Missing key {} in scm sensor data".format(key)
AssertionError: 'SCM_HSC_INPUT_12V_VOLT' not found in dict_keys(['present', 'SCM_OUTLET_TEMP', 'SCM_INLET_TEMP', 'SCM_HSC_OUTPUT_12V_VOLT', 'SCM_HSC_OUTPUT_12V_CURR', 'MB_OUTLET_TEMP', 'MB_INLET_TEMP', 'PCH_TEMP', 'VCCIN_VR_TEMP', '1V05COMB_VR_TEMP', 'SOC_TEMP', 'SOC_THERM_MARGIN_TEMP', 'VDDR_VR_TEMP', 'SOC_DIMMA_TEMP', 'SOC_DIMMB_TEMP', 'SOC_PACKAGE_POWER', 'VCCIN_VR_OUT_POWER', 'VDDR_VR_OUT_POWER', 'SOC_TJMAX_TEMP', 'P3V3_MB_VOLT', 'P12V_MB_VOLT', 'P1V05_PCH_VOLT', 'P3V3_STBY_MB_VOLT', 'P5V_STBY_MB_VOLT', 'PV_BAT_VOLT', 'PVDDR_VOLT', 'P1V05_COMB_VOLT', '1V05COMB_VR_CURR', 'VDDR_VR_CURR', 'VCCIN_VR_CURR', 'VCCIN_VR_VOLT', 'VDDR_VR_VOLT', '1V05COMB_VR_VOLT', '1V05COMB_VR_OUT_POWER', 'INA230_POWER', 'INA230_VOLT']) : Missing key SCM_HSC_INPUT_12V_VOLT in scm sensor data
----------------------------------------------------------------------
Ran 2 tests in 0.224s
FAILED (failures=1)

After:
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py  --run-test tests.cloudripper.test_sensor.ScmSensorTest
test_scm_sensor_keys (tests.cloudripper.test_sensor.ScmSensorTest) ... ok
test_scm_temp_sensor_range (tests.cloudripper.test_sensor.ScmSensorTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.255s

OK
```

Reviewed By: binhuangrick

fbshipit-source-id: 89a81f380c