yosemite: enable snapshot-util (#1186)
Summary:
1. enable snapshot-util for Yv1
Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1186

Test Plan:
Build and tested pass on Yv2 systems
(note: need the commit: snapshot-util: move snapshot-util to common)

root@sled24dz-oob:\~# snapshot-util
Error: invalid number of arguments
Usage: snapshot-util [fru] --set <reason_file>
snapshot-util [fru] --set ""
snapshot-util [fru] --get <info_num> <dump_file>
snapshot-util [fru] --get --all <dump_file>
snapshot-util [fru] --clear <info_num>

   [fru]: slot1, slot2, slot3, slot4
   <type>:
     --rma  RMA information
     --mfg  MFG failure information
   <info_num>: 1 ~ 3 for RMA information; 1 for MFG failure information

root@sled24dz-oob:\~# snapshot-util slot1 --set --rma reason.txt
Getting logs...
Getting POST codes...
File Size: 618
Storing to EEPROM...
Finished
root@sled24dz-oob:\~# snapshot-util slot1 --set --rma reason.txt
Getting logs...
Getting POST codes...
File Size: 614
Storing to EEPROM...
Finished
root@sled24dz-oob:\~# snapshot-util slot1 --set --rma reason.txt
Getting logs...
Getting POST codes...
File Size: 614
Storing to EEPROM...
Finished
root@sled24dz-oob:\~# snapshot-util slot1 --set --rma reason.txt
all Info areas are occupied
Failed
root@sled24dz-oob:\~# snapshot-util slot1 --set --mfg reason.txt
Getting logs...
Getting POST codes...
File Size: 614
Storing to EEPROM...
Finished
root@sled24dz-oob:\~# snapshot-util slot1 --set --mfg reason.txt
all Info areas are occupied
Failed
root@sled24dz-oob:\~# snapshot-util slot1 --get --all alldump
Filename: alldump-rma1
File Size: 618
Dumping from EEPROM...
Filename: alldump-rma2
File Size: 614
Dumping from EEPROM...
Filename: alldump-rma3
File Size: 614
Dumping from EEPROM...
Filename: alldump-mfg1
File Size: 614
Dumping from EEPROM...
Finished
root@sled24dz-oob:\~# snapshot-util slot1 --clear --rma 3 571932
Finished
root@sled24dz-oob:\~# snapshot-util slot1 --set --rma "3rd dump"
Reason file doesn't exist, assume stdin
Getting logs...
Getting POST codes...
File Size: 622
Storing to EEPROM...
Finished

Reviewed By: amithash

fbshipit-source-id: 218759e02c