GTA: Fix the usage of log-util of cb_accl12
Summary:
# Description:
- Fix the usage of log-util of cb_accl12.
- Separate fru list for GTA and GT/GTI.

# Motivation:
- Fix the usage of log-util of cb_accl12.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/2946

Test Plan:
- Build code: Pass
- CB ACCL12 log-util: Pass
- Fru list if Artemis: Pass

# Log:
root@bmc-oob:~# log-util cb_accl12 --print
root@bmc-oob:~# log-util cb_accl12 --clear
root@bmc-oob:~# log-util cb_accl12 --print
root@bmc-oob:~# log-util
ERROR: RequiredError: fru is required
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,bmc,cb,cb_accl1,cb_accl10,cb_accl11,cb_accl12,cb_accl2,cb_accl3,cb_accl4,cb_accl5,cb_accl6,cb_accl7,cb_accl8,cb_accl9,fan_bp1,fan_bp2,fio,hpdb,hsc,mb,mc,nic0,nic1,scm,sys,vpdb} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
  -s TEXT                     Starting time for timestamp delete
  -e TEXT Needs: -s           Ending time for timestamp delete
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU

Reviewed By: williamspatrick

Differential Revision: D52536751

fbshipit-source-id: 385da5de00b2a68f16e15feeca8c511eb1b23d50