Fix missing rest_mmc.py in compute platforms
Summary:
Didn't notice that I gated `rest_mmc.py` only for network devices in https://github.com/facebook/openbmc/commit/8daaec3f8bf925d02a252a7651b85c0ebec7cff3, fixing it here.
```
# python3 /usr/local/bin/rest.py
Traceback (most recent call last):
  File "/usr/local/bin/rest.py", line 37, in <module>
    from setup_plat_routes import setup_plat_routes
  File "/usr/local/fbpackages/rest-api/setup_plat_routes.py", line 23, in <module>
    from board_setup_routes import setup_board_routes
  File "/usr/local/fbpackages/rest-api/board_setup_routes.py", line 35, in <module>
    from node_bmc import get_node_bmc
  File "/usr/local/fbpackages/rest-api/node_bmc.py", line 33, in <module>
    import rest_mmc
ImportError: No module named 'rest_mmc'
```

Test Plan: CIT tests (to ensure no regressions in other platforms), build and install `rest-api` in a test yosemite2 BMC, ensure `curl localhost:8080/api/spb/bmc` doesn't crash

Reviewed By: jerrt2003

fbshipit-source-id: 0da44e62b3