fbgc2: Added the --force option to the VR fw update
Summary:
# [Task Description]
	* Related to GC20T5T7-113
	* Enable --force option for VR firmware update to bypass the block-flash restriction when the file version matches the currently flashed version
	* When users need to reflash the same firmware version for verification or debugging purposes, --force can be used to bypass the restriction
	* Make the --force option actually take effect on VR updates

# [Motivation]
	* VR update has a block-flash mechanism to avoid unnecessary reflashing that consumes limited OTP flash cycles

# [Design]
	* Add the missing force-update interface implementation, allowing the --force flag to be properly passed down to the underlying update logic

# [Test Plan]
1. Verifying that an update using the same CRC firmware results in a failed update $ fw-util server --update vr <VR FW>

2. Verify that adding --force allows you to bypass the update limit $ fw-util server --force --update vr <VR FW>

# [Test Log]
```
[Infineon]

	[PVCCIN_FIVRA]
	root@bmc-oob:/tmp# fw-util server --update vr XDPE15284D_Wiwynn_0x60_VCCIN-20260121-0x6E1CB151.mic
	slot_id: 1, comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x60_VCCIN-20260121-0x6E1CB151.mic, force: 0
	Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
	VR vendor=XDPE152XX (devid_len=2) at 0xC0
	File CRC : 6E1CB151
	Update VR: PVCCIN_FIVRA
	WARNING: the Checksum is the same as used now 6E1CB151!
	Please use "--force" option to try again.
	ERROR: VR Firmware update failed!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr XDPE15284D_Wiwynn_0x60_VCCIN-20260121-0x6E1CB151.mic
	slot_id: 1, comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x60_VCCIN-20260121-0x6E1CB151.mic, force: 1
	Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
	VR vendor=XDPE152XX (devid_len=2) at 0xC0
	File CRC : 6E1CB151
	Update VR: PVCCIN_FIVRA
	remaining writes 19.
	updated: 100 %
	Please do power cycle to reset VR to reload configuration
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

	[PVCCD_HV]
	root@bmc-oob:/tmp# fw-util server --update vr XDPE15284D_Wiwynn_0x62_VCCD_1+0_20260108-0xA4C6D622.mic
	slot_id: 1, comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x62_VCCD_1+0_20260108-0xA4C6D622.mic, force: 0
	Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
	VR vendor=XDPE152XX (devid_len=2) at 0xC0
	File CRC : A4C6D622
	Update VR: PVCCD_HV
	WARNING: the Checksum is the same as used now A4C6D622!
	Please use "--force" option to try again.
	ERROR: VR Firmware update failed!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr XDPE15284D_Wiwynn_0x62_VCCD_1+0_20260108-0xA4C6D622.mic
	slot_id: 1, comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x62_VCCD_1+0_20260108-0xA4C6D622.mic, force: 1
	Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
	VR vendor=XDPE152XX (devid_len=2) at 0xC0
	File CRC : A4C6D622
	Update VR: PVCCD_HV
	remaining writes 21.
	updated: 100 %
	Please do power cycle to reset VR to reload configuration
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

	[PVCCINFAON]
	root@bmc-oob:/tmp# fw-util server --update vr  XDPE15284D_Wiwynn_0x76_FAON-20260113-0x242466F4.mic
	slot_id: 1, comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x76_FAON-20260113-0x242466F4.mic, force: 0
	Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
	VR vendor=XDPE152XX (devid_len=2) at 0xC0
	File CRC : 242466F4
	Update VR: PVCCINFAON
	WARNING: the Checksum is the same as used now 242466F4!
	Please use "--force" option to try again.
	ERROR: VR Firmware update failed!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr  XDPE15284D_Wiwynn_0x76_FAON-20260113-0x242466F4.mic
	slot_id: 1, comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x76_FAON-20260113-0x242466F4.mic, force: 1
	Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
	VR vendor=XDPE152XX (devid_len=2) at 0xC0
	File CRC : 242466F4
	Update VR: PVCCINFAON
	remaining writes 22.
	updated: 100 %
	Please do power cycle to reset VR to reload configuration
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

[Renesas]

	[PVCCIN_FIVRA]
	root@bmc-oob:/tmp# fw-util server --update vr  GC2.0_ISL69260_VCCIN_FIVRA_60h_20260105_adjust_OCP_99CD2F6D.hex
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_ISL69260_VCCIN_FIVRA_60h_20260105_adjust_OCP_99CD2F6D.hex, force: 0
	Detected Renesas/ISL VR
	VR vendor=ISL (devid_len=4) at 0xC0
	File CRC : 99CD2F6D
	Update VR: PVCCIN_FIVRA
	WARNING: the CRC is the same as used now 99CD2F6D!
	Please use "--force" option to try again.
	ERROR: VR Firmware update fail!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr  GC2.0_ISL69260_VCCIN_FIVRA_60h_20260105_adjust_OCP_99CD2F6D.hex
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_ISL69260_VCCIN_FIVRA_60h_20260105_adjust_OCP_99CD2F6D.hex, force: 1
	Detected Renesas/ISL VR
	VR vendor=ISL (devid_len=4) at 0xC0
	File CRC : 99CD2F6D
	Update VR: PVCCIN_FIVRA
	remaining writes 24.
	Progress: 100 %
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

	[PVCCD_HV]
	root@bmc-oob:/tmp# fw-util server --update vr  GC2.0_ISL69260_HV_62h_20251229_19C6B63A.hex
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_ISL69260_HV_62h_20251229_19C6B63A.hex, force: 0
	Detected Renesas/ISL VR
	VR vendor=ISL (devid_len=4) at 0xC0
	File CRC : 19C6B63A
	Update VR: PVCCD_HV
	WARNING: the CRC is the same as used now 19C6B63A!
	Please use "--force" option to try again.
	ERROR: VR Firmware update fail!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr  GC2.0_ISL69260_HV_62h_20251229_19C6B63A.hex
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_ISL69260_HV_62h_20251229_19C6B63A.hex, force: 1
	Detected Renesas/ISL VR
	VR vendor=ISL (devid_len=4) at 0xC0
	File CRC : 19C6B63A
	Update VR: PVCCD_HV
	remaining writes 24.
	Progress: 100 %
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

	[PVCCINFAON]
	root@bmc-oob:/tmp# fw-util server --update vr GC2.0_ISL69260_FAON_EHV_76h_20260105_adjust_OCP_8703ADDC.hex
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_ISL69260_FAON_EHV_76h_20260105_adjust_OCP_8703ADDC.hex, force: 0
	Detected Renesas/ISL VR
	VR vendor=ISL (devid_len=4) at 0xC0
	File CRC : 8703ADDC
	Update VR: PVCCINFAON
	WARNING: the CRC is the same as used now 8703ADDC!
	Please use "--force" option to try again.
	ERROR: VR Firmware update fail!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr GC2.0_ISL69260_FAON_EHV_76h_20260105_adjust_OCP_8703ADDC.hex
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_ISL69260_FAON_EHV_76h_20260105_adjust_OCP_8703ADDC.hex, force: 1
	Detected Renesas/ISL VR
	VR vendor=ISL (devid_len=4) at 0xC0
	File CRC : 8703ADDC
	Update VR: PVCCINFAON
	remaining writes 25.
	Progress: 100 %
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

[Texas Instruments]

	[PVCCIN_FIVRA]
	root@bmc-oob:/tmp# fw-util server --update vr GC2.0_TPS53689_3.0_60h_96d_PVCCIN_EHV_FIVRA_E16B_20260212_A_AL_SMBUS.csv
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_TPS53689_3.0_60h_96d_PVCCIN_EHV_FIVRA_E16B_20260212_A_AL_SMBUS.csv, force: 0
	Detected TI VR
	VR vendor=TI (devid_len=6) at 0xC0
	File CRC : E16B
	Update VR: PVCCIN_FIVRA
	WARNING: the CRC is the same as used now E16B!
	Please use "--force" option to try again.
	ERROR: VR Firmware update fail!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr GC2.0_TPS53689_3.0_60h_96d_PVCCIN_EHV_FIVRA_E16B_20260212_A_AL_SMBUS.csv
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_TPS53689_3.0_60h_96d_PVCCIN_EHV_FIVRA_E16B_20260212_A_AL_SMBUS.csv, force: 1
	Detected TI VR
	VR vendor=TI (devid_len=6) at 0xC0
	File CRC : E16B
	Update VR: PVCCIN_FIVRA
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

	[PVCCD_HV]
	root@bmc-oob:/tmp# fw-util server --update vr GC2.0_TPS53689_3.0_62h_98d_PVCCD_HV_7DB4_20260423_A_AL.csv
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_TPS53689_3.0_62h_98d_PVCCD_HV_7DB4_20260423_A_AL.csv, force: 0
	Detected TI VR
	VR vendor=TI (devid_len=6) at 0xC0
	File CRC : 7DB4
	Update VR: PVCCD_HV
	WARNING: the CRC is the same as used now 7DB4!
	Please use "--force" option to try again.
	ERROR: VR Firmware update fail!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr GC2.0_TPS53689_3.0_62h_98d_PVCCD_HV_7DB4_20260423_A_AL.csv
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_TPS53689_3.0_62h_98d_PVCCD_HV_7DB4_20260423_A_AL.csv, force: 1
	Detected TI VR
	VR vendor=TI (devid_len=6) at 0xC0
	File CRC : 7DB4
	Update VR: PVCCD_HV
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

	[PVCCINFAON]
	root@bmc-oob:/tmp# fw-util server --update vr GC2.0_TPS53689_3.0_76h_118d_PVCCINFAON_EHV_F008_20260423_A_AL.csv
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_TPS53689_3.0_76h_118d_PVCCINFAON_EHV_F008_20260423_A_AL.csv, force: 0
	Detected TI VR
	VR vendor=TI (devid_len=6) at 0xC0
	File CRC : F008
	Update VR: PVCCINFAON
	WARNING: the CRC is the same as used now F008!
	Please use "--force" option to try again.
	ERROR: VR Firmware update fail!
	Upgrade of server : vr failed

	root@bmc-oob:/tmp# fw-util server --force --update vr GC2.0_TPS53689_3.0_76h_118d_PVCCINFAON_EHV_F008_20260423_A_AL.csv
	slot_id: 1, comp: 5, intf: 0, img: GC2.0_TPS53689_3.0_76h_118d_PVCCINFAON_EHV_F008_20260423_A_AL.csv, force: 1
	Detected TI VR
	VR vendor=TI (devid_len=6) at 0xC0
	File CRC : F008
	Update VR: PVCCINFAON
	Force upgrade of server : vr succeeded

	root@bmc-oob:/tmp# power-util server 12V-cycle
	12V Power cycling fru 1...

```

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3628

Reviewed By: waffle2k

Differential Revision: D111900966

fbshipit-source-id: c511776385480bc907f2807b606a117b4046d5d4