GTA: Set FW update ongoing flag for related FRU (#2570)
Summary:
- Currently, we will only set the FRU which is currently FW update ongoing. However, there are others FRUs might switch the same mux while doing sensor polling. e.g. While meb_cxl1 is FW updating, meb_cxl2 will switch the mux to itself which might cause meb_cxl1 update failed. Hence, all related FRUs must set FW update ongoing flag.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/2570

Test Plan:
- Do FW update and see if related FRUs FW update ongoing flag will be set - pass
- Finish FW update and the flag will be cleared which will not block power-util - pass

Log:
```
root@bmc-oob:~# fw-util meb --update cxl1 Artemis_mcrk_pioneer_v61.23.00.03_fwdl.bin &> result &
[1] 4339
root@bmc-oob:~# fw-util meb --update cxl2 Artemis_mcrk_pioneer_v61.23.00.03_fwdl.bin
Upgrade aborted due to ongoing upgrade on FRU: meb
root@bmc-oob:~# fw-util meb --update cxl3 Artemis_mcrk_pioneer_v61.23.00.03_fwdl.bin
Upgrade aborted due to ongoing upgrade on FRU: meb
root@bmc-oob:~# ./fw-util meb --update bic ATMC_2023_12_FF_cxl_fw_update.bin
Upgrade aborted due to ongoing upgrade on FRU: meb
root@bmc-oob:~# fw-util meb --update cxl8 Artemis_mcrk_pioneer_v61.23.00.03_fwdl.bin
Upgrade aborted due to ongoing upgrade on FRU: meb
root@bmc-oob:/tmp/cache_store# ls fru**_fwupd
fru16_fwupd  fru18_fwupd  fru20_fwupd  fru22_fwupd  fru24_fwupd  fru26_fwupd  fru28_fwupd  fru30_fwupd  fru32_fwupd  fru34_fwupd  fru36_fwupd  fru38_fwupd  fru40_fwupd  fru42_fwupd
fru17_fwupd  fru19_fwupd  fru21_fwupd  fru23_fwupd  fru25_fwupd  fru27_fwupd  fru29_fwupd  fru31_fwupd  fru33_fwupd  fru35_fwupd  fru37_fwupd  fru39_fwupd  fru41_fwupd  fru43_fwupd
root@bmc-oob:/tmp/cache_store# power-util sled-cycle
FW update for meb is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# fw-util acb --update pesw0 offline_Artemis_v51.00.00.05_pex0.bin
updating fw on bus 3
updated: 100 %
Elapsed time:  45   sec.
Upgrade of acb : pesw0 succeeded
root@bmc-oob:~# power-util sled-cycle
packet_write_wait: Connection to fe80::e63d:1aff:fe34:8819%enp7s0 port 22: Broken pipe
root@guaigaui-Freedom:/home/kaidan_tmp/fw_at#
```

Reviewed By: zhdaniel12

Differential Revision: D44737091

fbshipit-source-id: 325e86a3e86a658ecef9a39fd2ff92c5cb3a3575