fby35: check VF E1.S present when doing E1.S power/LED control
Summary:
# Description
1. add bic_vf_get_e1s_present() to check VF E1.S present by BIC's GPIO
2. check VF E1.S present when doing E1.S power/LED control, to return error while E1.S does not exist.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3847

Test Plan:
Build and test pass on fby35 + VF
(1U-dev0 and 1U-dev2 does not exist)

root@bmc-oob:~# fpc-util slot1 1U-dev0 --identify blink
slot1 1U-dev0 is not present
root@bmc-oob:~# fpc-util slot1 1U-dev0 --identify status
slot1 1U-dev0 is not present

root@bmc-oob:~# fpc-util slot1 1U-dev1 --identify blink
fpc-util: identification for slot1 1U-dev1 is set to blink successfully
root@bmc-oob:~# fpc-util slot1 1U-dev1 --identify status
slot1 1U-dev1 LED status: BLINK

root@bmc-oob:~# fpc-util slot1 1U-dev2 --identify blink
slot1 1U-dev2 is not present
root@bmc-oob:~# fpc-util slot1 1U-dev2 --identify status
slot1 1U-dev2 is not present

root@bmc-oob:~# fpc-util slot1 1U-dev3 --identify blink
fpc-util: identification for slot1 1U-dev3 is set to blink successfully
root@bmc-oob:~# fpc-util slot1 1U-dev3 --identify status
slot1 1U-dev3 LED status: BLINK

root@bmc-oob:~# power-util slot1 1U-dev0 cycle
Power cycling fru 1 dev 1U-dev0...
Device not found
ERROR: power-util fru[1] dev 1U-dev0 [POWER_CYCLE] failed

root@bmc-oob:~# power-util slot1 1U-dev1 cycle
Power cycling fru 1 dev 1U-dev1...
root@bmc-oob:~# power-util slot1 1U-dev1 status
Power status for fru 1 dev 1U-dev1 : ON

root@bmc-oob:~# power-util slot1 1U-dev2 cycle
Power cycling fru 1 dev 1U-dev2...
Device not found
ERROR: power-util fru[1] dev 1U-dev2 [POWER_CYCLE] failed

root@bmc-oob:~# power-util slot1 1U-dev3 cycle
Power cycling fru 1 dev 1U-dev3...
root@bmc-oob:~# power-util slot1 1U-dev3 status
Power status for fru 1 dev 1U-dev3 : ON

Reviewed By: williamspatrick, wangx6f

Differential Revision: D45723018

fbshipit-source-id: e643261d5dd3a6cabc7a2da6c1adbb8f5f769d70