wedge400: libpal: Fix pal_get_fru_id("fcm")
Summary:
Caught by CIT's `LibPalTest`, calls to `pal_get_fru_id("fcm")` return with -1 and log the following error:
```
pal_get_fru_id: Wrong fru#fcm
```

It seems the FRU id is defined in the `FRU_FCM` constant, but the entry was missing in `pal_get_fru_id()`

Test Plan:
Manually called `pal_get_fru_id("fcm")`, it now returns `3` (`FRU_FCM` in wedge400's `pal.h`, as expected).

Ran CIT `LibPalTest` on a wedge400:
```
tar -cz tests2 | ssh ${wedge400_bmc} "tar -xzf - -C /usr/local/bin" && ssh "${wedge400_bmc}" python /usr/local/bin/tests2/cit_runner.py --platform wedge400 --run-test tests.wedge400.test_libpal.LibPalTest
```

Before:
```
======================================================================
ERROR: test_pal_get_fru_id (tests.wedge400.test_libpal.LibPalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_libpal_test.py", line 88, in test_pal_get_fru_id
    fru_id = pal.pal_get_fru_id(fru_name)
  File "/usr/lib/python3.7/site-packages/pal.py", line 64, in pal_get_fru_id
    raise ValueError("Invalid FRU name: " + repr(fru_name))
ValueError: Invalid FRU name: 'fcm'
```

After:
```
test_pal_get_fru_id (tests.wedge400.test_libpal.LibPalTest) ... ok
```

Reviewed By: vineelasmile

fbshipit-source-id: 782f8bcf3f