tools: fboss-lite: remove test_emmc.py from cit template
Summary:
# Description
tools: fboss-lite: remove test_emmc.py from cit template

# Motivation
Since the runBMC card DVT, already remove eMMC chip, which is mounted to /mnt/data1
remove test case from template to prepare for the next upcoming platform,

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1880

Test Plan:
initial cit for new dummy platform
```
pokyuser@bc90a6af61ca:/workdir$ python3 tools/fboss-lite/new-fblite.py -n test_new -p cit
Work directory is set to /workdir
Updated platforms with test_new
processing CIT scripts under tests2/tests/test_new..
Added base CIT suit for test_new
Commit the CIT patch to local repo..
Committed base CIT suit for test_new
pokyuser@bc90a6af61ca:/workdir$
```

use the CIT validate on Icecube EVT1 platform
```
root@bmc-oob:/run/tests2# python cit_runner.py -p test_new
test_busybox_usage_strings (tests.test_new.test_busybox_syntax.BusyBoxSyntaxTest.test_busybox_usage_strings) ... ok
test_cpu_utilization (tests.test_new.test_cpu_utilization.CpuUtilizationTest.test_cpu_utilization)
Test that CPU utilization is below a threshold. ... ok
test_kernel_path_exists (tests.test_new.test_kernel_abi.KernelABITest.test_kernel_path_exists) ... ok
test_endpoint_api (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api) ... ok
test_endpoint_api_sys (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys) ... ok
test_endpoint_api_sys_bmc (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc) ... ok
test_endpoint_api_sys_bmc_mtd (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc_mtd) ... ok
test_endpoint_api_sys_bmc_secondary_boot (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc_secondary_boot) ... ok
test_endpoint_api_sys_fc_present (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_fc_present) ... ok
test_endpoint_api_sys_firmware_info_all (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_firmware_info_all) ... skipped 'not available'
test_endpoint_api_sys_mb (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb) ... ok
test_endpoint_api_sys_mb_fruid (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid) ... FAIL
...
(tests.test_new.test_syslog_restart.SyslogRestartTest.test_syslog_restart_no_duplicates) ... ok
test_syslog_restart_pid_changed (tests.test_new.test_syslog_restart.SyslogRestartTest.test_syslog_restart_pid_changed) ... ok

======================================================================
FAIL: test_endpoint_api_sys_mb_fruid (tests.test_new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_rest_endpoint_test.py", line 390, in test_endpoint_api_sys_mb_fruid
    self.set_endpoint_fruid_attributes()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/tests2/tests/test_new/test_rest_endpoint.py", line 50, in set_endpoint_fruid_attributes
    self.fail("this test case needs to define the fru format")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: this test case needs to define the fru format

----------------------------------------------------------------------
Ran 19 tests in 46.260s

FAILED (failures=1, skipped=3)
root@bmc-oob:/run/tests2#
```
the eMMC test case had been removed.

Reviewed By: lsiudut

Differential Revision: D77862021

Pulled By: ezeob002

fbshipit-source-id: 288aeeb4519949d735b0c8f204d19f7293e84848