celesticabmc: CIT: update to support new product name LEH800BCLS
Summary:
# Description
celesticabmc: CIT: update to support new product name LEH800BCLS

# Motivation
to support Anacapa EVT2
```
root@bmc:/run/tests2# python cit_runner.py -p celesticabmc -r tests.celesticabmc.test_eeprom
test_asset_tag (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_asset_tag) ... ok

...

test_product_name (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_product_name)
Tests if the platform defined product name is present ... ERROR

...

======================================================================
ERROR: test_product_name (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_product_name)
Tests if the platform defined product name is present
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_eeprom_test.py", line 106, in test_product_name
    found, name = self.is_found_product_name()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/tests2/common/base_eeprom_test.py", line 92, in is_found_product_name
    name = self.get_product_name()
  File "/run/tests2/common/base_eeprom_test.py", line 87, in get_product_name
    self.set_product_name()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/tests2/tests/celesticabmc/test_eeprom.py", line 43, in set_product_name
    raise ValueError(f"Unsupported platform: {get_platform_id()}")
ValueError: Unsupported platform: None

----------------------------------------------------------------------
Ran 13 tests in 8.263s

FAILED (errors=1)
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1942

Test Plan:
Validated on Anacapa EVT-2
```
root@bmc:/run/tests2# fboss-board-revision.sh -s
LEH800BCLS_EVT-2
root@bmc:/run/tests2# python cit_runner.py -p celesticabmc -r tests.celesticabmc.test_eeprom
test_asset_tag (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_asset_tag) ... ok
test_bmc_mac (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_bmc_mac) ... ok
test_extended_mac_base (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_extended_mac_base) ... ok
test_local_mac (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_local_mac) ... ok
test_location_on_fabric (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_location_on_fabric) ... ok
test_odm_pcb (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_odm_pcb) ... ok
test_product_name (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_product_name)
Tests if the platform defined product name is present ... ok
test_product_part_number (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_product_part_number) ... ok
test_product_serial_number (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_product_serial_number) ... ok
test_switch_asic_mac (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_switch_asic_mac) ... ok
test_system_manufacturer (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_system_manufacturer) ... ok
test_version (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_version) ... ok
test_x86_mac (tests.celesticabmc.test_eeprom.ChassisEepromTest.test_x86_mac) ... ok

----------------------------------------------------------------------
Ran 13 tests in 8.182s

OK
root@bmc:/run/tests2#
```

Reviewed By: mikechoifb

Differential Revision: D115027576

Pulled By: ezeob002

fbshipit-source-id: 4011eff609ecf18b6efd55cb70995a79d5a176a5