fbgc:fbgc2: Fix XDPE152XX VR fw update buffer overflow
Summary:
# [Task Description]
	* Related to GC20T5T7-113
	* Fixes a memory usage error in the CRC reading logic during the VR firmware update process that caused the same-version overwrite prevention mechanism to fail

# [Motivation]
	* The CRC read interface expects a full-size buffer, but the caller allocated insufficient space, corrupting the value

# [Design]
	* Adjust how the data is received to ensure the retrieved CRC value is complete and correct

# [Test Plan]
1. Verifying that an update using the same CRC firmware results in a failed update $ fw-util server --update vr <vr fw>

# [Test Log]
```
[PVCCIN_FIVRA]
1. root@bmc-oob:/tmp# fw-util server --update vr XDPE15284D_Wiwynn_0x60_VCCIN-20260121-0x6E1CB151.mic
comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x60_VCCIN-20260121-0x6E1CB151.mic, force: 0
Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
VR vendor=XDPE152XX (devid_len=2) at 0xC0
File CRC : 6E1CB151
Update VR: PVCCIN_FIVRA
WARNING: the Checksum is the same as used now 6E1CB151!
Please use "--force" option to try again.
ERROR: VR Firmware update fail!
Upgrade of server : vr failed

[PVCCD_HV]
1. root@bmc-oob:/tmp# fw-util server --update vr XDPE15284D_Wiwynn_0x62_VCCD_1+0_20260108-0xA4C6D622.mic
comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x62_VCCD_1+0_20260108-0xA4C6D622.mic, force: 0
Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
VR vendor=XDPE152XX (devid_len=2) at 0xC0
File CRC : A4C6D622
Update VR: PVCCD_HV
WARNING: the Checksum is the same as used now A4C6D622!
Please use "--force" option to try again.
ERROR: VR Firmware update fail!
Upgrade of server : vr failed

[PVCCINFAON]
root@bmc-oob:/tmp# fw-util server --update vr XDPE15284D_Wiwynn_0x76_FAON-20260113-0x242466F4.mic
comp: 5, intf: 0, img: XDPE15284D_Wiwynn_0x76_FAON-20260113-0x242466F4.mic, force: 0
Detected XDPE152xx (Product ID: 0x8A, Rev: 0x03)
VR vendor=XDPE152XX (devid_len=2) at 0xC0
File CRC : 242466F4
Update VR: PVCCINFAON
WARNING: the Checksum is the same as used now 242466F4!
Please use "--force" option to try again.
ERROR: VR Firmware update fail!
Upgrade of server : vr failed
```

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3670

Reviewed By: waffle2k

Differential Revision: D115671817

fbshipit-source-id: 2806d4fa254ac2e37433c68ea063bf2561172831