fby3: GPv3: block 12V-cycle when updating NIC firmware (#1728)
Summary:
-When updating firmware, we should block all power control commands to avoid terminating the update.
For T17, we need to block 12V-cycle except for sled-cycle.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1728

Test Plan:
-build code(pass)
-make sure 12V-cycle is blocked when updating NIC firmware(pass)

-try to do sled-cycle and 12V-cycle when updating NIC
root@bmc-oob:~# power-util sled-cycle
FW update for nic is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
Please make sure no firmware update is ongoing
ERROR: power-util fru[1] [12V_CYCLE] failed

-try to do sled-cycle and 12V-cycle when updating BMC
root@bmc-oob:~# power-util sled-cycle
FW update for bmc is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
Please make sure no firmware update is ongoing
ERROR: power-util fru[1] [12V_CYCLE] failed

-try to do sled-cycle and 12V-cycle when updating FPGA(FRU_BMC)
root@bmc-oob:~# power-util sled-cycle
FW update for bmc is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
Please make sure no firmware update is ongoing
ERROR: power-util fru[1] [12V_CYCLE] failed

-try to do sled-cycle and 12V-cycle when updating SB BIC
root@bmc-oob:~# power-util sled-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# power-util slot1 12V-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed
root@bmc-oob:~#

Reviewed By: williamspatrick

fbshipit-source-id: 3209d2f29a