remove type hint in rest_ntpstatus
Summary:
D48313365 fixed issues with restapi ntp endpoint, but it used the following type hints:
```
system_clock_synchronized: bool = False
ntp_active: bool = False
```
Some of our older platforms are running python 3.5, which does not see this as valid syntax and thus it breaks the restapi

```
root@sled1602-oob:~# python3 /usr/local/bin/rest.py
Traceback (most recent call last):
  File "/usr/local/bin/rest.py", line 38, in <module>
    from setup_plat_routes import setup_plat_routes
  File "/usr/local/fbpackages/rest-api/setup_plat_routes.py", line 24, in <module>
    from common_setup_routes import setup_common_routes
  File "/usr/local/fbpackages/rest-api/common_setup_routes.py", line 24, in <module>
    from rest_ntpstatus import rest_ntp_status_handler
  File "/usr/local/fbpackages/rest-api/rest_ntpstatus.py", line 75
    system_clock_synchronized: bool = False
                             ^
SyntaxError: invalid syntax
```

Test Plan:
Manually remove type hints on above fby2 and see that REST API is now working:
```
$ curl -k https://rtptest3317-oob.atn1.facebook.com:8443/api | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   232  100   232    0     0    213      0  0:00:01  0:00:01 --:--:--   213
{
  "Information": {
    "Description": "FBY2 RESTful API Entry",
    "version": "v0.2"
  },
  "Actions": [],
  "Resources": [
    "attestation",
    "bmc",
    "fans",
    "fwinfo",
    "logs",
    "mezz",
    "sensors",
    "server1",
    "server2",
    "server3",
    "server4",
    "spb",
    "sys"
  ]
}
```

Reviewed By: jagpalgill

Differential Revision: D48988962

fbshipit-source-id: 80baf04777097da8d036fe8fd855cb29d5bc254b