fby3: GPv3: improve firmware update for class 2 (#1783)
Summary:
-On T17 and T8, BMC will send notification SELs to the other BMC when it wants to run firmware update or control fan speed.
If two BMCs want to update their 2OU_BIC in parallel, two BMCs will send notification SELs to each other.
And one of BMCs may update 2OU_BIC to fail because the server board BIC(SB_BIC) which is responsible for helping transfer data can't handle requests from two sources because SB_BIC only supports 1 IPMB handler.
when SB_BIC is transferring firmware image, and it also needs to transfer notification SELs, the mailbox in SB_BIC will be messed up.

BMC will fully rely on `critical activity` bit and remove notification SELs in the future.
When the bit is asserted:
1. block sled-cycle command

2. one of BMCs wouldn't be allowed to access BB firmware to avoid accessing in parallel.
Ps. Because BMC only has a critical activity bit to identify the firmware update activity, which means when the bit is asserted, it can be SB_BIC, SB_CPLD, BB_CPLD, BB_BIC, etc,.

3. if the bit keeps low around 2~4s, it means fan manual mode is set
if the bit keeps low around 5~7s, it means fan auto mode is set

4. provide a temporary RPM/PWM to fscd.
Ps. if BMC is updating firmware and fscd is still running, fscd can't access RPM/PWM becasue it needs to get RPM/PWM via SB_BIC.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1783

Test Plan:
-build code(pass)
-when updating firmware on a slot, block the other slot to run sled-cycle(pass)
-when updating firmware on a slot, block the other slot to access baseboard firmware(pass)
-when updating firmware, check the temporary RPM/PWM are provided(pass)
-control fan speed manually(pass)

[LOG]
root@bmc-oob:~# power-util sled-cycle
power lock flag is asserted, please make sure no firmware update is ongoing
If you still want to proceed, please clean the flag manually!
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# fw-util slot1 --version
```````````````````````````````````````
BB Bridge-IC Version: NA (A critical activity is ongoing on the sled)
BB Bridge-IC Bootloader Version: NA (A critical activity is ongoing on the sled)
BB CPLD Version: NA (A critical activity is ongoing on the sled)
```````````````````````````````````````
root@bmc-oob:~# log-util all --print
2021 Aug 26 00:09:11 log-util: User cleared all logs
0    all      2021-08-26 00:10:08    power-util       SLED_CYCLE starting...
0    all      2021-08-26 00:10:09    power-util       SLED_CYCLE failed because a critical activity is ongoing

root@bmc-oob:~# fan-util auto-mode status
Auto Mode: Normal
root@bmc-oob:~# fan-util auto-mode disable
Setup fan mode control...
root@bmc-oob:~# fan-util auto-mode status
Auto Mode: Manual
root@bmc-oob:~# fan-util --set 65
Setting Zone 0 speed to 65%
Setting Zone 1 speed to 65%
Setting Zone 2 speed to 65%
Setting Zone 3 speed to 65%
root@bmc-oob:~# fan-util --get
Fan 0 Speed: 7184 RPM (65%)
Fan 1 Speed: 6421 RPM (65%)
Fan 2 Speed: 7260 RPM (65%)
Fan 3 Speed: 6394 RPM (65%)
Fan 4 Speed: 7292 RPM (65%)
Fan 5 Speed: 6385 RPM (65%)
Fan 6 Speed: 7250 RPM (65%)
Fan 7 Speed: 6426 RPM (65%)

[the temporary RPM/PWM]
root@bmc-oob:~# fan-util --get
Fan 0 Speed: 7500 RPM (70%)
Fan 1 Speed: 7500 RPM (70%)
Fan 2 Speed: 7500 RPM (70%)
Fan 3 Speed: 7500 RPM (70%)
Fan 4 Speed: 7500 RPM (70%)
Fan 5 Speed: 7500 RPM (70%)
Fan 6 Speed: 7500 RPM (70%)
Fan 7 Speed: 7500 RPM (70%)
Fan Mode: Normal
FSCD Driver: linear_nic(nic:nic_sensor_temp)
Sensor Fail: None
Fan Fail: None

Reviewed By: zhdaniel12

fbshipit-source-id: 8b6fcbd558