montblanc: openbmc-utils: Added support for NL2 BIOS firmware update
Summary:
# Description
Netlake 2.0 (the new COMe) uses the AMD EPYC Fire Range CPU, and BIOS has used 64M flash chip.

# Motivation
This PR is used to change the host flash size to 64M and added a check for BIOS flash file size to prevent firmware files from being misused between NL1.0 and NL2.0.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1921

Test Plan:
Test on NL2.0 COMe based platform:
```
root@bmc-oob:~# spi_util.sh write spi1 COME_BIOS /tmp/NL2108.rom
Select BIOS flash..
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 2.0 detected (Value: 0xa9)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Flash file size:67108864
Probe flashes..
Copy /tmp/NL2108.rom to /tmp/.spi_util_image.tmp..
Write /tmp/.spi_util_image.tmp to /dev/mtd7..
flashrom v1.5.1 on Linux 6.12.55-montblanc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 3ffffff
Verifying flash... VERIFIED.
Restore environment..
root@bmc-oob:~#
---------------------use NL1.0 BIOS image file---------------------
root@bmc-oob:~# spi_util.sh write spi1 COME_BIOS /tmp/NL404.bin
Select BIOS flash..
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 2.0 detected (Value: 0x99)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Error: File size (33554432 bytes) is less than 64MB for Netlake 2.0.
Restore environment..
root@bmc-oob:~#
```
Test on NL1.0 COMe based platform:
```
root@bmc-oob:~# spi_util.sh write spi1 COME_BIOS /tmp/NL404.bin
Select BIOS flash..
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 1.0 detected (Value: 0x0d)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Flash file size:33554432
Probe flashes..
Copy /tmp/NL404.bin to /tmp/.spi_util_image.tmp..
Append 33554432 bytes to /tmp/.spi_util_image.tmp..
Write /tmp/.spi_util_image.tmp to /dev/mtd7..
flashrom v1.5.1 on Linux 6.12.55-montblanc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 3ffffff
Verifying flash... VERIFIED.
Restore environment..
root@bmc-oob:~#

---------------------use NL2.0 BIOS image file---------------------
root@bmc-oob:~# spi_util.sh write spi1 COME_BIOS /tmp/NL2108.rom
Select BIOS flash..
Identifying board type...
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Netlake 1.0 detected (Value: 0x0d)
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Error: File size for Netlake 1.0 must be between 1 byte and 32MB.
Restore environment..
root@bmc-oob:~#
```
The IOB FPGA uses the same script, and the flashing test is unaffected. The result is below:
```
root@bmc-oob:~# spi_util.sh write spi1 IOB_FPGA /tmp/mp3_iob_v0.51.bit
Select IOB_FPGA flash..
Probe flashes..
Copy /tmp/mp3_iob_v0.51.bit to /tmp/.spi_util_image.tmp..
Append 14585095 bytes to /tmp/.spi_util_image.tmp..
Write /tmp/.spi_util_image.tmp to /dev/mtd7..
flashrom v1.5.1 on Linux 6.12.55-montblanc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to ffffff
Restore environment..
root@bmc-oob:~#
```

Reviewed By: binhuang00

Differential Revision: D101299024

Pulled By: ezeob002

fbshipit-source-id: d6e4fb27cf516ad618d7a3c55e55091f332fc3cc