restapi: fix import name error for old platforms using python lower than 3.6
Summary:
Found by CIT on Bryce Canyon, restapi can't bring up port 8080 or 8443 thus causing test to fail.
The root cause is:
```
root@dhcp-100-96-192-237:~# python3 /usr/local/bin/rest.py
Traceback (most recent call last):
  File "/usr/local/fbpackages/rest-api/node_attestation.py", line 22, in <module>
    import obmc_attestation.measure
ImportError: No module named 'obmc_attestation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rest.py", line 37, in <module>
    from setup_plat_routes import setup_plat_routes
  File "/usr/local/fbpackages/rest-api/setup_plat_routes.py", line 26, in <module>
    from common_tree import setup_common_routes
  File "/usr/local/fbpackages/rest-api/common_tree.py", line 33, in <module>
    from node_attestation import get_tree_attestation
  File "/usr/local/fbpackages/rest-api/node_attestation.py", line 26, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```
The `ModuleNotFoundError` is not available till python3.6. However on bryce canyon we are running python3.5
```
root@dhcp-100-96-192-237:~# python --version
Python 3.5.3
```

Test Plan:
Restapi can be start on the bc correctly:
```
root@dhcp-100-96-192-237:~# python3 /usr/local/bin/rest.py

[davcheng@devvm1584.prn0 ~] go-fbttn
Last login: Wed May 19 00:54:06 2021 from 2401:db00:eef0:1120:3520:0:1401:dc90
root@dhcp-100-96-192-237:~# netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:30003         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 :::8080                 :::*                    LISTEN
tcp        0      0 ::1:30003               :::*                    LISTEN
tcp        0      0 :::22                   :::*                    LISTEN
```

Reviewed By: jerrt2003

fbshipit-source-id: 01b355d024