Remove deprecated /Power and /Thermal endpoints
Summary: All data that is provided by these endpoints are also provided by the newer /Sensors endpoint. Also usecases have been migrated to use the new endpoint, so this is safe to remove

Test Plan:
```
➜  openbmc git:(helium) ✗ ./tests2/ptest-runner rest-api
Found 507 recipes of which 14 define unit-tests
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../meta-facebook/recipes-utils/mac-util/mac-util_0.1.bb: Unable to get checksum for mac-util SRC_URI entry eeprom.h: file could not be found
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/recipes-utils/mypy-native/mypy_0.910.bb: Unable to get checksum for nativesdk-mypy SRC_URI entry 001-load-so-fix.patch: file could not be found
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/recipes-utils/mypy-native/mypy_0.910.bb: Unable to get checksum for mypy-native SRC_URI entry 001-load-so-fix.patch: file could not be found
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/recipes-utils/mypy-native/mypy_0.910.bb: Unable to get checksum for mypy SRC_URI entry 001-load-so-fix.patch: file could not be found
Parsing recipes: 100% |########################################################################################################################################################| Time: 0:00:14
WARNING: No recipes available for:
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby3-image.bbappend
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby35-image.bbappend
Initialising tasks: 100% |#####################################################################################################################################################| Time: 0:00:03
START: ptest-runner
2021-11-19T03:55
BEGIN: /usr/lib/rest-api/ptest
/usr/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py:110: DeprecationWarning: "coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def handler_wrapper(*args, **kwargs):
/usr/lib/python3.8/site-packages/aiohttp/helpers.py:141: DeprecationWarning: Task.current_task() is deprecated, use asyncio.current_task() instead
  task = asyncio.Task.current_task(loop=loop)
.Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60ae508>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60ae7f0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60aea48>()]>>
./usr/local/fbpackages/rest-api/test_async_ratelimiter.py:88: RuntimeWarning: coroutine 'TestRatelimiterWorks.__assert_normal_request' was never awaited
  self.__assert_normal_request("GET", "agent2")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:55> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60ae2e0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:55> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60aeb08>()]>>
.Task was destroyed but it is pending!
task: <Task pending name='Task-53' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60ae2f8>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-55' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60ae6d0>()]>>
............../usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............../usr/lib/python3.8/site-packages/aiohttp/web_server.py:44: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  yield from asyncio.gather(*coros, loop=self._loop)
...................s...../usr/lib/python3.8/linecache.py:171: ResourceWarning: unclosed file <_io.FileIO name='/tmp/tmpjqd298uw' mode='ab' closefd=True>
  get_source = getattr(loader, 'get_source', None)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'
........................................................
----------------------------------------------------------------------
Ran 114 tests in 1.541s

OK (skipped=1)
Name                                                                       Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------
/usr/local/fbpackages/rest-api/acl_config.py                                   2      0   100%
/usr/local/fbpackages/rest-api/acl_providers/__init__.py                       0      0   100%
/usr/local/fbpackages/rest-api/acl_providers/cached_acl_provider.py           37      2    95%   52-53
/usr/local/fbpackages/rest-api/acl_providers/common_acl_provider_base.py      41      1    98%   61
/usr/local/fbpackages/rest-api/async_ratelimiter.py                           18      1    94%   56
/usr/local/fbpackages/rest-api/boardroutes.py                                  1      0   100%
/usr/local/fbpackages/rest-api/common_auth.py                                 56      5    91%   57-60, 139
/usr/local/fbpackages/rest-api/common_logging.py                              32      2    94%   61, 71
/usr/local/fbpackages/rest-api/common_middlewares.py                          76     12    84%   48, 68-69, 76-80, 89-90, 125-126
/usr/local/fbpackages/rest-api/common_utils.py                                57     41    28%   21-29, 43-48, 52-67, 83-88, 96, 102-116
/usr/local/fbpackages/rest-api/common_webapp.py                               13      6    54%   9, 13-19
/usr/local/fbpackages/rest-api/redfish_account_service.py                     17      7    59%   25-34, 38-46
/usr/local/fbpackages/rest-api/redfish_base.py                                54     36    33%   89, 96, 112-116, 119-130, 141-144, 147-154, 157-160, 163
/usr/local/fbpackages/rest-api/redfish_bios_firmware_dumps.py                204    154    25%   23-24, 40-41, 45-46, 50-51, 55-56, 89, 96-102, 107-117, 120-172, 177-180, 185-209, 212-258, 265-278, 281-312, 324, 327, 330, 333, 336
/usr/local/fbpackages/rest-api/redfish_chassis.py                             26      0   100%
/usr/local/fbpackages/rest-api/redfish_chassis_helper.py                     188    118    37%   60-62, 66-67, 71-72, 77, 95-106, 112-119, 127-133, 137-189, 195-202, 206-225, 250-251, 257-299, 305, 309, 333
/usr/local/fbpackages/rest-api/redfish_common_routes.py                       59      1    98%   28
/usr/local/fbpackages/rest-api/redfish_computer_system.py                     55     26    53%   30-42, 45-48, 53-81, 86-102, 105-124, 136, 139, 142
/usr/local/fbpackages/rest-api/redfish_managers.py                           104     49    53%   22-30, 34-46, 50-55, 59-64, 69-91, 142-151
/usr/local/fbpackages/rest-api/redfish_powercycle.py                          59     10    83%   68, 79, 85, 93, 103, 122, 127, 129, 137, 142
/usr/local/fbpackages/rest-api/redfish_sensors.py                            112     23    79%   23, 56, 90-93, 101, 117, 134, 193, 195, 197, 199, 201, 203, 209-220
/usr/local/fbpackages/rest-api/redfish_service_root.py                        27      8    70%   39, 41-42, 49-59, 63-2506
/usr/local/fbpackages/rest-api/redfish_session_service.py                     12      7    42%   7-21, 25-34
/usr/local/fbpackages/rest-api/rest_config.py                                 37      1    97%   103
/usr/local/fbpackages/rest-api/rest_fruid.py                                  21     16    24%   30-47
/usr/local/fbpackages/rest-api/rest_fscd_sensor_data.py                       30      3    90%   59-62
/usr/local/fbpackages/rest-api/rest_fwinfo.py                                 47      1    98%   78
/usr/local/fbpackages/rest-api/rest_gpios.py                                  22      4    82%   33-59
/usr/local/fbpackages/rest-api/rest_mmc.py                                    25      0   100%
/usr/local/fbpackages/rest-api/rest_modbus_cmd.py                             86     10    88%   105, 125-128, 133, 137-141, 172
/usr/local/fbpackages/rest-api/rest_pal_legacy.py                            169    141    17%   48-49, 53-68, 72-80, 84-92, 97-105, 109-116, 124-145, 150-197, 201-216, 220-230, 234-236, 240-245, 249-257
/usr/local/fbpackages/rest-api/rest_utils.py                                   6      0   100%
--------------------------------------------------------------------------------------------------------
TOTAL                                                                       1693    685    60%
DURATION: 4
END: /usr/lib/rest-api/ptest
2021-11-19T03:55
STOP: ptest-runner
```

Reviewed By: doranand

fbshipit-source-id: e762a61237