tests2: shell_util.py: fix string format for raise Exception message (#465)
Summary:
When shell_util.py raise an Exception, sometimes it will cause tuple index out of range because of string format.
We met such error when we do CIT stress test, and it can not provide enough for users to debug when this happens.
Error log:
ERROR: test_fan4_pwm_set (tests.wedge400.test_fans.FansTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/utils/shell_util.py", line 42, in run_shell_cmd
    raise Exception(err + " [FAILED]")
Exception: open watchdog: failed
 [FAILED]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/wedge400/test_fans.py", line 126, in test_fan4_pwm_set
    super().fan_set_and_read(fan_id=4, pwm=70)
  File "/usr/local/bin/tests2/common/base_fans_test.py", line 168, in fan_set_and_read
    self.kill_fan_controller()
  File "/usr/local/bin/tests2/common/base_fans_test.py", line 59, in kill_fan_controller
    run_shell_cmd(cmd)
  File "/usr/local/bin/tests2/utils/shell_util.py", line 45, in run_shell_cmd
    raise Exception("Failed to run command = {} and exception {}".format(cmd), e)
IndexError: tuple index out of range
Pull Request resolved: https://github.com/facebookexternal/openbmc.celestica/pull/465

Test Plan:
tianhui@openbmc-ubuntu16:~/tianhui_d/facebook/openbmc.celestica/tests2/utils$ python3
Python 3.8.1 (default, Jan  1 2020, 08:33:43)
[GCC 5.3.1 20160413] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shell_util
>>> shell_util.
shell_util.run_cmd(        shell_util.run_shell_cmd(  shell_util.subprocess
>>> shell_util.run_shell_cmd("ls /dev/fail")
Traceback (most recent call last):
  File "/share/disk_d/tianhui/facebook/openbmc.celestica/tests2/utils/shell_util.py", line 42, in run_shell_cmd
    raise Exception(err + " [FAILED]")
Exception: ls: cannot access '/dev/fail': No such file or directory
 [FAILED]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/disk_d/tianhui/facebook/openbmc.celestica/tests2/utils/shell_util.py", line 45, in run_shell_cmd
    raise Exception("Failed to run command = {} and exception {}".format(cmd, e))
Exception: Failed to run command = ls /dev/fail and exception ls: cannot access '/dev/fail': No such file or directory
 [FAILED]
>>> shell_util.run_shell_cmd("ls /dev/zero")
'/dev/zero\n'
>>>

Reviewed By: joancaneus

fbshipit-source-id: a8ee97fbe7