Take the MTD name from the command line
Test Plan:
Adjusted and added unit tests. Ran with an invalid device,
it exits:

```
ERROR:2020-05-14 11:31:46,431 Unhandled exception raised.
Traceback (most recent call last):
  File "/tmp/improve_system.py", line 236, in <module>
      improve_system(logger)
  File "/tmp/improve_system.py", line 215, in improve_system
      raise ValueError("No device with label {}".format(args.mtd_labels))
ValueError: No device with label ljhljhljh
```

Ran it with an existing flash as an argument and it flashed it:

```
$ /tmp/improve_system.py --mtd-labels flash0 flash
[...]
INFO:2020-05-01 12:22:19,308 Finished running `/usr/local/bin/openbmc_gpio_util.py config ROMCS1#`.
INFO:2020-05-01 12:22:20,728 Flashing flash0
INFO:2020-05-01 12:22:20,768 Checking the sanity of the request
INFO:2020-05-01 12:22:28,448 Proceeding with flash
INFO:2020-05-01 12:22:28,487 Starting to run `flashcp flash /dev/mtd5`.
```

Without arguments it does its old thing:

```
INFO:2020-05-01 12:39:24,745 Flashing flash1
INFO:2020-05-01 12:39:24,807 Checking the sanity of the request
INFO:2020-05-01 12:39:28,984 Proceeding with flash
INFO:2020-05-01 12:39:29,062 Starting to run `flashcp flash /dev/mtd5`.
INFO:2020-05-01 12:41:36,022 Finished running `flashcp flash /dev/mtd5`.
INFO:2020-05-01 12:41:37,033 Flashing flash0
INFO:2020-05-01 12:41:37,069 Checking the sanity of the request
INFO:2020-05-01 12:41:39,233 Proceeding with flash
INFO:2020-05-01 12:41:39,243 Starting to run `flashcp flash /dev/mtd4`.
```

which is necessary to keep backwards compatibility and not break
provisioning while we adapt oobgrader.

Tested on sled0502ju-oob.06.ftw3.facebook.com (Yv2) to confirm that it
doesn't break verified-boot:

```
INFO:2020-05-01 12:50:33,895 Checking the sanity of the request
INFO:2020-05-01 12:50:41,822 Proceeding with flash
INFO:2020-05-01 12:50:45,058 Starting to run `flashcp flash.tmp /dev/mtd5`.
```

Reviewed By: kawmarco

fbshipit-source-id: 05a89cf45d