fby3: improve power lock mechanism (#1688)
Summary:
Set a new kv to store power lock time instead of setting "fru%d_fwupd" key,
which will block firmware update and power control other than sled cycle.
With this change, power lock only block sled cycle in both slot and 12V-cycle in local slot.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1688

Test Plan:
Build and test on fby3 class 2 system.
1. Power control during another slot updating firmware
root@bmc-oob:~# power-util sled-cycle
power lock flag is asserted, please make sure no firmware update is ongoing
If you still want to proceed, please clean the flag manually! ret=0, lock=0 0
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# power-util slot1 cycle
Power cycling fru 1...
root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
packet_write_wait: Connection to 192.168.88.225 port 22: Broken pipe

2. Power control during local slot updating firmware
root@bmc-oob:~# power-util slot1 12V-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed
root@bmc-oob:~# power-util sled-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed

3. No abnormal log in /var/log/messages.

Reviewed By: tao-ren

fbshipit-source-id: 3e411a5067