Migrate gpio test to citv2
Summary:
This diff adds a tests for gpio testing.
- Input data is platform driven with a python based list for gpios
- The core logic for gpio is verifying is the shadow root path
exists
- Additionally also check if the gpio attributes exist.
- Given that there are a lot of GPIO, chose to create subtests
for each gpio for better dbeuggability, and treate each gpio as
an entity

Test Plan:
1) When gpio test passes :
root@rsw1aw-oob:/usr/local/bin/tests2# python cit_runner.py --run-test tests.wedge100.test_gpio.GpioTest.test_gpios
test_gpios (tests.wedge100.test_gpio.GpioTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 3.948s

2) Induce a failure by setting a gpio name incorrectly:
Observe each gpto is treated as a "test"
root@rsw1aw-oob:/usr/local/bin/tests2# python cit_runner.py --run-test tests.wedge100.test_gpio.GpioTest.test_gpios
test_gpios (tests.wedge100.test_gpio.GpioTest) ...
======================================================================
FAIL: test_gpios (tests.wedge100.test_gpio.GpioTest) (gpio='BMC_COM__ISOBUF_EN')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 59, in test_gpios
    self.gpio_shadow_path(gpio)
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 46, in gpio_shadow_path
    self.assertTrue(os.path.exists(gpio_path), "GPIO missing={}".format(gpioname))
AssertionError: False is not true : GPIO missing=BMC_COM__ISOBUF_EN

----------------------------------------------------------------------
Ran 1 test in 3.113s

FAILED (failures=1)

Reviewed By: tomrepo

fbshipit-source-id: dd8814e431