Ensure decode_modbus_address gets an int addr
Summary:
When we fail on firmware update we currently try to get some
debug information and fail since decode_modbus_address expects addr
(it's first arg) to be an int and we give bytes. Without this change
we fail with this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/psu-update-delta-orv3.py", line 315, in <module>
    main()
  File "/usr/local/bin/psu-update-delta-orv3.py", line 307, in main
    print(get_status_reg(args.addr.to_bytes(1, "big")))
  File "/usr/local/bin/psu-update-delta-orv3.py", line 94, in get_status_reg
    addr_b, uaddr = decode_modbus_address(addr)
  File "/usr/local/fbpackages/psu/modbus_update_helper.py", line 12, in decode_modbus_address
    line_addr = addr & 0xFF
TypeError: unsupported operand type(s) for &: 'bytes' and 'int'
```

https://fb.workplace.com/groups/openbmccomputestorageqa/posts/2838244226574995

Test Plan: doitlive

Reviewed By: waffle2k

Differential Revision: D109491697

fbshipit-source-id: 0d6feb4c552ab1cd06b73ee1a78e624975cb9770