fby3: GPv3: prevent sled-cycle when the other BMC is updating firmware (#1571)
Summary:
-There are 2 BMCs on a type 17 system. when one of them is updating the firmeare, the other one can perform sled-cycle.
In order to handle this case, BMC would add a `SLED Power Lock` sel to the other one to prevent the unexpected sled-cycle.
Also, BMC would set `critical activity` bit in BB CPLD register for insurance to avoid the SEL loss.
So, BMC will check both to decide to run sled-cycle or not.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1571

Test Plan:
-build code(pass)
-try to run sled-cycle when upading the firmware on the other side(pass)

-firmware update on SLOT3
root@bmc-oob:~# log-util all --print
2021 Apr 26 21:52:24 log-util: User cleared all logs
1    slot1    2021-04-26 21:53:18    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:53:16, Sensor: SYSTEM_STATUS (0x46), Event Data: (140300) Fan mode changed to manual mode by slot3 Assertion
1    slot1    2021-04-26 21:53:19    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:53:19, Sensor: SYSTEM_STATUS (0x46), Event Data: (606F00) SLED Power Lock Assertion
root@bmc-oob:~# i2cget -y 4 0x0f 0x10
0x00
root@bmc-oob:~# power-util sled-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# echo 0 > /tmp/cache_store/fru1_fwupd
root@bmc-oob:~# power-util sled-cycle
power lock flag is asserted, please make sure no firmware update is ongoing
If you still want to proceed, please clean the flag manually! ret=0, lock=1
ERROR: power-util fru[255] [SLED_CYCLE] failed
root@bmc-oob:~# i2cget -y 4 0x0f 0x10
0x01
root@bmc-oob:~# log-util all --print
2021 Apr 26 21:52:24 log-util: User cleared all logs
1    slot1    2021-04-26 21:53:18    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:53:16, Sensor: SYSTEM_STATUS (0x46), Event Data: (140300) Fan mode changed to manual mode by slot3 Assertion
1    slot1    2021-04-26 21:53:19    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:53:19, Sensor: SYSTEM_STATUS (0x46), Event Data: (606F00) SLED Power Lock Assertion
1    slot1    2021-04-26 21:53:38    ipmid            SEL Entry: FRU: 1, Record: Facebook Unified SEL (0xFB), GeneralInfo: POST(0x28), POST Failure Event: System PXE boot fail
0    all      2021-04-26 21:53:47    power-util       SLED_CYCLE starting...
1    slot1    2021-04-26 21:55:39    ipmid            SEL Entry: FRU: 1, Record: Facebook Unified SEL (0xFB), GeneralInfo: POST(0x28), POST Failure Event: System PXE boot fail
1    slot1    2021-04-26 21:55:55    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:55:55, Sensor: SYSTEM_STATUS (0x46), Event Data: (140301) Fan mode changed to auto mode by slot3 Assertion
1    slot1    2021-04-26 21:55:55    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:55:55, Sensor: SYSTEM_STATUS (0x46), Event Data: (60EF00) SLED Power Lock Deassertion

-firmware update on SLOT1
root@bmc-oob:~# log-util all --print
2021 Apr 26 21:54:02 log-util: User cleared all logs
1    slot1    2021-04-26 21:55:25    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:55:24, Sensor: SYSTEM_STATUS (0x46), Event Data: (140100) Fan mode changed to manual mode by slot1 Assertion
1    slot1    2021-04-26 21:55:28    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:55:27, Sensor: SYSTEM_STATUS (0x46), Event Data: (606F00) SLED Power Lock Assertion
0    all      2021-04-26 21:56:10    power-util       SLED_CYCLE starting...
1    slot1    2021-04-26 21:58:03    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:58:02, Sensor: SYSTEM_STATUS (0x46), Event Data: (140101) Fan mode changed to auto mode by slot1 Assertion
1    slot1    2021-04-26 21:58:03    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2021-04-26 21:58:03, Sensor: SYSTEM_STATUS (0x46), Event Data: (60EF00) SLED Power Lock Deassertion
root@bmc-oob:~# power-util sled-cycle
packet_write_wait: Connection to 192.168.88.246 port 22: Broken pipe

Reviewed By: zhdaniel12

fbshipit-source-id: cfddd7c661