GTI: fix retimer abnormal assert/deassert event when boots up
Summary:
# Description

Currently, we rebind the mux driver when PERST is asserted. But when BMC boots up, gpiod starts up later than sensord. It cause there has a little period of time, sensord can't read retimer health sensors because driver doesn't probe. So, we add a retry to fix this.

Fail log:
Fri Mar 9 04:35:47 2018: Setup sensor monitoring... done.
Fri Mar 9 04:35:47 2018: Setup gpio monitoring for Grandteton

2018 Mar 9 04:35:49 bmc-oob. kern.info inspirationpoint-v2023.32.0.Test: kernel: [64.225816] pca954x 6-0070: registered 8 multiplexed busses for I2C switch pca9548

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4041

Test Plan:
1. Update the bad retimer FW
root@bmc-oob:~# fw-util mb --update retimer0 /tmp/pt516_x16_bad_image.ihx 04:46:10 ERROR /usr/src/debug/libretimer/2.14-r1/aries_misc.c:3585: Error: '/tmp/pt516_x16_bad_image.ihx', line: 1
04:46:10 ERROR /usr/src/debug/libretimer/2.14-r1/aries_misc.c:3585: Error: '/tmp/pt516_x16_bad_image.ihx', line: 34
04:46:10 INFO /usr/src/debug/libretimer/2.14-r1/aries_api.c:757: Starting Main Micro assisted EEPROM write
04:46:10 INFO /usr/src/debug/libretimer/2.14-r1/aries_api.c:775: Slv: 0x50, Reg: 0x0000
04:46:13 INFO /usr/src/debug/libretimer/2.14-r1/aries_api.c:775: Slv: 0x50, Reg: 0x2000 .
.
04:47:23 INFO /usr/src/debug/libretimer/2.14-r1/aries_api.c:1347: Ending verify
04:47:23 INFO /usr/src/debug/libretimer/2.14-r1/aries_api.c:1351: EEPROM verify time: 19.00 seconds
To active the upgrade of Retimer, please perform 'power-util mb cycle'
Upgrade of mb : retimer0 succeeded

2. Perform DC cycle
root@bmc-oob:~# power-util mb cycle
Power cycling fru 1...

3. Check retimer health
root@bmc-oob:~#  retimer-util mb health 0
04:51:30 WARN /usr/src/debug/libretimer/2.14-r1/aries_api.c:209: Code Load reg unexpected. Not all modules are loaded
04:51:30 WARN /usr/src/debug/libretimer/2.14-r1/aries_api.c:278: No Main Micro Heartbeat heartbeat: bad
code load status: bad

4. Check if the unhealthy event is logging
root@bmc-oob:~# log-util all --print
1 mb 2018-03-09 04:50:03 sensord ASSERT: MB_RETIMER0_HEALTH - FRU: 1

5. Update official retimer FW

6. Check if the health event is logging
1 mb 2018-03-09 05:06:35 sensord DEASSERT: MB_RETIMER0_HEALTH - FRU: 1

Reviewed By: amithash

Differential Revision: D48834653

fbshipit-source-id: 2c856d139fd4746ba410db9b8e2edb3dc88d9d33