cmm rest-api: minor fix in rest_firmware.py
Summary:
In order to get version number from "cpld_ver" and "cpld_sub_ver" files,
we just need to read the first line (instead of whole file), because
the remaining lines are usage documents for debugging purpose.

Test Plan:
1) rest_firmware.py prints following before the fix:

Traceback (most recent call last):
  File "./rest_firmware.py", line 65, in <module>
    print('{}'.format(get_firmware_info()))
  File "./rest_firmware.py", line 56, in get_firmware_info
    firmware_info['SYS_CPLD'] = _get_syscpld_info()
  File "./rest_firmware.py", line 43, in _get_syscpld_info
    return _firmware_json(ver, sub_ver)
  File "./rest_firmware.py", line 34, in _firmware_json
    'version': int(ver, int_base),
ValueError: invalid literal for int() with base 16: '0x2\n\nNote:\n\nBit[5:0] @ register 0x1, register value 0x2\n'

2) rest_firmware.py prints following after the fix:

{'FCB3_CPLD': {'version': 3, 'sub_version': 0}, 'FCB1_CPLD': {'version': 3, 'sub_version': 0}, 'FCB4_CPLD': {'version': 3, 'sub_version': 0}, 'SYS_CPLD': {'version': 2, 'sub_version': 3}, 'FCB2_CPLD': {'version': 3, 'sub_version': 0}}

Reviewed By: mikechoifb

fbshipit-source-id: 96cf019cf