tests2: fbgc: rest-api: delete test point "pwr_server_last_state" (#1874)
Summary:
The power policy LPS is deprecated on Grand Canyon, thus, delete test point "pwr_server_last_state".

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1874

Test Plan:
1. Check test_rest_endpoints can successful.
- Before update
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --run-test  tests.fbgc.test_rest_endpoint.RestEndpointTest.test_rest_endpoints
test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) ...
======================================================================
FAIL: test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) (attrib='pwr_server_last_state')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 157, in verify_endpoint_attributes
    msg="endpoint {} missing attrib {}".format(endpointname, attrib),
AssertionError: 'pwr_server_last_state' not found in '{"Information": {"system_identify_server": "off", "server_boot_order": "0100090203ff", "server_por_cfg": "on", "sysfw_ver_server": "0", "ntp_server": "", "server_sel_error": "1", "server_sensor_health": "1"}, "Actions": ["update"], "Resources": []}' : endpoint /api/server/config missing attrib pwr_server_last_state

----------------------------------------------------------------------
Ran 1 test in 15.354s

FAILED (failures=1)

- After update
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --run-test  tests.fbgc.test_rest_endpoint.RestEndpointTest.test_rest_endpoints
test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 14.860s

OK

Reviewed By: peterdelevoryas

fbshipit-source-id: 4b648ed599