common: If all fan fail, prevent server from powering on (#1815)
Summary:
If all fan fail, prevent server from powering on for Yv2/GPv2 platform.
Only force power on will not be blocked under all fans fail condition.
By the way, always force power on after force 12V-on regardless of power policy.

Test case:
1.If all fans fail before sled on, bmc will not power on any servers.
Also, after fscd detect fan fail condition, all slots will 12V-off.
root@bmc-oob:~# log-util all --print
FRU# FRU_NAME TIME_STAMP             APP_NAME         MESSAGE
2020 Jun 30 01:47:07 log-util: User cleared all logs

0    all      2020-06-30 01:47:07    power-util       SLED_CYCLE
starting...
2    slot2    2020-06-30 01:48:29    power-util       SERVER_POWER_ON
fail for FRU: 2 due to fan fail
4    slot4    2020-06-30 01:48:30    power-util       SERVER_POWER_ON
fail for FRU: 4 due to fan fail
6    nic      2020-06-30 01:48:49    ncsid            FRU: 6 NIC AEN
Supported: 0x70007, AEN Enable Mask=0x70007
0    all      2020-06-30 01:48:50    healthd          ASSERT: Verified
boot failure (3,35)
0    all      2020-06-30 01:48:50    healthd          Verified boot
failure reason: U-Boot FIT did not contain the /keys node
0    all      2020-06-30 01:48:50    healthd          SLED Powered OFF
at Tue Jun 30 01:47:07 2020
0    all      2020-06-30 01:48:50    healthd          SLED Powered ON at
Tue Jun 30 01:47:33 2020
5    spb      2020-06-30 01:49:12    sensord          ASSERT: Lower
Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 0.00 RPM,
thresh_val: 500.00 RPM, snr: SP_FAN0_TACH
5    spb      2020-06-30 01:49:12    sensord          ASSERT: Lower
Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 0.00 RPM,
thresh_val: 500.00 RPM, snr: SP_FAN1_TACH
5    spb      2020-06-30 01:49:19    fscd             FRU: 5, 12V-off
all slots due to both fan fail
0    all      2020-06-30 01:49:19    fscd             2 fans failed
0    all      2020-06-30 01:49:19    fscd             Fan 0 dead, 0 RPM
0    all      2020-06-30 01:49:19    fscd             Fan 1 dead, 0 RPM
5    spb      2020-06-30 01:49:56    sensord          ASSERT: Upper Non
Critical threshold - raised - FRU: 5, num: 0xD0 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN0_PWM
5    spb      2020-06-30 01:49:56    sensord          ASSERT: Upper
Critical threshold - raised - FRU: 5, num: 0xD0 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN0_PWM
5    spb      2020-06-30 01:49:56    sensord          ASSERT: Upper Non
Critical threshold - raised - FRU: 5, num: 0xD1 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN1_PWM
5    spb      2020-06-30 01:49:56    sensord          ASSERT: Upper
Critical threshold - raised - FRU: 5, num: 0xD1 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN1_PWM

2. Under all fans fail condition, user only power on server by force
option:

root@bmc-oob:~# power-util slot2 status
Power status for fru 2 : OFF (12V-OFF)
root@bmc-oob:~# power-util slot2 12V-on
12V Powering fru 2 to ON state...
Fail to 12V Powering fru 2 to ON state due to fan fail.
ERROR: power-util fru[2] [12V_ON] failed
root@bmc-oob:~# power-util slot2 --force 12V-on
12V Powering fru 2 to ON state...
root@bmc-oob:~# log-util all --print
FRU# FRU_NAME TIME_STAMP             APP_NAME         MESSAGE
2020 Jun 30 01:58:17 log-util: User cleared all logs

5    spb      2020-06-30 01:58:18    sensord          ASSERT: Lower
Critical threshold - raised - FRU: 5, num: 0x46 curr_val: 0.00 RPM,
thresh_val: 500.00 RPM, snr: SP_FAN0_TACH
5    spb      2020-06-30 01:58:18    sensord          ASSERT: Upper Non
Critical threshold - raised - FRU: 5, num: 0xD0 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN0_PWM
5    spb      2020-06-30 01:58:19    sensord          ASSERT: Upper
Critical threshold - raised - FRU: 5, num: 0xD0 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN0_PWM
5    spb      2020-06-30 01:58:19    sensord          ASSERT: Lower
Critical threshold - raised - FRU: 5, num: 0x47 curr_val: 0.00 RPM,
thresh_val: 500.00 RPM, snr: SP_FAN1_TACH
5    spb      2020-06-30 01:58:19    sensord          ASSERT: Upper Non
Critical threshold - raised - FRU: 5, num: 0xD1 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN1_PWM
5    spb      2020-06-30 01:58:19    sensord          ASSERT: Upper
Critical threshold - raised - FRU: 5, num: 0xD1 curr_val: 100.00 %,
thresh_val: 100.00 %, snr: SP_FAN1_PWM
2    slot2    2020-06-30 01:58:40    power-util       SERVER_12V_ON fail
for FRU: 2 due to fan fail
1    slot1    2020-06-30 01:59:13    power-util       PAIR_12V_ON
successful for FRU: 1
2    slot2    2020-06-30 01:59:13    power-util       SERVER_12V_ON
successful for FRU: 2
2    slot2    2020-06-30 01:59:16    ipmid            SEL Entry: FRU: 2,
Record: Standard (0x02), Time: 2020-06-30 01:59:16, Sensor:
SYSTEM_STATUS (0x10), Event Data: (07FFFF) Platform_Reset Assertion
2    slot2    2020-06-30 01:59:17    gpiod            FRU: 2, System
powered ON
2    slot2    2020-06-30 01:59:20    ipmid            SEL Entry: FRU: 2,
Record: Standard (0x02), Time: 2020-06-30 01:59:20, Sensor:
SYSTEM_STATUS (0x10), Event Data: (07FFFF) Platform_Reset Deassertion
2    slot2    2020-06-30 01:59:20    ipmid            SEL Entry: FRU: 2,
Record: Standard (0x02), Time: 2020-06-30 01:59:20, Sensor:
SYSTEM_STATUS (0x10), Event Data: (07FFFF) Platform_Reset Assertion

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1815

Reviewed By: amithash

fbshipit-source-id: 5265bbecb2