netlakemtp: Revise vmalloc size for spi flash (#2190)
Summary:
- Revise vmalloc size to 640M from 384M for spi flash

Dependency: https://github.com/facebookexternal/openbmc.wiwynn/issues/2152

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/2190

Test Plan:
- BIOS update - pass
root@bmc-oob:~# fw-util server --force --update bios NLICXBU_EOM_ON_CMD.bin
ERROR: unable to put ME in recovery mode!
Flashing to device: /dev/mtd13
Erasing block: 8192/8192 (100%)
Writing kb: 32768/32768 (100%)
Verifying kb: 32768/32768 (100%)
Force upgrade of server : bios succeeded

Reviewed By: GoldenBug

fbshipit-source-id: 5aecc4f07fe0480868d21386f751a7437d796613