celesticabmc: bios_update: fix issue cannot use read/erase operand
Summary:
# Description
celesticabmc: bios_update: modify script to check file size for only write operand

# Motivation
To fix issue, cannot use read/erase operand
because from unnecessary checking file size with all operand

```
root@bmc:~# service_mode.sh on
Enable service mode
root@bmc:~# bios_update.sh read bios.bin
Error: File not found.
Cleanup: Execution failed or interrupted (Status 1)
root@bmc:~#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1941

Test Plan:
validate in Anacapa 87.5 EVT2
```
root@bmc:~# service_mode.sh on
Enable service mode
root@bmc:~# bios_update.sh read bios.bin
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
exporting gpio (aspeed-gpio, GPIOG4), shadow=BMC_IOB_FLASH_SEL
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
/usr/local/bin/spi-utils.sh: line 63: echo: write error: No such device
Reading COME_BIOS to bios.bin...
flashrom v1.6.0 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (65536 kB, Programmer-specific) on linux_mtd.
Reading flash... done.
root@bmc:~# ls -l
-rw-r--r--    1 root     root      67108864 Mar 14 00:04 bios.bin
root@bmc:~#
```

Reviewed By: mikechoifb

Differential Revision: D115026478

Pulled By: ezeob002

fbshipit-source-id: 85d1b8ee0dbbf36271ae2cacf1c69ed0555e4146