elbert: add CIT test to verify flashrom -L
Summary:
# Description

Adds a CIT test to verify `flashrom -L` on Elbert.

# Motivation

Recently, flashrom broke on Elbert after upgrading to v1.5.1 as the existing patches did not apply cleanly. This CIT test will allow us to flag future breakages more easily.

This should merge after https://github.com/facebookexternal/openbmc.arista/issues/429, which fixes flashrom on Elbert for version v1.5.1.

X-link: https://github.com/facebookexternal/openbmc.arista/pull/430

Test Plan:
Verified that the CIT test catches the issue addressed in https://github.com/facebookexternal/openbmc.arista/issues/429:
```
root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --platform=elbert --run-test tests.elbert.test_flashrom_devices.FlashromSupportedDevicesTest.test_devices_supported
test_flashrom_chips_supported (tests.elbert.test_flashrom_devices.FlashromSupportedDevicesTest.test_devices_supported) ... FAIL

======================================================================
FAIL: test_flashrom_chips_supported (tests.elbert.test_flashrom_devices.FlashromSupportedDevicesTest.test_devices_supported)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/elbert/test_flashrom_devices.py", line 56, in test_devices_supported
    self.assertTrue(
    ~~~~~~~~~~~~~~~^
        device_supported_match,
        ^^^^^^^^^^^^^^^^^^^^^^^
        "{} flash device not supported".format(device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
AssertionError: None is not true : GD25LQ256D flash device not supported

----------------------------------------------------------------------
Ran 1 test in 0.327s

FAILED (failures=1)
```

The new CIT test has been regression tested in our lab against the supported flash devices. Example output:
```
root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --platform=elbert --run-test tests.elbert.test_flashrom_devices.FlashromSupportedDevicesTest.test_devices_supported�test_devices_supported (tests.elbert.test_flashrom_devices.FlashromSupportedDevicesTest.test_devices_supported) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.212s

OK
```

Reviewed By: ezeob002

Differential Revision: D86696534

Pulled By: tao-ren

fbshipit-source-id: 12f31e0bff269e7492c2f44149e317f6b718ecb9