ELBERT: adds test_show_tech CIT test (#210)
Summary:
Adds a new CIT test to sanity check the show_tech.py script and basic switch configuration.

The test runs show_tech.py, then parses the output to verify:
- Switchcard power is good
- SCM, SMB, SMB_CPLD, and FAN FPGA versions can be read
- PIM FPGA versions can be read (uninserted PIMs are ignored)

## Testing

The new test has been tested over 200 iterations, with no failures across 12 Elbert systems in our regression testbed.

Example output:
```
root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --platform=elbert -r tests.elbert.test_show_tech
test_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest) ... ok
test_pim_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest) ... ok
test_smb_powergood_status (tests.elbert.test_show_tech.ShowTechTest) ... ok

----------------------------------------------------------------------
Ran 3 tests in 9.203s

OK
```

The new test was also run against the recent OpenBMC image with the pim8ddm voltage regression; the test catches the error when the PIM FPGA fails to load correctly:
```
root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --platform=elbert -r tests.elbert.test_show_tech
test_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest) ... ok
test_pim_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest) ... FAIL
test_smb_powergood_status (tests.elbert.test_show_tech.ShowTechTest) ... ok

======================================================================
FAIL: test_pim_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/elbert/test_show_tech.py", line 91, in test_pim_fpga_version_detected
    "PIM{} FPGA version not detected".format(pim)
AssertionError: <re.Match object; span=(756, 783), match='PIM 7: VERSION_NOT_DETECTED'> is not false : PIM7 FPGA version not detected

----------------------------------------------------------------------
Ran 4 tests in 16.708s

FAILED (failures=1)
```

The test also fails if any of the SCM/SMB/FAN FPGAs aren't loaded:
```
root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --platform=elbert -r tests.elbert.test_show_tech
test_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest) ... FAIL
test_pim_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest) ... ok
test_smb_powergood_status (tests.elbert.test_show_tech.ShowTechTest) ... ok

======================================================================
FAIL: test_fpga_version_detected (tests.elbert.test_show_tech.ShowTechTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/elbert/test_show_tech.py", line 80, in test_fpga_version_detected
    "{} version not detected".format(fpga)
AssertionError: <re.Match object; span=(715, 728), match='FAN_FPGA: 0.0'> is not false : FAN_FPGA version not detected

----------------------------------------------------------------------
Ran 4 tests in 10.443s

FAILED (failures=1)
```

Pull Request resolved: https://github.com/facebookexternal/openbmc.arista/pull/210

Reviewed By: binhuang00

fbshipit-source-id: 79b069acca