fby2: fby2-sensors: add missing -lrt
Summary:
Observed the following compile error due to changes in other library's
linking structure.  shm_open is used directly by the package, so add it
to the link flags in the makefile.

```
.../build-fbnd/tmp/work/armv6-fb-linux-gnueabi/fby2-sensors/0.1-r1/recipe-sysroot/usr/lib/libfby2_sensor.so: undefined reference to `shm_open'
```

Test Plan: Build passes CIT.

Reviewed By: sammyblueeyes

fbshipit-source-id: 879ecbac1a