[openbmc.quanta][PR] tpm2_tools: Fix strdup() with NULL pointer if tools can't find TCTI l… (#1737)
Summary:
…ibrary
find_tcti_default() will probe the TCTI library and return its name if found, otherwise, return NULL.
But tcti_get_config() did not handle with the case of NULL pointer and call strdup() with it, which will cause segmentation fault.

The upstream of tpm2_tools had modified the implementation to probe the TCTI library, so we only need to apply this fix to v3.2.0

// The case if can't find TCTI library
// Before applying fix
root@bmc-oob:~# tpm2_getcap -h
Segmentation fault

// After applying fix
root@bmc-oob:~# tpm2_getcap -h
ERROR: Requested no tcti, but tool requires TCTI.
Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1737

Test Plan: Build pass and test on fbep

Reviewed By: benwei13

fbshipit-source-id: 067f5f6811