GTI: enable ADDC dump
Summary:
1. get CPUID when POST complete
2. gpiod detect APML_CPUx_ALERT and check ras_status to trigger dump

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3913

Test Plan:
Build and test pass on GTI

note: agesa code for PCIe dump not yet in current BIOS, so there is some parsing error due to PCIe dump portion

(1) CPU0 nbio error:
Start logging at /home/cosmo2/NDA-Genoa_OOB_Crashdump_v1.7/amd-crashdump-analyzer-tool/Crashdump_Analyzer_NDA_1.7/logs/2023_06_05_14H_53M_26S.log Crashdump analyzer version : 1.7

\############################################################
\##                    Socket 0, bank 0                    ##
\############################################################
+---------------------+--------------------------------------------------------------------------------------+
| Index               | Status                                                                               |
|---------------------+--------------------------------------------------------------------------------------|
| Bank                | nbio_p0                                                                              |
| Status Register     | nbio                                                                                 |
| PCC                 | 1                                                                                    |
| UC                  | 1                                                                                    |
| TCC                 | 1                                                                                    |
| Deferred            | 0                                                                                    |
| Synd_V              | 1                                                                                    |
| Syndrome            | Structure ID : 1                                                                     |
|                     | Group ID : 7                                                                         |
| Addr_V              | 0                                                                                    |
| Error Code          | 0000000100001011                                                                     |
| Error Code Decode   | Type : Memory               ADDC version:addc_0.1                                                         |
|                     | TT (Transaction Type) : 10  --> Generic                                              |
|                     | LL (cache level) : 11  --> LG: Generic                                               |
|                     | RRRR (Memory Transaction Type) : 0000 --> Generic                                    |
| Errorcode ext       | 0                                                                                    |
| Errorcode ext Type  | EccParityError                                                                       |
| Error description   | ECC or Parity error.                                                                 |
| MCA ERROR Serverity | Uncorrected system fatal error. Action required.                                     |
|                     |  A hardwareuncorrected error has corrupted system state.                             |
|                     |  The error is fatal to the system and the system processing must be terminated.      |
| -----------------   | ------------------------------------------------------------------------------------ |
+---------------------+--------------------------------------------------------------------------------------+
debug log no: 1 doesn't have valid block ID
Traceback (most recent call last):
  File "cdump_analyzer.py", line 245, in <module>
    analyze_all(param.filepath, param.reportpath, param.summary)
  File "cdump_analyzer.py", line 216, in analyze_all
    data_dict = cda._analyze_cper(lines, summary)
  File "/home/cosmo2/NDA-Genoa_OOB_Crashdump_v1.7/amd-crashdump-analyzer-tool/Crashdump_Analyzer_NDA_1.7/data/Program1/Gen1/CDA_1_7/cdump_analyzer_lib.py", line 623, in _analyze_cper
    data_dict = _dbg_log_decode(lines, data_dict, socket)
  File "/home/cosmo2/NDA-Genoa_OOB_Crashdump_v1.7/amd-crashdump-analyzer-tool/Crashdump_Analyzer_NDA_1.7/data/Program1/Gen1/CDA_1_7/cdump_analyzer_lib.py", line 477, in _dbg_log_decode
    header = lines[location]
IndexError: list index out of range

(2) CPU1 nbio error:
\############################################################
\##                    Socket 1, bank 0                    ##
\############################################################
+---------------------+--------------------------------------------------------------------------------------+
| Index               | Status                                                                               |
|---------------------+--------------------------------------------------------------------------------------|
| Bank                | nbio_p1                                                                              |
| Status Register     | nbio                                                                                 |
| PCC                 | 1                                                                                    |
| UC                  | 1                                                                                    |
| TCC                 | 1                                                                                    |
| Deferred            | 0                                                                                    |
| Synd_V              | 1                                                                                    |
| Syndrome            | Structure ID : 1                                                                     |
|                     | Group ID : 7                                                                         |
| Addr_V              | 0                                                                                    |
| Error Code          | 0000000100001011                                                                     |
| Error Code Decode   | Type : Memory                                                                        |
|                     | TT (Transaction Type) : 10  --> Generic                                              |
|                     | LL (cache level) : 11  --> LG: Generic                                               |
|                     | RRRR (Memory Transaction Type) : 0000 --> Generic                                    |
| Errorcode ext       | 0                                                                                    |
| Errorcode ext Type  | EccParityError                                                                       |
| Error description   | ECC or Parity error.                                                                 |
| MCA ERROR Serverity | Uncorrected system fatal error. Action required.                                     |
|                     |  A hardwareuncorrected error has corrupted system state.                             |
|                     |  The error is fatal to the system and the system processing must be terminated.      |
| -----------------   | ------------------------------------------------------------------------------------ |
+---------------------+--------------------------------------------------------------------------------------+
debug log no: 1 doesn't have valid block ID
Traceback (most recent call last):
  File "cdump_analyzer.py", line 245, in <module>
    analyze_all(param.filepath, param.reportpath, param.summary)
  File "cdump_analyzer.py", line 216, in analyze_all
    data_dict = cda._analyze_cper(lines, summary)
  File "/home/cosmo2/NDA-Genoa_OOB_Crashdump_v1.7/amd-crashdump-analyzer-tool/Crashdump_Analyzer_NDA_1.7/data/Program1/Gen1/CDA_1_7/cdump_analyzer_lib.py", line 623, in _analyze_cper
    data_dict = _dbg_log_decode(lines, data_dict, socket)
  File "/home/cosmo2/NDA-Genoa_OOB_Crashdump_v1.7/amd-crashdump-analyzer-tool/Crashdump_Analyzer_NDA_1.7/data/Program1/Gen1/CDA_1_7/cdump_analyzer_lib.py", line 477, in _dbg_log_decode
    header = lines[location]
IndexError: list index out of range

# Description

Support ADDC

# Motivation

Collect the dump when CPU error occurs

ADDC version: addc_0.1

ADDC Validation Cases:
ADDC-TEST-03
ADDC-TEST-04
ADDC-TEST-07
ADDC-TEST-08
ADDC-TEST-18

Reviewed By: williamspatrick

Differential Revision: D46486221

Pulled By: amithash

fbshipit-source-id: 439f807df227c6ced452edc779f77d347c40dfee