fw-util: move VrComponent to common (#1619)
Summary:
1. move VrComponent to common to be used by fbal, fbsp, and fbep.
2. separate VR components to update VR indivisually
Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1619

Test Plan:
Build and test pass on fbal, fbsp, and fbep

Example on fbal:
(1) display VR version:
root@bmc-oob:~# fw-util vr --version
VR_CPU0_VCCIN/VCCSA Version: 3856
VR_CPU0_VCCIO Version: AA0A
VR_CPU0_VDDQ_ABC Version: F47C
VR_CPU0_VDDQ_DEF Version: 8567
VR_CPU1_VCCIN/VCCSA Version: ED77
VR_CPU1_VCCIO Version: 7F2B
VR_CPU1_VDDQ_ABC Version: 215D
VR_CPU1_VDDQ_DEF Version: D02E
VR_PCH_PVNN/P1V05 Version: BCBA1E93

(2) specify mismatched component vs. VR file: cannot update
root@bmc-oob:~# fw-util vr --update cpu0_vccin /tmp/F0C_CPU1_VCCIN_VCCSA_2B83_20190624.csv
ERROR: VR Firmware update failed!
Upgrade of vr : cpu0_vccin failed

(3) specify correct component vs. VR file:
root@bmc-oob:~# fw-util vr --update cpu1_vccin /tmp/F0C_CPU1_VCCIN_VCCSA_2B83_20190624.csv
Update VR: VR_CPU1_VCCIN/VCCSA
File CRC : 2B83
updated: 100 %
Upgrade of vr : cpu1_vccin succeeded

(4) check updated VR version:
root@bmc-oob:~# fw-util vr --version
VR_CPU0_VCCIN/VCCSA Version: 3856
VR_CPU0_VCCIO Version: AA0A
VR_CPU0_VDDQ_ABC Version: F47C
VR_CPU0_VDDQ_DEF Version: 8567
VR_CPU1_VCCIN/VCCSA Version: 2B83
VR_CPU1_VCCIO Version: 7F2B
VR_CPU1_VDDQ_ABC Version: 215D
VR_CPU1_VDDQ_DEF Version: D02E
VR_PCH_PVNN/P1V05 Version: BCBA1E93

(5) update back to original version:
root@bmc-oob:~# fw-util vr --update cpu1_vccin /tmp/TPS53688\ \@\ PMBus\ Address\ 112d\ Project_ED77_F0C_CPU1_VCCIN_VCCSA_20191022.csv
Update VR: VR_CPU1_VCCIN/VCCSA
File CRC : ED77
updated: 100 %
Upgrade of vr : cpu1_vccin succeeded

root@bmc-oob:~# fw-util vr --version cpu1_vccin
VR_CPU1_VCCIN/VCCSA Version: ED77

root@bmc-oob:~# fw-util
USAGE: fw-util all|FRU --version [all|COMPONENT]
       fw-util FRU --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --force --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --dump [--]COMPONENT IMAGE_PATH
FRU        : Components
---------- : ----------
bmc        : bmc rom tpm
cpld       : glb_cpld mod_cpld pfr_cpld
mb         : bios me
nic        : nic0 nic1
ocpdbg     : mcu mcubl
pdb        : cm cmbl
vr         : cpu0_vccin cpu0_vccio cpu0_vddq_abc cpu0_vddq_def cpu1_vccin cpu1_vccio cpu1_vddq_abc cpu1_vddq_def pch_pvnn

Get VR Version on fbsp:
root@bmc-oob:~# fw-util vr --version
VR_CPU0_VCCIN/VCCSA Version: 1B3D
VR_CPU0_VCCIO Version: 8901
VR_CPU0_VDDQ_ABC Version: 10F0
VR_CPU0_VDDQ_DEF Version: 145A
VR_CPU1_VCCIN/VCCSA Version: 8E1C
VR_CPU1_VCCIO Version: 5C20
VR_CPU1_VDDQ_ABC Version: BCDF
VR_CPU1_VDDQ_DEF Version: 4113
VR_PCH_PVNN/P1V05 Version: 183441AE

root@bmc-oob:~# fw-util
USAGE: fw-util all|FRU --version [all|COMPONENT]
       fw-util FRU --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --force --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --dump [--]COMPONENT IMAGE_PATH
FRU        : Components
---------- : ----------
bmc        : bmc fscd rom tpm
mb         : bios cpld me
nic        : nic0 nic1
ocpdbg     : mcu mcubl
vr         : cpu0_vccin cpu0_vccio cpu0_vddq_abc cpu0_vddq_def cpu1_vccin cpu1_vccio cpu1_vddq_abc cpu1_vddq_def pch_pvnn

Get VR Version on fbep:
root@bmc-oob:~# fw-util vr --version
VR_P0V8_VDD0 Version: 0x31
VR_P0V8_VDD1 Version: 0x31
VR_P0V8_VDD2 Version: 0x31
VR_P0V8_VDD3 Version: 0x31
VR_P1V0_AVD0 Version: 0x30
VR_P1V0_AVD1 Version: 0x30
VR_P1V0_AVD2 Version: 0x30
VR_P1V0_AVD3 Version: 0x30

root@bmc-oob:~# fw-util
USAGE: fw-util all|FRU --version [all|COMPONENT]
       fw-util FRU --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --force --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --dump [--]COMPONENT IMAGE_PATH
FRU        : Components
---------- : ----------
bmc        : bmc fscd rom tpm
mb         : cpld pax0-bl2 pax0-cfg pax0-flash pax0-img pax1-bl2 pax1-cfg pax1-flash pax1-img pax2-bl2 pax2-cfg pax2-flash pax2-img pax3-bl2 pax3-cfg pax3-flash pax3-img pfr_cpld
ocpdbg     : mcu mcubl
vr         : p0v8_vdd0 p0v8_vdd1 p0v8_vdd2 p0v8_vdd3 p1v0_avd0 p1v0_avd1 p1v0_avd2 p1v0_avd3

Reviewed By: benwei13

fbshipit-source-id: 6921f6111e