github: meta-aspeed: update linux PV to 5.6.14
Summary:
Observing failure in our sstate-cache build.

```
$ cat log.do_kernel_version_sanity_check
DEBUG: Executing shell function do_kernel_version_sanity_check
ERROR: Package Version (5.6.3) does not match of kernel being built (5.6.14). Please update the PV variable to match the kernel source or set KERNEL_VERSION_SANITY_SKIP="1" in your recipe.
```

Update linux PV to match code, which is now at 5.6.14.

Test Plan: NA.

Reviewed By: tao-ren

fbshipit-source-id: f8bd05b6d0