fuji: RestAPI: Rest API functionality broken (#1438)
Summary:
Issue description:
RestAPI functionality was broken after following commit was merged: https://github.com/facebookexternal/openbmc.celestica/commit/54ef16e1fa66e94704404ea23d1996fab7e89982

Issue Logs:
CIT Errors:
ERROR: test_endpoint_api (tests.fuji.test_rest_endpoint.RestEndpointTest)
ERROR: test_endpoint_api_fan_present (tests.fuji.test_rest_endpoint.RestEndpointTest)
ERROR: test_endpoint_api_psu_present (tests.fuji.test_rest_endpoint.RestEndpointTest)
ERROR: test_endpoint_api_scm_present (tests.fuji.test_rest_endpoint.RestEndpointTest)
ERROR: test_endpoint_api_sys (tests.fuji.test_rest_endpoint.RestEndpointTest)
ERROR: test_watchdog_kick (tests.fuji.test_watchdog.WatchdogTest)
FAIL: test_installed_processes (tests.fuji.test_process_running.ProcessRunningTest) (process='rest.py')

RestAPI curl commands failures:
root@bmc-oob:~# time curl -g http://10.208.140.159:8080/api/sys/mb/fruid
curl: (7) Failed to connect to 10.208.140.159 port 8080: Connection refused
real 0m0.025s
user 0m0.010s
sys 0m0.011s

root@bmc-oob:~# time curl -g http://[2001:1:2:0:2e0:ecff:feff:5f43]:8080/api
curl: (7) Failed to connect to 2001:1:2:0:2e0:ecff:feff:5f43 port 8080: Connection refused
real 0m0.021s
user 0m0.018s
sys 0m0.001s

Root Cause: "rest_pim_present.py" file was introduced as a part of the above mentioned commit, respective file details were not added in the "rest-api_0.1.bbappend" file. This resulted in restAPI service failing, hence causing the issue.

Dec 31 16:01:24 bmc-oob. rest.py[1231]: ModuleNotFoundError: No module named 'rest_pim_present'
Dec 31 16:01:24 bmc-oob. systemd[1]: restapi.service: Main process exited, code=exited, status=1/FAILURE
..
-- An ExecStart= process belonging to unit restapi.service has exited.
..
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 16:01:24 bmc-oob. systemd[1]: restapi.service: Failed with result 'exit-code'.
-- Subject: Unit failed
..
-- The unit restapi.service has entered the 'failed' state with result 'exit-code'.

---------------------------------------------------------------------------------------------------------------------------------------------

Fix Details: Added the "rest_pim_present.py" details to the "rest-api_0.1.bbappend" file.

Unit Test Logs:

CIT Logs:
[CIT_REST_Logs.txt](https://github.com/facebookexternal/openbmc.celestica/files/10506471/CIT_REST_Logs.txt)
CURL Logs:
[CURL_REST_Logs.txt](https://github.com/facebookexternal/openbmc.celestica/files/10506506/CURL_REST_Logs.txt)

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1438

Reviewed By: binhuang00

Differential Revision: D43074982

fbshipit-source-id: c2ceb2635f299b1e11508c3a74a64b149e87aeac