Do proper min memory calculations in case when image was pre-downloaded
Summary:
Pypartition doesn't take into account the case when image is already
pre-downloaded by other systems. This change introduces better memory
calculation.

First, we check if provided image path is a http url. If not then
assumes a local file path and tries to get the file size.

The tricky part here is error handling. If file is not found then simply
return 0 and let pypartition do the "normal" execution, should be safe
enough.

As for the python2 compatibility hack:
```
>>> os.stat("/tmp/xyz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 2] No such file or directory: '/tmp/xyz'

```

Test Plan:
Scuba: https://fburl.com/scuba/pb9uavq6

```
INFO:2019-12-10 06:35:21,793 Image size 23518 Kb
INFO:2019-12-10 06:35:21,813 Minimum memory needed for update is 37922 KiB
```

Also tested in the workflow context:

```
$ cows workflow-status --id 03768b63-0c90-44c8-aafc-03e5a314d7d7
...
parameters: '{"host": "rtptest005-oob.ftw3", "fbpkg_name": "openbmc.image.yosemite2:v2019.32.1", "pypartition_version": "11abd56"}'
...
  status: FinishStatus.SUCCEEDED
...
```

fbshipit-source-id: b530c0d91a