tests: Rewrite CPU utilization test to be more accurate
Summary:
Before this diff, `top` was used to estimate the CPU
utilization. Even though it was run twice, it didn't return a good
estimate because it calculated over an interval of 1s, and displaying
the command lines of all processes. This is evidenced by the fact that
the first run of top always shows a much higher utilization.

This diff computes the utilization directly using `/proc/stat` for
system utilization and `/proc/<pid>/stat` for process utilization. It
also changes the computation interval to 5s, which leads to much
smoother results.

The original algorithm made the test flaky at least on yamp.

Test Plan:
Successful run:
```
root@fboss310913715-oob:/run/tests2# python cit_runner.py --run-test tests.yamp.test_cpu_utilization.CpuUtilizationTest
test_cpu_utilization (tests.yamp.test_cpu_utilization.CpuUtilizationTest)
This test is ran a specific number of time ... ok

----------------------------------------------------------------------
Ran 1 test in 24.331s

OK
```

Failed run (when manually set the utilization threshold to 10%):
```
root@fboss310913715-oob:/run/tests2# python cit_runner.py --run-test tests.yamp.test_cpu_utilization.CpuUtilizationTest
test_cpu_utilization (tests.yamp.test_cpu_utilization.CpuUtilizationTest)
This test is ran a specific number of time ... FAIL

======================================================================
FAIL: test_cpu_utilization (tests.yamp.test_cpu_utilization.CpuUtilizationTest)
This test is ran a specific number of time
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_cpu_utilization_test.py", line 116, in test_cpu_utilization
    self.assertGreaterEqual(good_runs, self.result_threshold, debug_info)
AssertionError: 0 not greater than or equal to 2 : Expected CPU utilization <= 10%
Actual utilizations for each run (without excluded processes (used in test), with excluded processes (for info)):
27%   28%
34%   35%
30%   30%
30%   30%

----------------------------------------------------------------------
Ran 1 test in 23.179s

FAILED (failures=1)
```

Reviewed By: Scott8440

Differential Revision: D61511902

fbshipit-source-id: 378656991f0f572294b96d4ef7557d222499c666