Static type checking for the REST codebase
Summary: Enable static typechecking on the REST codebase using mypy

Test Plan:
Running ptests now executes mypy
```
openbmc git:(linttype) ? ./tests2/ptest-runner rest-api
Found 511 recipes of which 14 define unit-tests
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../meta-facebook/recipes-utils/mac-util/mac-util_0.1.bb: Unable to get checksum for mac-util SRC_URI entry eeprom.h: file could not be found
Parsing recipes: 100% |########################################################################################################################################################| Time: 0:00:15
WARNING: No recipes available for:
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby3-image.bbappend
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby35-image.bbappend
Initialising tasks: 100% |#####################################################################################################################################################| Time: 0:00:03
START: ptest-runner
2021-12-06T08:16
BEGIN: /usr/lib/rest-api/ptest
[UNIT TESTS]
/usr/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py:110: DeprecationWarning: "coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def handler_wrapper(*args, **kwargs):
/usr/lib/python3.8/site-packages/aiohttp/helpers.py:141: DeprecationWarning: Task.current_task() is deprecated, use asyncio.current_task() instead
  task = asyncio.Task.current_task(loop=loop)
.Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:57> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b83d0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:57> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b84d8>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:57> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b8718>()]>>
./usr/local/fbpackages/rest-api/test_async_ratelimiter.py:87: RuntimeWarning: coroutine 'TestRatelimiterWorks.__assert_normal_request' was never awaited
  self.__assert_normal_request("GET", "agent2")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:58> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b8748>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:58> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b86e8>()]>>
.Task was destroyed but it is pending!
task: <Task pending name='Task-53' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:57> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b85f8>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-55' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:57> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf60b8850>()]>>
............../usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............../usr/lib/python3.8/site-packages/aiohttp/web_server.py:44: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  yield from asyncio.gather(*coros, loop=self._loop)
...................s...../usr/lib/python3.8/linecache.py:171: ResourceWarning: unclosed file <_io.FileIO name='/tmp/tmplhck9zjq' mode='ab' closefd=True>
  get_source = getattr(loader, 'get_source', None)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'
............................................................
----------------------------------------------------------------------
Ran 118 tests in 1.656s

OK (skipped=1)
Name                                                                       Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------
/usr/local/fbpackages/rest-api/acl_config.py                                   3      0   100%
/usr/local/fbpackages/rest-api/acl_providers/__init__.py                       0      0   100%
/usr/local/fbpackages/rest-api/acl_providers/cached_acl_provider.py           39      3    92%   52-53, 62
/usr/local/fbpackages/rest-api/acl_providers/common_acl_provider_base.py      41      1    98%   61
/usr/local/fbpackages/rest-api/async_ratelimiter.py                           19      1    95%   59
/usr/local/fbpackages/rest-api/boardroutes.py                                  2      0   100%
/usr/local/fbpackages/rest-api/common_auth.py                                 56      5    91%   57-60, 139
/usr/local/fbpackages/rest-api/common_logging.py                              32      2    94%   61, 71
/usr/local/fbpackages/rest-api/common_middlewares.py                          76     12    84%   48, 68-69, 76-80, 89-90, 125-126
/usr/local/fbpackages/rest-api/common_utils.py                                57     41    28%   21-29, 43-48, 52-67, 83-88, 96, 102-118
/usr/local/fbpackages/rest-api/common_webapp.py                               13      6    54%   9, 13-19
/usr/local/fbpackages/rest-api/redfish_account_service.py                     17      7    59%   25-34, 38-46
/usr/local/fbpackages/rest-api/redfish_base.py                                54     36    33%   98, 105, 121-125, 128-139, 150-153, 156-163, 166-169, 172
/usr/local/fbpackages/rest-api/redfish_bios_firmware_dumps.py                195    156    20%   23-24, 40-41, 45-46, 50-51, 55-56, 89, 96-102, 105-116, 119-172, 175-181, 184-209, 212-258, 265-278, 281-313
/usr/local/fbpackages/rest-api/redfish_chassis.py                             29      0   100%
/usr/local/fbpackages/rest-api/redfish_chassis_helper.py                     188    118    37%   58-60, 64-65, 69-70, 75, 93-104, 110-117, 125-131, 135-187, 193-200, 204-223, 253-254, 260-302, 308, 312, 336
/usr/local/fbpackages/rest-api/redfish_common_routes.py                       55      1    98%   29
/usr/local/fbpackages/rest-api/redfish_computer_system.py                     53     29    45%   19, 43-55, 58-61, 64-95, 98-115, 118-139
/usr/local/fbpackages/rest-api/redfish_log_service.py                         89      9    90%   32, 38, 45, 57, 88, 92, 116, 122, 143
/usr/local/fbpackages/rest-api/redfish_managers.py                           105     50    52%   23-32, 36-48, 52-57, 61-66, 71-93, 144-153
/usr/local/fbpackages/rest-api/redfish_powercycle.py                          60     10    83%   68, 79, 85, 93, 103, 125, 130, 132, 140, 145
/usr/local/fbpackages/rest-api/redfish_sensors.py                            118     27    77%   24-25, 29, 64, 98-101, 109-110, 128, 145, 204, 206, 208, 210, 212, 214, 220-236
/usr/local/fbpackages/rest-api/redfish_service_root.py                        27      8    70%   39, 41-42, 49-59, 63-2506
/usr/local/fbpackages/rest-api/redfish_session_service.py                     12      7    42%   7-21, 25-34
/usr/local/fbpackages/rest-api/rest_config.py                                 37      1    97%   103
/usr/local/fbpackages/rest-api/rest_fruid.py                                  18     15    17%   28-44
/usr/local/fbpackages/rest-api/rest_fscd_sensor_data.py                       30      3    90%   59-62
/usr/local/fbpackages/rest-api/rest_fwinfo.py                                 47      1    98%   78
/usr/local/fbpackages/rest-api/rest_gpios.py                                  22      4    82%   33-59
/usr/local/fbpackages/rest-api/rest_mmc.py                                    25      0   100%
/usr/local/fbpackages/rest-api/rest_modbus_cmd.py                             86     10    88%   105, 125-128, 133, 137-141, 172
/usr/local/fbpackages/rest-api/rest_pal_legacy.py                            171    141    18%   50-51, 55-70, 74-82, 86-94, 99-107, 111-118, 126-147, 152-199, 203-218, 222-232, 236-238, 242-247, 251-259
/usr/local/fbpackages/rest-api/rest_utils.py                                   4      0   100%
--------------------------------------------------------------------------------------------------------
TOTAL                                                                       1780    704    60%
[PYFLAKES]
[MYPY]
sh: reboot: command not found
sh: reboot: command not found
Success: no issues found in 72 source files
DURATION: 30
END: /usr/lib/rest-api/ptest
2021-12-06T08:16
STOP: ptest-runner
```

REST tests in CIT still pass

Reviewed By: doranand

fbshipit-source-id: 2f7ee28e53