netlakenext: fw-util: Refactor CPLD update to use external handler
Summary:
# Description
- Refactor the CPLD update logic in fw-util to call the external cpld-handler tool instead of implementing the I2C protocol directly. Update the platform CPLD type to LFMXO5-25.

- A new run_command helper function was added to execute shell commands via popen. The update, print_version, and get_version methods now construct and execute command-line calls to the cpld-handler utility.

- The default platform CPLD in platform.cpp is updated from MAX10_10M08 to LFMXO5-25 to match the current hardware.

- In the XO5 .jed file, the CPLD version string is not included like it is in the XO3. Therefore, the usercode (CPLD version) will not be printed during the update process.

- To obtain the CPLD version, we can only rely on the I2C command. The version format is a 4-byte hexadecimal value, e.g., "12345678".

# Motivation
- Aligns the codebase with the new LFMXO5-25 CPLD being used on the platform.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3484

Test Plan:
- build pass

- log
root@bmc-oob:~# fw-util server --version BIOS Version: NL405_ESPI CPLD
version: ffffffff
ME Version: SPS_05.00.04.100.0
VR_1V05_STBY Version: Infineon dc9ef246, Remaining Write: 46
VR_VCCIN/VR_1V8_STBY Version: Infineon 66e33f72,
Remaining Write: 22 VR_VCCANA_CPU Version: Infineon 4b411349,
Remaining Write: 46 VR_VDDQ Version: Infineon 7e5e4775,
Remaining Write: 46 VR_VNN_PCH Version: Infineon 43374369, Remaining Write: 46

root@bmc-oob:~# fw-util server --version-json cpld CPLD
CPLD version: ffffffff
  [
      {
          "COMPONENT": "cpld",
          "FRU": "server",
          "VERSION": "ffffffff"
      }
  ]

fw-util server --update cpld /tmp/Project_impl_1.jed Lock file: /tmp/cpld-handler_3.lock Starting to update LFMXO5-25
  NOTE DEVICE NAME:       LFMXO5-25-11BBG400*
  QF Size = 5767168
  Checksum = 0x03ab
  CFG Size = b0000
  JED File Checksum = 0x6203AB
  Timeout waiting for device ready
  Error: Device not ready.
  CPLD update failed
  Command exited with code: 255
  Upgrade of server : cpld failed

  root@bmc-oob:~# fw-util server --version cpld
  CPLD version: ffffffff

  root@bmc-oob:~# fw-util server --force --update cpld /tmp/Project_impl_1.jed
  Force upgrade of server : cpld not supported

Reviewed By: jamesatha

Differential Revision: D89915544

fbshipit-source-id: 062970b7c00429b2b6778a3e8bd1b554f31229b8