adding error message to better identify which subTest is failiing
Summary: adding an error message to assert func. to better identify which subTest is failing

Test Plan:
```FAIL: test_rest_endpoints (tests.fbttn.test_rest_endpoint.RestEndpointTest) (attrib='abc')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 144, in verify_endpoint_attributes
    msg="endpoint {} missing attrib {}".format(endpointname, attrib),
AssertionError: 'abc' not found in '{"Information": {"Description": "FBTTN Mezzanine Card"}, "Resources": ["logs", "sensors"], "Actions": []}' : endpoint /api/nic missing attrib abc
```

Reviewed By: vineelasmile, benwei13

fbshipit-source-id: 7fec9ab879