Fix rainiera6 build
Summary:
Without this change I'm getting the following error while
building:
```
$ bitbake rainiera6-image
ERROR: The following layer directories do not exist:
ERROR:    /data/users/jamesatha/openbmc/yocto/lf-master/meta-facebook/meta-yosemite5/meta-rainiera6
ERROR: Please check BBLAYERS in /data/users/jamesatha/openbmc/build-rainiera6/conf/bblayers.conf
```
It looks like upstream doesn't have the rainiera6 layer so adding the
stuff downstream for now and it seems to make progress

Test Plan: `bitbake rainiera6-image` isn't erroring out

Reviewed By: williamspatrick, williamdap

Differential Revision: D101825988

fbshipit-source-id: 6adb48e0f0361d3fc598ad86c254ea0a70f9b491