fby35: Support class2 12V-cycle secure during firmware update (#2159)
Summary:
Support to block 12V-cycle while updating BMC/ROM/NIC expansion CPLD.
For Class1: Before doing 12V-cycle, we will check the corresponding slot status.
For Class2: Before doing 12V-cycle, we will check the corresponding slot and NIC expansion status.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/2159

Test Plan:
1. Build and test pass on fby35 class2 system.
Do 12V-cycle while updating BMC/ROM/NIC expansion CPLD.

(1) NICEXP CPLD
root@bmc-oob:~# fw-util bmc --update cpld Y35CBB_E06_EVT_NEW_signed.rpd
rpd file size = 143360 bytes.
OnChip Flash Status = 0xFFFFFE18.
image type = 0x3.
Max10 Unprotect Sector 4.
Max10 Erase Sector 4
Erase sector SUCCESS.
Max10 Erase Sector 0
Erase sector SUCCESS.
Progress: Addr: 0x2EB30  [22 %]

root@bmc-oob:~# power-util slot1 12V-cycle
FW update for bmc is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed

"continue updating..."
rpd file size = 143360 bytes.
OnChip Flash Status = 0xFFFFFE18.
image type = 0x3.
Max10 Unprotect Sector 4.
Max10 Erase Sector 4
Erase sector SUCCESS.
Max10 Erase Sector 0
Erase sector SUCCESS.
Progress: Addr: 0x49FFC  [100 %]
 Done!
Upgrade of bmc : cpld succeeded

(2) BMC
root@bmc-oob:~# fw-util bmc --update bmc flash-fby35-12V_cycle_blk
Flashing to device: /dev/mtd6
Erasing block: 359/7311 (4%)

root@bmc-oob:~# power-util slot1 12V-cycle
FW update for bmc is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed

"continue updating..."
Flashing to device: /dev/mtd6
Erasing block: 7311/7311 (100%)
Writing kb: 29242/29242 (100%)
Verifying kb: 29242/29242 (100%)
Upgrade of bmc : bmc succeeded

(3) ROM
root@bmc-oob:~# fw-util bmc --update rom flash-fby35-12V_cycle_blk
Flashing to device: /dev/mtd12
Erasing block: 219/7311 (2%)

root@bmc-oob:~# power-util slot1 12V-cycle
FW update for bmc is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed

"continue updating..."
Flashing to device: /dev/mtd12
Erasing block: 7311/7311 (100%)
Writing kb: 29242/29242 (100%)
Verifying kb: 29242/29242 (100%)
Upgrade of bmc : rom succeeded

Reviewed By: williamspatrick

fbshipit-source-id: c6ecc4fbd8ca08e083ef07d26239f4705509cd83