Upstream aconf_util.sh
Summary:
# Description
A number of changes were made to bios_util.sh in order to support programming the aboot_conf via aconf_util.sh.

First off, a new `--partition` option is added to bios_uti.sh, which only performs the operation on that partition, as specified in the layout file. For the write action, yamp has an extra requirement to keep the pdr segment intact, so by default, the header and pdr sections are written. Yamp previously formulated the default aboot_conf as a script variable; this has been changed to materialize it as a file, bmc_aboot.conf (along with the other, cpu_aboot.conf), like in elbert.

To initialize the default aboot_conf into the image, the new `--init-aconf` option is to be used.

The native aconf_util.sh would create the aboot_conf partition of the image (only), then program it using the `--partition` option. To facilitate this, it leverages the routine used by bios_uti.sh: previously, bios_util.sh would create this "aboot_conf only" image, then merge it into the supplied image before programming. This is now done in one routine, and the supplied image from aconf_util.sh is `/dev/zero` to meet the same result. This routine, `create_aboot_conf_image`, is moved into board-utils.sh to be accessible by both scripts.

X-link: https://github.com/facebookexternal/openbmc.arista/pull/431

Test Plan:
First back up the flash:
```
root@bmc-oob:~# bios_util.sh read backup
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
```
Writing back the same flash results in an identical image, as indicated by the flashrom message:
```
root@bmc-oob:~# bios_util.sh write backup
Backing up pdr
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
512+0 records in
512+0 records out
 writing header and payload ...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using regions: "payload", "header".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading old flash chip contents... done.
Erasing and writing flash chip...
Warning: Chip content is identical to the requested image.
Erase/write done.
```
New fields were added to the default aboot_conf, so when using `--init-aconf`, bios_util.sh will now add these:
```
root@bmc-oob:~# bios_util.sh write backup --init-aconf
Using Aboot conf file: /etc/bmc_aboot.conf
 writing header and payload ...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using regions: "payload", "header".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading old flash chip contents... done.
Erasing and writing flash chip... Erase/write done.
Verifying flash... VERIFIED.
```
```
root@bmc-oob:~# bios_util.sh read backup2
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
```
```
root@bmc-oob:~# cmp backup backup2
backup backup2 differ: char 10461255, line 24030
```
Byte 10461255 is within the aboot_conf section, meaning everything before that is unaltered.
Now, read and visually compare the aboot_conf sections:
```
root@bmc-oob:~# dd if=backup of=ac1 bs=4096 count=5 skip=2554
5+0 records in
5+0 records out
```
```
root@bmc-oob:~# dd if=backup2 of=ac2 bs=4096 count=5 skip=2554
5+0 records in
5+0 records out
```
```
root@bmc-oob:~# hexdump -C ac1
00000000  42 4f 4f 54 5f 4d 45 54  48 4f 44 31 3d 53 56 42  |BOOT_METHOD1=SVB|
00000010  57 4e 6c 39 51 57 45 55  3d 0a 42 4f 4f 54 5f 4d  |WNl9QWEU=.BOOT_M|
00000020  45 54 48 4f 44 32 3d 54  45 39 44 51 55 77 3d 0a  |ETHOD2=TE9DQUw=.|
00000030  42 4f 4f 54 5f 4d 45 54  48 4f 44 33 3d 51 56 4a  |BOOT_METHOD3=QVJ|
00000040  4a 55 31 52 42 0a 00 00  00 00 00 00 00 00 00 00  |JU1RB...........|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00005000
```
```
root@bmc-oob:~# hexdump -C ac2
00000000  42 4f 4f 54 5f 4d 45 54  48 4f 44 31 3d 53 56 42  |BOOT_METHOD1=SVB|
00000010  57 4e 6c 39 51 57 45 55  3d 0a 42 4f 4f 54 5f 4d  |WNl9QWEU=.BOOT_M|
00000020  45 54 48 4f 44 32 3d 54  45 39 44 51 55 77 3d 0a  |ETHOD2=TE9DQUw=.|
00000030  42 4f 4f 54 5f 4d 45 54  48 4f 44 33 3d 51 56 4a  |BOOT_METHOD3=QVJ|
00000040  4a 55 31 52 42 0a 42 4f  4f 54 5f 4d 45 54 48 4f  |JU1RB.BOOT_METHO|
00000050  44 34 3d 55 6b 56 43 54  30 39 55 0a 43 4f 4e 53  |D4=UkVCT09U.CONS|
00000060  4f 4c 45 53 50 45 45 44  3d 4e 54 63 32 4d 44 41  |OLESPEED=NTc2MDA|
00000070  3d 0a 44 4d 49 5f 42 4f  41 52 44 5f 4e 41 4d 45  |=.DMI_BOARD_NAME|
00000080  3d 57 55 46 4e 55 41 3d  3d 0a 44 4d 49 5f 42 4f  |=WUFNUA==.DMI_BO|
00000090  41 52 44 5f 56 45 52 53  49 4f 4e 3d 4d 53 34 77  |ARD_VERSION=MS4w|
000000a0  0a 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00005000
```
Programming with bios_util.sh now adds the bmc aconf_util, as desired. Check the remaining sections:
```
root@bmc-oob:~# dd if=backup of=end1 bs=4096 count=1537 skip=2559
1537+0 records in
1537+0 records out
```
```
root@bmc-oob:~# dd if=backup2 of=end2 bs=4096 count=1537 skip=2559
1537+0 records in
1537+0 records out
root@bmc-oob:~# cmp end1 end2
```
They are the same.
Testing the `--partition` option:
```
root@bmc-oob:~# dd if=/dev/zero of=zeros bs=4096 count=4096
4096+0 records in
4096+0 records out
```
```
root@bmc-oob:~# bios_util.sh write zeros --partition normal
 writing partition(s) ...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "normal".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading old flash chip contents... done.
Erasing and writing flash chip... Erase/write done.
Verifying flash... VERIFIED.
```
```
root@bmc-oob:~# bios_util.sh read normal --partition normal
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "normal".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
```
```
root@bmc-oob:~# cmp normal zeros
```
A section of zeros was successfully programmed and read back. Next, write the "normal" partition from the (good) backup image.
```
root@bmc-oob:~# bios_util.sh write backup --partition normal
 writing partition(s) ...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "normal".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading old flash chip contents... done.
Erasing and writing flash chip... Erase/write done.
Verifying flash... VERIFIED.
```
```
root@bmc-oob:~# bios_util.sh read normal2 --partition normal
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "normal".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
```
Compare the "normal" partition read back with that of the backup image. The beginning is zero:
```
root@bmc-oob:~# dd if=normal2 bs=4096 count=2560 | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
2560+0 records in
2560+0 records out
```
Grab the "normal" section from the backup image:
```
root@bmc-oob:~# dd if=backup of=backup_normal bs=4096 count=1488 skip=2560
1488+0 records in
1488+0 records out
```
Compare them:
```
root@bmc-oob:~# dd if=normal2 bs=4096 count=1488 skip=2560 | cmp backup_normal -
1488+0 records in
1488+0 records out
```
They match.
Check that `--partition` and `--init-aconf` can't be used together:
```
root@bmc-oob:~# bios_util.sh write backup --partition normal --init-aconf
--init-aconf and --partition are mutually exclusive
Usage:
bios_util.sh <OP> <bios file> [--partition <partition>]
      <OP> : read, write, erase, recover
      [<partition>] : partition of layout file; defaults to total (all sections)
                      specify image for Aboot image sections
bios_util.sh write <bios file> [--init-aconf]
      If --init-aconf is specified, the aboot_conf section will be programmed
      after writing the bios file.
```
```
root@bmc-oob:~# bios_util.sh write backup --init-aconf --partition normal
--init-aconf and --partition are mutually exclusive
Usage:
bios_util.sh <OP> <bios file> [--partition <partition>]
      <OP> : read, write, erase, recover
      [<partition>] : partition of layout file; defaults to total (all sections)
                      specify image for Aboot image sections
bios_util.sh write <bios file> [--init-aconf]
      If --init-aconf is specified, the aboot_conf section will be programmed
      after writing the bios file.
```
Now, test aconf_util.sh.
```
root@bmc-oob:~# aconf_util.sh show
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "aboot_conf".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
Contents of aboot_conf:
BOOT_METHOD1=IPV6_PXE
BOOT_METHOD2=LOCAL
BOOT_METHOD3=ARISTA
BOOT_METHOD4=REBOOT
CONSOLESPEED=57600
DMI_BOARD_NAME=YAMP
DMI_BOARD_VERSION=1.0
```
Program the cpu conf, which is empty but always adds the board name & version:
```
root@bmc-oob:~# aconf_util.sh program cpu
Using Aboot conf file: /etc/cpu_aboot.conf
 writing partition(s) ...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "aboot_conf".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading old flash chip contents... done.
Erasing and writing flash chip... Erase/write done.
Verifying flash... VERIFIED.
```
```
root@bmc-oob:~# aconf_util.sh show
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "aboot_conf".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
Contents of aboot_conf:
DMI_BOARD_NAME=YAMP
DMI_BOARD_VERSION=1.0
```
Program the bmc conf from aconf_util.sh instead of bios_util.sh:
```
root@bmc-oob:~# aconf_util.sh program bmc
Using Aboot conf file: /etc/bmc_aboot.conf
 writing partition(s) ...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "aboot_conf".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading old flash chip contents... done.
Erasing and writing flash chip... Erase/write done.
Verifying flash... VERIFIED.
```
```
root@bmc-oob:~# aconf_util.sh show
Reading flash content...
flashrom v1.2 on Linux 6.1.51-yamp (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using region: "aboot_conf".
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Macronix flash chip "MX25L12835F/MX25L12845E/MX25L12865E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
Contents of aboot_conf:
BOOT_METHOD1=IPV6_PXE
BOOT_METHOD2=LOCAL
BOOT_METHOD3=ARISTA
BOOT_METHOD4=REBOOT
CONSOLESPEED=57600
DMI_BOARD_NAME=YAMP
DMI_BOARD_VERSION=1.0
```

Ran the yamp cit tests. The failures were all from `tests.yamp.test_fscd.FscdTestPwm` and also existed in the previous stable image.
```
======================================================================
FAIL: test_fscd_inlet_20_th3_11_duty_cycle_13 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 177, in test_fscd_inlet_20_th3_11_duty_cycle_13
    self.assertTrue(
AssertionError: False is not true : Expected 13 for all fans but received ['Fan 1 RPMs: 9771, 9771, (50%)', 'Fan 2 RPMs: 9756, 9756, (50%)', 'Fan 3 RPMs: 9771, 9771, (50%)', 'Fan 4 RPMs: 9724, 9724, (50%)', 'Fan 5 RPMs: 9756, 9756, (50%)', '']

======================================================================
FAIL: test_fscd_inlet_24_th3_46_duty_cycle_19 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 155, in test_fscd_inlet_24_th3_46_duty_cycle_19
    self.assertTrue(
AssertionError: False is not true : Expected 19 for all fans but received ['Fan 1 RPMs: 9756, 9756, (50%)', 'Fan 2 RPMs: 9771, 9771, (50%)', 'Fan 3 RPMs: 9740, 9740, (50%)', 'Fan 4 RPMs: 9724, 9724, (50%)', 'Fan 5 RPMs: 9756, 9756, (50%)', '']

======================================================================
FAIL: test_fscd_inlet_29_th3_32_duty_cycle_28 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 188, in test_fscd_inlet_29_th3_32_duty_cycle_28
    self.assertTrue(
AssertionError: False is not true : Expected 28 for all fans but received ['Fan 1 RPMs: 9756, 9756, (50%)', 'Fan 2 RPMs: 9756, 9756, (50%)', 'Fan 3 RPMs: 9740, 9740, (50%)', 'Fan 4 RPMs: 9724, 9724, (50%)', 'Fan 5 RPMs: 9740, 9740, (50%)', '']

======================================================================
FAIL: test_fscd_inlet_30_th3_15_duty_cycle_35 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 144, in test_fscd_inlet_30_th3_15_duty_cycle_35
    self.assertTrue(
AssertionError: False is not true : Expected 35 for all fans but  received ['Fan 1 RPMs: 9771, 9771, (50%)', 'Fan 2 RPMs: 9756, 9756, (50%)', 'Fan 3 RPMs: 9756, 9756, (50%)', 'Fan 4 RPMs: 9756, 9756, (50%)', 'Fan 5 RPMs: 9756, 9756, (50%)', '']

======================================================================
FAIL: test_fscd_inlet_34_th3_62_duty_cycle_56 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 166, in test_fscd_inlet_34_th3_62_duty_cycle_56
    self.assertTrue(
AssertionError: False is not true : Expected 56 for all fans but received ['Fan 1 RPMs: 9756, 9756, (50%)', 'Fan 2 RPMs: 9708, 9708, (50%)', 'Fan 3 RPMs: 9740, 9740, (50%)', 'Fan 4 RPMs: 9724, 9724, (50%)', 'Fan 5 RPMs: 9740, 9740, (50%)', '']

======================================================================
FAIL: test_fscd_inlet_36_th3_41_duty_cycle_73 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 210, in test_fscd_inlet_36_th3_41_duty_cycle_73
    self.assertTrue(
AssertionError: False is not true : Expected 73 for all fans but received ['Fan 1 RPMs: 9771, 9771, (50%)', 'Fan 2 RPMs: 9756, 9756, (50%)', 'Fan 3 RPMs: 9740, 9740, (50%)', 'Fan 4 RPMs: 9724, 9724, (50%)', 'Fan 5 RPMs: 9756, 9756, (50%)', '']

======================================================================
FAIL: test_fscd_inlet_38_th3_80_duty_cycle_73 (tests.yamp.test_fscd.FscdTestPwm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/yamp/test_fscd.py", line 221, in test_fscd_inlet_38_th3_80_duty_cycle_73
    self.assertTrue(
AssertionError: False is not true : Expected 73 for all fans but received ['Fan 1 RPMs: 9740, 9740, (50%)', 'Fan 2 RPMs: 9756, 9756, (50%)', 'Fan 3 RPMs: 9740, 9740, (50%)', 'Fan 4 RPMs: 9724, 9724, (50%)', 'Fan 5 RPMs: 9756, 9756, (50%)', '']

----------------------------------------------------------------------
Ran 201 tests in 1648.491s

FAILED (failures=7, skipped=50)
```

Reviewed By: lsiudut

Differential Revision: D87751389

Pulled By: joancaneus

fbshipit-source-id: 655a4f9610cd411547fc4a1685acb2e826e3b660