Fix missing mmc-info entry in /api/sys/bmc's schema
Summary:
From the failing test's output:
```
Traceback (most recent call last):
  File "/dev/shm/uid-30041/6f04428b-seed-nspid4026532648_cgpid67954179-ns-4026532645/bmc/tools/cit/api_validation_tests/test_api_matches_schema.py", line 90, in test_legacy_endpoints_valid
    raise ValueError(
ValueError: REST output from GET /api/sys/bmc does not match schema defined in 'common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api/sys/bmc.yml':
Output: {"Resources": [], "Actions": [], "Information": {"memory": {"Shmem": 324, "Buffers": 0, "Cached": 83732, "MemAvailable": 118168, "MemTotal": 242628, "MemFree": 117212}, "Description": "wedge100 BMC", "load-15": "0.86", "u-boot version": "2016.07", "uptime": "320.81", "OpenBMC Version": "2023.09.0", "mmc-info": {}, "CPU Usage": "CPU:  74% usr  26% sys   0% nic   0% idle   0% io   0% irq   0% sirq", "kernel version": "5.15.67-galaxy100 #1 Mon Feb 27 08:16:15 UTC 2023", "MTD Parts": ["u-boot", "env", "fit", "data0", "flash0", "flash1"], "At-Scale-Debug Running": false, "Secondary Boot Triggered": false, "MAC Addr": "00:E0:EC:62:A0:F6", "TPM FW version": "NA", "load-1": "2.01", "TPM TCG version": "NA", "Memory Usage": "Mem: 125416K used, 117212K free, 324K shrd, 0K buff, 83732K cached", "vboot": {"status": "-1", "status_text": "Unsupported"}, "Reset Reason": "Power ON Reset", "SPI0 Vendor": "Unknown", "load-5": "1.78", "open-fds": "374", "Uptime": "00:35:42 up 0:05:20, load average: 2.01, 1.78, 0.86", "SPI1 Vendor": "Unknown"}}
Schema errors:
'response':
    - 'body':
        - 'schema':
            - 'Information':
                - 'additionalProperties':
                    - "When `additionalProperties` is False, no unspecified properties are allowed. The following unspecified properties were found:
\t`{'mmc-info'}`"
Please fix incorrect endpoint/schema in 'common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api/sys/bmc.yml' and run test again.'
```

Looks like the `mmc-info` property was missing from the schema, copied the `mmc-info` definition from [wedge100/api/sys/bmc.yml](https://www.internalfb.com/code/yocto-meta-openbmc/[helium%3A27b179715d77bd763927a9e02bc376c5d8374df2]/common/recipes-rest/rest-api/files/swagger/definitions/wedge100/api/sys/bmc.yml?lines=95-122)

Test Plan:
Reproduce [sandcastle command](https://www.internalfb.com/intern/sandcastle/job/36028797911535341/insights) locally adding `--bmc-root "$HOME/openbmc" --regex '.*test_legacy_endpoints_valid.*'` so it uses the local repo and only runs the relevant test:

```
cd $(mktemp -d) && \
fbpkg fetch neteng.netcastle.runner && \
./netcastle.par --team openbmcfb --purpose continuous --jobs 1 --test-config galaxy100 --fbpkg-name openbmc.image.backpack100_fc_lc:d84699df87d6cbc3b2a9615472439fb6 --platform galaxy100 --skip-filtering-by-test-stat --bmc-root "$HOME/openbmc" --regex '.*test_legacy_endpoints_valid.*'
```

Check log output for successful result:

```
2023/03/03 07:09:51.101|161658|MainThread|I|test_case: Test setUp for test_api_matches_schema.ApiValidator.test_legacy_endpoints_valid
2023/03/03 07:09:51.242|161658|MainThread|I|test_api_matches_schema: Running GET /api
2023-03-03 07:09:51,283 DEBUG Starting new HTTPS connection (1): fboss57874250-lc401-oob.snc1.facebook.com:8443
2023-03-03 07:09:52,266 DEBUG https://fboss57874250-lc401-oob.snc1.facebook.com:8443 "GET /api HTTP/1.1" 200 115
2023/03/03 07:09:52.270|161658|MainThread|I|test_api_matches_schema: Ran GET /api, output: {"Information": {"Description": "Wedge RESTful API Entry", "version": "v0.1"}, "Actions": [], "Resources": ["sys"]}
2023/03/03 07:09:52.271|161658|MainThread|I|test_api_matches_schema: Validating response from /api using common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api.yml
2023/03/03 07:09:52.299|161658|MainThread|I|test_api_matches_schema: Running GET /api/sys
2023-03-03 07:09:52,569 DEBUG https://fboss57874250-lc401-oob.snc1.facebook.com:8443 "GET /api/sys HTTP/1.1" 200 222
2023/03/03 07:09:52.569|161658|MainThread|I|test_api_matches_schema: Ran GET /api/sys, output: {"Information": {"Description": "Wedge System"}, "Actions": [], "Resources": ["bmc", "fc_present", "firmware_info", "fscd_sensor_data", "gpios", "i2cflush", "mb", "ntp", "psu_update", "sensors", "server", "usb2i2c_reset"]}
2023/03/03 07:09:52.570|161658|MainThread|I|test_api_matches_schema: Validating response from /api/sys using common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api/sys.yml
2023/03/03 07:09:52.661|161658|MainThread|I|test_api_matches_schema: Running GET /api/sys/bmc
2023-03-03 07:09:53,862 DEBUG https://fboss57874250-lc401-oob.snc1.facebook.com:8443 "GET /api/sys/bmc HTTP/1.1" 200 1044
2023/03/03 07:09:53.863|161658|MainThread|I|test_api_matches_schema: Ran GET /api/sys/bmc, output: {"Information": {"uptime": "314.31", "SPI1 Vendor": "Unknown", "MTD Parts": ["u-boot", "env", "fit", "data0", "flash0", "flash1"], "kernel version": "5.15.67-galaxy100 #1 Mon Feb 27 08:16:15 UTC 2023", "SPI0 Vendor": "Unknown", "CPU Usage": "CPU:  80% usr  20% sys   0% nic   0% idle   0% io   0% irq   0% sirq", "Secondary Boot Triggered": false, "open-fds": "379", "OpenBMC Version": "2023.09.0", "load-1": "1.61", "TPM TCG version": "1.2", "mmc-info": {}, "memory": {"Buffers": 0, "Cached": 83724, "MemAvailable": 118456, "MemFree": 117404, "Shmem": 328, "MemTotal": 242628}, "TPM FW version": "133.32", "u-boot version": "2016.07", "Uptime": "07:09:53 up 0:05:14, load average: 1.61, 1.68, 0.81", "load-5": "1.68", "Reset Reason": "Power ON Reset", "Description": "wedge100 BMC", "vboot": {"status_text": "Unsupported", "status": "-1"}, "At-Scale-Debug Running": false, "Memory Usage": "Mem: 125224K used, 117404K free, 328K shrd, 0K buff, 83724K cached", "load-15": "0.81", "MAC Addr": "00:E0:EC:6C:5E:10"}, "Actions": [], "Resources": []}
2023/03/03 07:09:53.863|161658|MainThread|I|test_api_matches_schema: Validating response from /api/sys/bmc using common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api/sys/bmc.yml
2023/03/03 07:09:53.884|161658|MainThread|I|test_api_matches_schema: Running GET /api/sys/fc_present
2023-03-03 07:09:54,774 DEBUG https://fboss57874250-lc401-oob.snc1.facebook.com:8443 "GET /api/sys/fc_present HTTP/1.1" 200 176
2023/03/03 07:09:54.775|161658|MainThread|I|test_api_matches_schema: Ran GET /api/sys/fc_present, output: {"Information": {"Description": "Slotid indicates monitored slotid's status", "Monitored Slotid": 0, "Status": "Not Applicable", "Slotid": 401}, "Actions": [], "Resources": []}
2023/03/03 07:09:54.775|161658|MainThread|I|test_api_matches_schema: Validating response from /api/sys/fc_present using common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api/sys/fc_present.yml
2023/03/03 07:09:54.796|161658|MainThread|I|test_api_matches_schema: Running GET /api/sys/firmware_info
2023-03-03 07:09:57,928 DEBUG https://fboss57874250-lc401-oob.snc1.facebook.com:8443 "GET /api/sys/firmware_info HTTP/1.1" 200 141
2023/03/03 07:09:57.929|161658|MainThread|I|test_api_matches_schema: Ran GET /api/sys/firmware_info, output: {"SYS_CPLD": {"sub_version": 8, "version": 16}, "SCM_CPLD": {"sub_version": 3, "version": 17}, "QSFP_CPLD": {"sub_version": 1, "version": 1}}
2023/03/03 07:09:57.929|161658|MainThread|I|test_api_matches_schema: Validating response from /api/sys/firmware_info using common/recipes-rest/rest-api/files/swagger/definitions/backpack100_fc_lc/api/sys/firmware_info.yml
2023/03/03 07:09:57.941|161658|MainThread|I|test_case: Test tearDown for test_api_matches_schema.ApiValidator.test_legacy_endpoints_valid
2023/03/03 07:09:57.941|161658|MainThread|I|test_case: Finished test: test_api_matches_schema.ApiValidator.test_legacy_endpoints_valid
2023/03/03 07:09:58.242|161658|MainThread|I|test_case: Test output has been everpasted (https://www.internalfb.com/intern/everpaste/?color=1&handle=GGTauAj85vKHXJgCADdCIiZCB3AZbr0LAAAz)
```

Reviewed By: doranand

Differential Revision: D43748525

fbshipit-source-id: aa758bba4e852e9e1e787cb40ff558613c221018