log-util-v2: rsyslogd missing header
Summary:
Newer versions of GCC adjusted the automatic header inclusion and
reports the following error.

```
| rsyslogd.cpp:21:35: error: 'strerror' is not a member of 'std'; did you mean 'perror'?
|    21 |     throw std::runtime_error(std::strerror(errno));
|       |                                   ^~~~~~~~
|       |                                   perror
```

Test Plan: Compile is successful.

Reviewed By: amithash

fbshipit-source-id: db76f219f22bb86a2ec7ddb551526ee41782fe92