celesticabmc: host-recovery: Multi-process BIOS/IOB update mutual exclusion logic failed
Summary:
# Description

Fix a bug where Multi-process BIOS/IOB SPI update mutual exclusion logic failed

# Motivation

When a bios update process is running,the second update process is correctly fails with the "Another process is running" error. However, the third update process is allowed, which causes BMC reboot unexpectedly and bios update fail. Solution is to add an exit handler to receive the exit status of shell script. If the script exits without setup gpio and lockfile enviroment cleanup_spi function can not be executed.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1899

Test Plan:
**Case 1: When updating bios image, execute more bios update process in the same time.**
```
root@bmc-oob:~# bios_update.sh write NL405.bin
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
exporting gpio (aspeed-gpio, GPIOG4), shadow=BMC_IOB_FLASH_SEL
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
Writing NL405.bin to COME_BIOS...
dd: number 0 is not in 1..2147483647 range
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.5.1 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org/
Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (32768 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to 1ffffff
Verifying flash... VERIFIED.

root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
```
**Case 2: When updating bios image, execute iob update process in the same time.**
```
root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
Another process is running
```
**Case 3: When updating iob image, execute more iob update process in the same time.**
```
root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
exporting gpio (aspeed-gpio, GPIOG4), shadow=BMC_IOB_FLASH_SEL
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
/usr/local/bin/spi-utils.sh: line 63: echo: write error: No such device
Writing icecube_iob_v0.2.bin to IOB_FPGA...
dd: number 0 is not in 1..2147483647 range
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.5.1 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org/

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... done.
Updating flash chip contents... Erase/write done from 0 to ffffff

root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# iob_update.sh write icecube_iob_v0.2.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
```
**Case 4: When updating iob image, execute bios update process in the same time.**
```
root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
Cleanup: Execution failed or interrupted (Status 1)
root@bmc-oob:~# bios_update.sh write NL405.bin
Another process is running
```
**Case5: When updating iob image, Ctrl+C to interrupt exit before done, It has clean-up**
```
root@bmc-oob:/tmp# iob_update.sh write icecube_iob_v0.2.bin
exporting gpio (aspeed-gpio, GPIOQ6), shadow=SPI_MUX_SEL
exporting gpio (aspeed-gpio, GPIOG4), shadow=BMC_IOB_FLASH_SEL
exporting gpio (aspeed-gpio, GPIOG0), shadow=BMC_I2C1_EN
/usr/local/bin/spi-utils.sh: line 63: echo: write error: No such device
Writing icecube_iob_v0.2.bin to IOB_FPGA...
dd: number 0 is not in 1..2147483647 range
flashrom -p linux_mtd:dev=7 -w /tmp/temp_image
flashrom v1.5.1 on Linux 6.12.55-celesticabmc (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on linux_mtd.
Reading old flash chip contents... ^Cfailed to open gpio (shadow=BMC_I2C1_EN): No such file or directory
Error: Write failed
failed to open gpio (shadow=BMC_I2C1_EN): No such file or directory
failed to open gpio (shadow=BMC_IOB_FLASH_SEL): No such file or directory
failed to open gpio (shadow=SPI_MUX_SEL): No such file or directory
failed to unexport gpio (shadow=SPI_MUX_SEL): No such file or directory
failed to unexport gpio (shadow=BMC_IOB_FLASH_SEL): No such file or directory
failed to unexport gpio (shadow=BMC_I2C1_EN): No such file or directory
root@bmc-oob:/tmp# ls /var/run/spi_util.pid
ls: /var/run/spi_util.pid: No such file or directory
root@bmc-oob:/tmp#
```
[updateBIOS_multi_process_1.txt](https://github.com/user-attachments/files/24126282/updateBIOS_multi_process_1.txt)
[updateBIOS_multi_process_2.txt](https://github.com/user-attachments/files/24126284/updateBIOS_multi_process_2.txt)
[updateBIOS_multi_process_3.txt](https://github.com/user-attachments/files/24126285/updateBIOS_multi_process_3.txt)

Reviewed By: binhuang00

Differential Revision: D89045610

Pulled By: ezeob002

fbshipit-source-id: d89fc86a3abd5e10b91071c705aafacc62feb990