fby2: fix multi BMC firmware update issue (#2679)
Summary:
1. remove pal_set_fw_update_ongoing in pal.c, make BMC firmware update ongoing setting & checking are consistence on same file "/tmp/cache_store/fru7_fwupd"
2. increace MAX_NUM_FRUS to 7, ensure sled-cycle is blocked while BMC FW update is ongoing

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/2679

Test Plan:
Build and test passed on northdome

1. Test sled-cycle & BMC update while BMC firmware update ongoing
- session 1, start a BMC update process
```
root@bmc-oob:~# fw-util bmc --update bmc flash-northdome
Flashing to device: /dev/mtd6
Erasing block: 444/444 (100%)
Writing kb: 28370/28370 (100%)
Verifying kb: 28370/28370 (100%)
Upgrade of bmc : bmc succeeded
```

- session 2, run another BMC firmware update & sled-cycle should be blocked
```
root@bmc-oob:~# fw-util bmc --update bmc flash-northdome
Upgrade aborted due to ongoing upgrade on FRU: bmc
root@bmc-oob:~# power-util sled-cycle
FW update for bmc is ongoing, block the power controlling.
ERROR: power-util fru[255] [SLED_CYCLE] failed
```

Reviewed By: binhuang00

fbshipit-source-id: 2df97f20c2