acctonbmc: board-utils.sh: Fix wedge_power.sh reset issue
Summary:
# Description:
1. Check the x86 platform reset pin before performing a CPLD x86 power cycle.
2. Return EBUSY if the reset pin is not ready within 10 seconds.
3. Return EIO if triggering the CPLD x86 power cycle fails.
4. Return ETIME if retrieving the CPLD x86 power cycle status times out.

# Motivation:
Reset will not be triggered if wedge_power.sh reset is run again too soon.
It needs to wait for the platform reset pin to return to its normal state before triggering a CPU reset

X-link: https://github.com/facebookexternal/openbmc.accton/pull/221

Test Plan:
"bitbake acctonbmc-image" success

 --- CIT Log ---
-- Before applying this fix --
root@bmc-oob:/run/tests2# python cit_runner.py --platform acctonbmc --run-test tests.acctonbmc.test_wedge_power.WedgePowerTest
test_wedge_power_off (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_off)
Tests wedge power off ... ok
test_wedge_power_on (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on)
Tests wedge power on ... ok
test_wedge_power_on_force (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on_force)
Tests wedge power on with force ... ok
test_wedge_power_reset (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_reset)
Tests wedge power reset ... ERROR
test_wedge_power_status (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_status)
Tests wedge power status ... ok

======================================================================
ERROR: test_wedge_power_reset (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_reset)
Tests wedge power reset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/acctonbmc/test_wedge_power.py", line 185, in test_wedge_power_reset
    self.run_power_cmd_test("reset"), 0, "Power reset test failed"
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/run/tests2/tests/acctonbmc/test_wedge_power.py", line 124, in run_power_cmd_test
    return_code, _ = self.run_power_cmd(cmd)
                      ~~~~~~~~~~~~~~~~~~^^^^^
  File "/run/tests2/tests/acctonbmc/test_wedge_power.py", line 83, in run_power_cmd
    raise Exception(stderr.decode())
Exception: Reset timed out

----------------------------------------------------------------------
Ran 5 tests in 11.759s

FAILED (errors=1)

-- After applying this fix --
root@bmc-oob:/run/tests2# python cit_runner.py --platform acctonbmc --run-test tests.acctonbmc.test_wedge_power.WedgePowerTest
test_wedge_power_off (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_off)
Tests wedge power off ... ok
test_wedge_power_on (tests.acctonbmc.test_wedge_power.WedgePowerTest.test_wedge_power_on)
Tests wedge power on ... ok
test_wedge_power_on_force

Note: It also needs to change CIT wedge_power test flow.

Stress test WedgePowerTest 500 times success:
[wedge_power.sh_reset_20251101.log](https://github.com/user-attachments/files/23291243/wedge_power.sh_reset_20251101.log)

Run all CIT success:
[cit_run_test_all_20251101.log](https://github.com/user-attachments/files/23291266/cit_run_test_all_20251101.log)

Reviewed By: Scott8440

Differential Revision: D86384980

Pulled By: tao-ren

fbshipit-source-id: 486c73ba29710f8c61ac16f50e94217cb04769fc