kernel: config: explicitly enable CONFIG_I2C
Summary:
We periodically see failures building the
kernel-module-i2c-dev-sysfs package, which is a kernel module:

```
i2c_dev_sysfs.c:76:9: error: implicit declaration of function 'i2c_smbus_read_byte_data' [-Werror=implicit-function-declaration]
|    76 |   val = i2c_smbus_read_byte_data(client, dev_attr->ida_reg);
i2c_dev_sysfs.c:254:9: error: implicit declaration of function 'i2c_smbus_write_byte_data' [-Werror=implicit-function-declaration]
|   254 |   val = i2c_smbus_write_byte_data(client, dev_attr->ida_reg, val);
```

I was able to recreate this in cloudripper by doing the following:
```
bitbake cloudripper-image
bitbake linux-aspeed -c clean
bitbake kernel-module-i2c-dev-sysfs -c clean
bitbake kernel-module-i2c-dev-sysfs
```

Upon debug I found that the `CONFIG_I2C` is not set, which is used in
`include/linux/i2c.h` to wrap these function definitions.  What I think
is happening is that once the kernel is built the CONFIG_I2C is set due
to implicit dependencies by other kconfigs we have enabled (since we
obviously use a lot of I2C stuff), but if the out-of-tree module is
attempted to be build prior to that, the implicit configs are not yet
enabled and the compile fails.

By explicitly enabling CONFIG_I2C in any defconfig which didn't already
have it, it is always enabled for the out-of-tree module no matter the
build sequence order.

Test Plan: Rebuilt successfully with my failing scenario.

Reviewed By: doranand

fbshipit-source-id: f5efcd6c29ebe17ff2f7e8de798f08556ea128cd