Fix sensors unit test
Summary: It appears `snr.getInformation()` sometimes returns a value, but sometimes a coroutine (to calculate the value). So conditionally executing the coroutine if required.

Test Plan:
# How to test

Executed:
```
./tools/rest_api/rest_test_loop
```
and stopped, copied generated `run.do_unit_test` to `/tmp` and modified the path from
```
/data/users/xaionaro/openbmc/meta-facebook/meta-fby2/meta-fby2-nd/tmp/work/x86_64-linux/rest-api-native/0.1-r1
```
to
```
common/recipes-rest/rest-api/files
```

Then executed `/tmp/run.do_unit_test`

# Before
{P463536614}

# After
{P463536562}

# In total

Before:
```
Ran 116 tests in 0.898s
```

After:
```
Ran 125 tests in 1.474s
```

# Error samples

Before:
```
AssertionError: <coroutine object sensorsNode.getInformation at 0x7f440b9ed4d0> != {'MB_INLET_TEMP': {'value': '32.62'}}
```

After:
```
AssertionError: [] != {'MB_INLET_TEMP': {'value': '32.62'}}
```

Reviewed By: zhdaniel12, deathowl

fbshipit-source-id: 78d0eb8c9f646e1464a1dd8259b5a74c1698561a