wedge100: psumuxmon: fix AttributeError caused by typo
Summary:
Update "server_power_is_on" to "userver_power_is_on" to fix below error
detected on "fboss.autotest:wedge100s:fboss12719856.snc1" with a single
AC PSU.

wedge100-v2021.13.1: psumuxmon.py[535]: Traceback (most recent call last):
wedge100-v2021.13.1: psumuxmon.py[535]:   File "/usr/local/bin/psumuxmon.py", line 1172, in <module>
wedge100-v2021.13.1: psumuxmon.py[535]:     pcard.run()
wedge100-v2021.13.1: psumuxmon.py[535]:   File "/usr/local/bin/psumuxmon.py", line 1134, in run
wedge100-v2021.13.1: psumuxmon.py[535]:     self.ltc4281_detect(ch)
wedge100-v2021.13.1: psumuxmon.py[535]:   File "/usr/local/bin/psumuxmon.py", line 642, in ltc4281_detect
wedge100-v2021.13.1: psumuxmon.py[535]:     self.power_consumption_reduction()
wedge100-v2021.13.1: psumuxmon.py[535]:   File "/usr/local/bin/psumuxmon.py", line 247, in power_consumption_reduction
wedge100-v2021.13.1: psumuxmon.py[535]:     if self.server_power_is_on():
wedge100-v2021.13.1: psumuxmon.py[535]: AttributeError: 'Pcard' object has no attribute 'server_power_is_on'

Test Plan:
Bootup fboss12719856-oob.snc1:
  - log without fix: https://www.internalfb.com/phabricator/paste/view/P415749225
  - log with fix: https://www.internalfb.com/phabricator/paste/view/P415749307

Reviewed By: joancaneus

fbshipit-source-id: e6456d44bb