fix drun run test
Summary:
dryn run kept on failing because of the command that was passed
in the json. The command is extracted to a file by itself where we use
nondpe and dpe as argument to check the register value.

Test Plan:
Dryrun test was failing before like this:
```
/bin/sh: -c: line 0: `echo dryrun: if [ $(head -n 1
/sys/bus/i2c/drivers/scmcpld/12-0043/dpe_image) != '0x1' ]; then  echo
'non dpe image detected. exiting...'; exit 1; fi'
ERROR

======================================================================
ERROR: test_fw_upgrade_dryrun
(tests.elbert.fw_test_upgrade_dryrun.FwUpgradeDryrunTest)
Test that the firmware binary hash matches the ones in the json
----------------------------------------------------------------------
Traceback (most recent call last):
File
"/usr/local/bin/tests2/common/fw_test_base_upgrade_all_dryrun.py",
line 59, in test_fw_upgrade_dryrun
FwUpgrader(self.json, self.binPath, dryrun=True).run_upgrade()
File "/tmp/fw_upgrade/entity_upgrader.py", line 486, in
run_upgrade
entity_failure_list = FwEntityUpgrader(
```

After modifying the code, dryrun test pass
```
root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --fw
--run-test
tests.elbert.fw_test_upgrade_dryrun.FwUpgradeDryrunTest.test_fw_upgrade_dryrun
test_fw_upgrade_dryrun
(tests.elbert.fw_test_upgrade_dryrun.FwUpgradeDryrunTest)
Test that the firmware binary hash matches the ones in the json ...
dryrun: /usr/local/bin/bios_util.sh write
/tmp/fw_upgrade/coreboot-elbert.rom
dryrun: fpga_util.sh scm program /tmp/fw_upgrade/elbert_scm.astp
ok

----------------------------------------------------------------------
Ran 1 test in 7.293s

OK
root@bmc-oob:/usr/local/bin/tests2#
```

Reviewed By: binhuang00

fbshipit-source-id: 2651363d92